### ISSUE TITLE
Getting somone elses whispers and not getting mine

### ISSUE THREAD

**Issue by wnxace** [lemasato/POE-Trades-Companion#103]
Woke up today to 5 messages for items i don't have and tabs I don't own, then had my friend pm me and i also didn't get the message to show up on trade companion... was working just fine 9 hours ago when i fell asleep, didn't close it, my browser or poe any ideas? reloaded Poe, reloaded companion, and web browser...

**Comment by lemasato** [comment]
Is the tool now working properly or are you still unable to get trade infos to show on the interface?

About "receiving someone else's whispers and not mine", what do you mean?
The information shown on the interface is directly parsed from your Client.txt file. If you get a trade request for item X located in tab Y, then it means you received a whisper matching those infos.
