### ISSUE TITLE
'Fontin Small Caps' font issue

### ISSUE THREAD

**Issue by LaplaceNoMa** [lemasato/POE-Trades-Companion#105]
Hi,

There's been an issue in PoE with this font: https://www.pathofexile.com/forum/view-thread/2119808

 The game uses its own bundled version of the font that doesn't have the problem with the combination of letters 'FFI' (visible on items like Conqueror's E   ciency, or pressing Alt on any items and seeing the broken 'Su   xes' word). As soon as PoE Trades Companion is launched, apparently it installs its own version of the font in windows. Following the advice in the thread I've linked, I uninstalled the font, and after restarting windows, the problem in game was gone; however, now Trades Companion tells me the font is missing, even though I chose another font in settings.

**Comment by lemasato** [comment]
I'll inspect on this.

**Comment by lemasato** [comment]
I could confirm the issue (and it's most likely general with all Trades Companions users) but I haven't found a decent solution that doesn't require user's input yet.  To be honest, I think that forcing the fonts to be installed on the system is a bad idea generally, but it's required for the ImageButton class.

**Comment by lemasato** [comment]
Update: I got ImageButton to work with private fonts.
Will make sure that it works correctly, then the modifications will be pushed to Trades Companion.

**Comment by lemasato** [comment]
Hi, [[1.12.5]](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.12.5) has been released.  
Fonts are no longer required to be installed on the system.  

- If you don't plan on using Fontin SmallCaps in other programs (photoshop/etc), you can safely uninstall it from Windows.
- If you wish to keep it:
Run Trades Companion at least once after updating so the new font file can be extracted.
Install the updated version of the font from `\Documents\AutoHotkey\POE Trades Companion\Fonts`.

Once either is done, reboot your system and text will appear correctly in game.

Thanks a lot for reporting about this!
