### ISSUE TITLE
Error: Invalid option.

### ISSUE THREAD

**Issue by Aerevia** [lemasato/POE-Trades-Companion#106]
Hello,

I have this error whenever I try to open trades companion : 

![image](https://user-images.githubusercontent.com/13220181/41277402-6bedc8fe-6e27-11e8-8b3c-c01c1c709aa3.png)

It prevents it from loading the GUI. Before I got this error, I added a custom button which was working well. Then I tried changing the skin and it started appearing when re-drawing interface.
I have access to settings and tried re changing skin but the error is still there.

Have any idea of what could be causing this ?
Great tool though !

**Comment by lemasato** [comment]
Seems it's related to one of the smaller "special" buttons.  
One easy way to fix it is to edit the ini file:

- Close Trades Companion.
- Head to `Documents\AutoHotkey\POE Trades Companion\Preferences.ini`
- Look for the [CUSTOMIZATION_BUTTONS_UNICODE] section.
Delete all of the keys inside that section.
- Reload Trades Companion. The deleted settings will be reverted to default.

Sorry you have to deal with this, I know the tool is a mess code-wise at the moment.  
Next major update contains something against this. Once a setting will be out of the "allowed range", it will be reset to default automatically to avoid such issues.

**Comment by Aerevia** [comment]
Thanks for the quick answer and for your work, it fixed the problem
