### ISSUE TITLE
Popup opens minimized if POE window isnt selected during trade whisper.

### ISSUE THREAD

**Issue by sclient** [lemasato/POE-Trades-Companion#107]
This has been a very long term issue. I get pretty anxious about it, I have to admit, bc often in trades if you dont respond w/in the 10 second wait period that is minimum for a lot of traders, they will move on to look for another seller, and the ~3 extra seconds it takes to select the POE window, unminimize the helper, and finally party request the buyer can put it just past the end of that time frame.

Love this tool, and while it looks like I will resort to also using mercury for the global 820 filter and buff timers, I will always recommend this over MT (and have many, many times on reddit).

**Comment by lemasato** [comment]
So, when you are tabbed out of the game, if you receive a trading whisper, the interface does not auto un-minimize itself?
But if you receive a trading whisper while the game window is on focus, the auto un-minimize works just fine?

Honestly, if you like what MercuryTrade offers better, go for it!
While I personally find that the interface is overly complicated, some of their extra features are pretty neat.
I want to keep this tool focused around making trading better/easier, so the grid thing that shows your item location would be handy, and I'd certainly like to add something similar in the future. But others such as Flask/Skill timer are simply out of my ideology for Trades Companion.

I made a separate [notifier tool](https://github.com/lemasato/POE-Keyword-Notifier) for global 820 stuff, but it's still very basic (it sucks) and most likely nowhere near as fleshed out as MercuryTrade.

**Comment by sclient** [comment]
Well, I dont tab out, I have two screens, and often something is selected on the other screen, but Im assuming yes, the same thing will happen while tabbed out.

You know, I will take a look at your other tool.. But really, since you are a coder and everything, I would ask if youd consider taking a look at this for some debugging (It randomly crashes, most frequently after you enter the settings, and sometimes it just stops capturing global and sits there dead). I really like this tool, bc MT just beeps if w/e you want shows up, then you have to dig through a light speed scrolling chat to try and find it, this thing actually highlights the hit it got, and if you click on the chat line, it copies a whisper. It would be REALLY helpful if it didnt show all the non matching chat lines so you didnt have to struggle to click the one you want b4 it scrolls off, but its SUPER useful if it could be debugged. The original author only made 2 releases and abandoned it, Bunni did 2 and then also abandoned it, and since I tried to report the crash issue, he also closed the issue page. :(

https://github.com/Bunni/global820

I wouldnt ask you to add any of the MT stuff, and I will always primarily use your tool for the trade aspect, it just works better (but yeah, the grid is super nice).

**Comment by sclient** [comment]
Yes, that setting has always been on.

It would be really cool if that had any features you could think of putting in it. I like mercury trade's ability to override flagged hits for certain keys, as I was mentioning (like if Im looking for the word free/wild, it would be nice if I could blacklist 'boss' 'uber' and 'trial' from the hits) If you'd add that sort of blacklist, that would be super useful, and Id probably only be left with the buff timers to use MT with. It looks like it'll be real helpful for keeping arcane surge up, and knowing exactly when flask time has come again.

**Comment by sclient** [comment]
OMG I totally missed the minimize when inactive option. I just needed to uncheck that is all. My bad.

**Comment by sclient** [comment]
For a second there I was thinking I needed to just turn off minimize when inactive, but thats what makes it minimize with no queues and alters the opacity, so I cant disable that.

**Comment by sclient** [comment]
Oh! If there could be a checkbox in Trades Helper so it wouldnt give me beta update popups when the main version is already fully updated to the latest final release, that would be very helpful, as I tend to reflexively click on update requests, and dont want to end up with a beta by accident. Maybe if the beta option is unchecked it can not give those notices.

**Comment by lemasato** [comment]
@sclient 
Hey. Wondering, should this be closed?
