### ISSUE TITLE
[Feature request] Toggle button for automatic un-minimize when active

### ISSUE THREAD

**Issue by darorl89** [lemasato/POE-Trades-Companion#109]
Hey, it would be nice to have automatic  un-minimize toggle next to open/close toggle, so you cen set it off while you don't want to be disturbed by popups and don't want to do /dnd.

**Comment by lemasato** [comment]
Like a toggle on/off button to allow/prevent Trades Companion from picking up trading whispers?  
Sounds good. Probably via a menu by right clicking on the Trades GUI, so users don't accidentally click on it.
Nice suggestion, thanks!

**Comment by darorl89** [comment]
Specifically to turn off un-minimize when someone whispers if you are busy and don't want your screen covered by a popup. Would be a nice if button would be easily accesible on the title bar.

**Comment by lemasato** [comment]
Oops, looks like I misunderstood your post.  
So, prevent the GUI from un-minimizing itself? Isn't that what the "Un-minimize when active" setting does?
