### ISSUE TITLE
[Feature request] different sound for different trades

### ISSUE THREAD

**Issue by deduijk** [lemasato/POE-Trades-Companion#110]
It would be nice to set sounds for different thresholds.
Thresholds you can set yourself. 
Might be hard to determine absolute value across different currency, but in that case maybe several thresholds?
(1 for chaos trades, one for chisel trades, one for alc trades, 1 for ex trades.... and one for everything else).

I.e.: 
Anything lower then let's say 10C gets sound A, 
Anything between 10C and 50C gets Sound B,
Anything higher gets Sound C.

(10 and 50 thresholds to be set by user .. in begin u probably want different sounds for the trades then midway through a season...)

If value in C can be calculated and 1 threshold can be set for all that would be very nice, but that probably requires parsing of poe.ninja data or something, which might influence start-up time [i presume that data would be fetched and parsed at start then only]).

Thanks!

**Comment by lemasato** [comment]
Meh. While this sounds cool, it's one of these gimmick feature that only a handful of people would use.  
Sorry, but that's not something I'd want to see.

**Comment by deduijk** [comment]
I understand, although i doubt only a few would use it.. 
And even so, it probably would be used by the heavy traders, that use this feature a lot, so it would still get a lot of use i.m.h.o.

Thanks for considering it. too bad it won't make the cut. (thought it wouldn't  be a very difficult feature that has the potential to be great.). I would see it as an optional (so default turned off, that way the less experienced user isn't required to set it up).

**Comment by lemasato** [comment]
Sooo. This could be added someday. But I still need to decide how'd that work out and there are still a lot of other priorities first (new interface, chat notifications, probably other things).

Could work by giving options to set thresholds in chaos or exalt, and allow to choose a custom sound file for those.

**Comment by lemasato** [comment]
I'll be closing this issue to keep the issues tab cleaner as those are on my consider/to-do list. A page will be opened with future possible updates.
