### ISSUE TITLE
Windows 10 - Windows Store Opening on Launch 

### ISSUE THREAD

**Issue by IRKZ** [lemasato/POE-Trades-Companion#111]
Every time I attempt to launch the application [version 1.12.5], I am given a popup asking to open the windows store before I am allowed to run the application. It brings up the window store then admin privileges then finally runs.

**Comment by lemasato** [comment]
- Were you using POE Trades Companion prior to 1.12.5?
If so, would the issue also happen back then?
- If you never had the issue before, could you see if it happens now even on prior versions? [1.12.4](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.12.4)

**Comment by IRKZ** [comment]
Hello there,

1. I was not using POE TC prior to 1.12.5, I've only started using it.
2. When launching 1.12.4, I green text box saying reloading for admin privileges before the app launches, no windows store popup happens.
3a. Running 1.12.5 as admin directly still has the windows store issue popup.
3b. Running 1.12.4 as admin directly just launches the app.

**Comment by IRKZ** [comment]
Here is a video showing it. During the 'black out' UAC asks to run the application: https://youtu.be/vwLL_y1c3hE

**Comment by lemasato** [comment]
If you click on yes, does it search for anything specific on the store?

**Comment by lemasato** [comment]
I recompiled the executable using AHK v1.1.28.02: [POE Trades Companion](https://github.com/lemasato/POE-Trades-Companion/raw/open-win-store-on-launch%23111/POE%20Trades%20Companion.exe).  
Could you try it out?

**Comment by IRKZ** [comment]
When clicking yes, nothing happens and the recompiled version has the same issue.

**Comment by lemasato** [comment]
Hi,

I did all the googling around possible, but I couldn't any reliable informations about it.
Do you also get the popup when [using the source code](https://github.com/lemasato/POE-Trades-Companion/wiki/Usage)? 

If you do, try this executable and tell me if it also gives the popup: [WinstorePopup.zip](https://github.com/lemasato/POE-Trades-Companion/files/2181745/WinstorePopup.zip)
