### ISSUE TITLE
Inconsistent copy to clipboard for bulk map trades

### ISSUE THREAD

**Issue by artofvs** [lemasato/POE-Trades-Companion#112]
Hello. Great tool overall, but i've been having one small annoyance with map bulk trades.
When I recive a msg like this:
"Hi, I'd like to buy your 5 Shaped Coral Ruins for my 20 chaos in Incursion."
script will copy "5 Shaped Coral Ruins" to clipboard instead of "Shaped Coral Ruins" which makes pasting in to highlight needed map into map stash tab impossible.
Would be great if it would work as single items.
Thank you for your work.

**Comment by lemasato** [comment]
Guess I could exclude numbers when clipboarding items.
No item or currency have numbers in their name (aside from gem lvl/qual and map tier), so that'd work great.

Thank you for reporting!

**Comment by lemasato** [comment]
Added as of 1.12.6.
Sorry the update didn't hit earlier. I was waiting in case another issue would rise up, and then I had to work on other things.

Thank you for reporting about this!
