### ISSUE TITLE
[Feature request] Track how long time it takes to sell an item

### ISSUE THREAD

**Issue by zeuz542** [lemasato/POE-Trades-Companion#113]
I am really missing that feature, it would be great when trying to get the best prices. Some items go really fast and could probably have fetched an better price.

Also add it as an column to my stash.

Could probably be done by running queries against poe.trade. It shows that information there.

**Comment by lemasato** [comment]
> Track how long time it takes to sell an item to get the best prices

Not so useful actually. Prices gradually change over time.  
The best way to fetch the best price is to compare similar items on poe.trade. Using TradeMacro advanced search, it usually takes only a few seconds to fill the form and get a rough estimate of your item's worth.  
It's all about knowing the market.  

Also, I'd like to avoid having to interact with other websites.
As of now, the only useful interaction with trading websites would be to make sure the whisper price wasn't modified (avoiding scams).

So yeah, sorry but won't happen.
