### ISSUE TITLE
My Stats?

### ISSUE THREAD

**Issue by pdzbw** [lemasato/POE-Trades-Companion#115]
Is it disabled? I couldn't find a way to activate it, and the things showed on the window are from 2007

**Comment by lemasato** [comment]
From 2007?
Your OS time must have been off at the time.

To have your trade saved, you have to close the tab using a Custom Button that has the "Save the trade infos locally?" checkbox enabled.

**Comment by pdzbw** [comment]
Got it ~ my bad didn't read the button page carefully~ tyvm!
