### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by merubhanot** [lemasato/POE-Trades-Companion#116]
Not sure why, I've been getting this error for a while (may have minor typos, I typed it out from the error message)

Error: Invalid option.
Specifically: x
Line#
--->             799: Gui,Trades:Add,Button,"x" btnPos_X " y"
btnPos_Y*scaleMult " w" btnPos_W*scaleMult " h" btnPos_H*scaleMult "
hWnd" btnHandler " BackgroundTrans
gGui_Trades_Do_Action_func",fontChars[btnType]

The current thread will exit.

**Comment by lemasato** [comment]
One of your Special Buttons slot is invalid.  
Follow the same steps as described here: [#106](https://github.com/lemasato/POE-Trades-Companion/issues/106)

**Comment by merubhanot** [comment]
Great, that works, thanks!
