### ISSUE TITLE
FPS drops

### ISSUE THREAD

**Issue by fchatred** [lemasato/POE-Trades-Companion#118]
Dropping roughly 15-20 FPS when running the PoE-Trades-Companion. I've tried using the exe and the AHK script itself and still having the problem. The problem stops once I close out of the script or the exe.

I found an old issue detailing this same problem here; https://github.com/lemasato/POE-Trades-Companion/issues/96 and went to follow this advice "POE Trades Companion.ahk: At line 725, change SetTimer,% A_ThisFunc, -%timer% to ; SetTimer,% A_ThisFunc, -%timer% and run the file. If you don't get performance hits anymore after that, see if changing SetTimer,% A_ThisFunc, -%timer% to SetTimer,% A_ThisFunc, -1000" However, upon editing it I did not see that at line 725 and ctrl+f didn't find anything either.

System specs:
OS: Windows 7 Home Premium SP1
CPU: AMD FX 6300 3.76 GHz
RAM: 8GB G.Skill Ripjaw ram 1600Mhz dual channel
GPU: AMD R9 380x Nitro
Mobo: MSI 970A-G43
SSD: ADATA SU650 120GB

Really love the program as I've used it before and really appreciate any help.

Update: Overclocked my CPU to 4.6GHz, ram to 1866MHz and getting stable 110 fps in hideout with PoE Trade Companion closed and as soon as I poen PoE Trade companion  I go to a stuttery 50 fps.

**Comment by lemasato** [comment]
> CPU: AMD FX 6300 3.76 GHz
GPU: AMD R9 380x Nitro

I used to have a FX6300 aswell, never had that issue back then.
Never had an AMD GPU though, but I don't think it's related.

> Really love the program as I've used it before and really appreciate any help.

Has the issue appeared recently or has it always been happening?

&nbsp;  
- On the task manager, do you see any difference with TradesCompanion running/closed?
Head in your hideout, compare the CPU usages.
- Does the issue only occurs with POE or also with other games?

**Comment by fchatred** [comment]
> Has the issue appeared recently or has it always been happening?
That I'm not 100% sure about. I believe it's always happened which is why I stopped using it in the first place.

> On the task manager, do you see any difference with TradesCompanion running/closed?
Head in your hideout, compare the CPU usages.
Alright so I compared both and the first screenshot is without trade companion and the second is with.

From where I overclocked to 4.6 (now down to 4.4 due to overheating issues) I'm dropping 50 FPS, which may not seem that bad as I'm still getting 50 but the game is very stuttery and choppy and that's just in the hideout.

Another interesting note is the CPU usage was generally lower with PoE trade companion open which is really odd. Usually anywhere from 3-10% lower while it fluctuated.

![poe cpu no trade companion](https://user-images.githubusercontent.com/27310778/42532306-1fbfe094-844c-11e8-908f-2f5fca2a9a72.png)
![poe cpu trade companion](https://user-images.githubusercontent.com/27310778/42532319-256e03f4-844c-11e8-8cb7-a70ba58af2cc.png)

> Does the issue only occurs with POE or also with other games?
Yup, definitely only happens with PoE. This might help to know as well but, it also happens with MercuryTrade and POE Lab Compass. So that leads me to believe it may be due to the scanning of cleint.txt however, like I mentioned in the OP I changed the values in PoE Trade Companion to no avail.

**Comment by lemasato** [comment]
You should check from the Processes tab. It's much more detailed, and also allows to see if something else interferes when the FPS drop occurs.

In my opinion, the fps drop is caused by either:
1. Having an "overlay" on top of your game.
Could be lowering POE priority.
2. Reading the Client.txt.
Could be due to something with the system, or an overly protective scan.
#
1. Do you have multiple monitors?
If so, could you move TradesCompanion on your secondary screen to see if that makes any changes FPS-wise? If not, try putting your game in Windowed 800x600 and put the TradesCompanion window away from the game. (If you can't move TradesCompanion, right click on the tray icon and choose `Mode: Window`)

1. Could you try [Keyword Notifier](https://github.com/lemasato/POE-Keyword-Notifier) and see if you get the same issue?
Keyword Notifier has both a GUI and scan the Client.txt file.
If the FPS drops, try this app: [FpsDrops.zip](https://github.com/lemasato/POE-Trades-Companion/files/2181980/FpsDrops.zip). It scans the Client.txt file, but once every 30 seconds.

**Comment by fchatred** [comment]
So the only thing I tried was moving it to another monitor and it worked. You're a genius. So what exactly would be causing this and is there anyway to fix it so I can have it sitting on top of PoE?

**Comment by fchatred** [comment]
> Wondering... Do you also get FPS issue if you set the Task Manager to be always on top? (Options > Always on top)

Nope no FPS issues with Task Manager always on top.

However, testing it with the game Tekken 7 and having the overlay on top also reduces the FPS in that game. So something with drawing/rendering it above other windows? It's interesting that task manager has no effect though while PoE-Trades-Companion, Mercurytrade and Lab compass do.

I also changed the priority of PoE and Trade companion to no avail. My next step will be trying to change the driver unless that above gives you anymore info into possibly another option I could try.

**Comment by lemasato** [comment]
> unless that above gives you anymore info into possibly another option I could try

Try these: [fpsdrop_#118.zip](https://github.com/lemasato/POE-Trades-Companion/files/2182250/fpsdrop_.118.zip). There are three executables. One is a simple GUI. The second is a simple GUI but that is always on top. The third is a borderless GUI that is always on top.

**Comment by fchatred** [comment]
> Try these: fpsdrop_#118.zip. There are three executables. One is a simple GUI. The second is a simple GUI but that is always on top. The third is a borderless GUI that is always on top.

Okay, so good news. All three of those had 0 affect on my FPS. 

Now, I have some even better news which may solve this problem or give you a better idea of why it's happening. So, out of curiosity I enabled Windows Aero again (Running Windows 7 Home Premium SP1), I usually have Aero turned off due to input lag due to me playing fighting games. Once, I re-enabled aero and ran PoE-Trade-Companion no FPS drops.

Just to verify I disabled aero once again and loaded up PoE-Trade-Companion and it dropped FPS like it always did. So I'm not sure if this is something that can be fixed and if not I'll go back to using Aero but, I'd just thought I'd let you know. I really appreciate all your help so far. Let me know if you want me to test anything else.

**Comment by lemasato** [comment]
> Once, I re-enabled aero and ran PoE-Trade-Companion no FPS drops.

Damnit. I swear this was on my mind ever since you posted that Task Manager screenshot. But I thought it was silly, and couldn't be related...

> I really appreciate all your help so far

And so do I. Thank you for having been through all of this.

One more weird request:
- Turn on Aero. Run TradesCompanion, wait for it to load completely. Turn back off Aero.
Are your FPS fine this way?
- Also try it the other way around. Aero turned off. Run TC. Turn Aero back on.

**Comment by fchatred** [comment]
> Turn on Aero. Run TradesCompanion, wait for it to load completely. Turn back off Aero.
    Are your FPS fine this way?  Also try it the other way around. Aero turned off. Run TC. Turn Aero back on.

Okay, so I turned on Aero, loaded TC and turned Aero off. So FPS was was fine with Aero on and as soon as I turned it off and it dropped back down.

Next I did, Aero off TC loaded FPS was bad. Turned Aero on immediately after and the FPS went back to normal. So it seems like TC doesn't like having Aero turned off for some reason.
