### ISSUE TITLE
Nonexisten menu item

### ISSUE THREAD

**Issue by dome970** [lemasato/POE-Trades-Companion#119]
Hey, im having thiis issue when im trying to launch the Poe Tracdes Companion not sure what to do about it.

![screen](https://user-images.githubusercontent.com/20746471/43106550-69fa70a6-8ed9-11e8-9835-16826d88a7f3.png)

Thanks in advance for your time and effort ;)

**Comment by lemasato** [comment]
Hi,
Sorry you're having this issue.  
You can fix it by heading in your `\Documents\AutoHotkey\POE Trades Companion\Preferences.ini`. In the `[SETTINGS]` section, look for `Trades_GUI_Mode=` and set it to `Trades_GUI_Mode=Window` or delete the line.

**Comment by dome970** [comment]
No worries, it fixed it ;), i realy enjoy your programm keep up the good work.
Thanks a lot
