### ISSUE TITLE
Release 1.12.7 - Windows Defender detected Trojan:Win32/Occamy.C

### ISSUE THREAD

**Issue by Anvirol** [lemasato/POE-Trades-Companion#122]
Also happened with previous version I was using.

https://go.microsoft.com/fwlink/?linkid=37020&name=Trojan:Win32/Occamy.C&threatid=2147726780&enterprise=0
```
 	Name: Trojan:Win32/Occamy.C
 	ID: 2147726780
 	Severity: Severe
 	Category: Trojan
 	Path: file:_D:\Users\x\Downloads\POE-Trades-Companion.exe
 	Detection Origin: Local machine
 	Detection Type: FastPath
 	Detection Source: Real-Time Protection
 	Process Name: C:\Program Files\Mozilla Firefox\firefox.exe
 	Signature Version: AV: 1.273.717.0, AS: 1.273.717.0, NIS: 1.273.717.0
 	Engine Version: AM: 1.1.15100.1, NIS: 1.1.15100.1

```

**Comment by lemasato** [comment]
Related to #121 

Strange, the [virustotal](https://www.virustotal.com/#/file/87d8b2170d551e0c2960a74848942f79f67a4ceac6b918a0e63d383280a5fd46/detection) doesn't say anything about Microsoft (at least, not yet). Also no flag on a W10 OS with WinDefender up to date. WinDefender probably monitored POE Trades Companion to learn how it was working, then decided it was a threat.  

For now, if you do not wish to add Trades Companion as an exclusion but still want to use the tool: I have included a source only zip that doesn't contain the compiled executables in the latest release. You can download it here: [1.12.7 release page](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.12.7) then choose Source-only-no-exe.zip. Or [click here](https://github.com/lemasato/POE-Trades-Companion/releases/download/1.12.7/Source-only-no-exe.zip) for a direct link.

**Comment by Isolocis** [comment]
Hi, I wanted to add that the issue occurs for me too (version 1.12.5). Windows Defender has some other matches too:

[Trojan.Win32/Tiggre!plock](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fTiggre!plock&threatid=2147723626)

[Program:Win32/Unwaders.C!ml](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Program:Win32/Unwaders.C!ml)

**Comment by lemasato** [comment]
@Isolocis Based on virustotal, 1.12.5 is [flagged by Microsoft (8/66)](https://www.virustotal.com/#/file/0bd18f60121e8335356607dbb786a7beb32c2148ef9b5483c8f51fb8abaa05e1/detection)
See if 1.12.7 works for you. If not, add it as an exception or [read my post above](https://github.com/lemasato/POE-Trades-Companion/issues/122#issuecomment-410224751) to download the exe-free zip.

**Comment by lemasato** [comment]
I opened a general post for the malicious flagging.
For any talk about the issue, please post over there.
You can find it over here: #124
