### ISSUE TITLE
Some Antivirus are still detecting 1.12.7

### ISSUE THREAD

**Issue by EThaNol2005** [lemasato/POE-Trades-Companion#123]
[https://www.virustotal.com/de/file/87d8b2170d551e0c2960a74848942f79f67a4ceac6b918a0e63d383280a5fd46/analysis/1533799644/](url)

Bitdefender still blocking the app, with whitelistentry... 

btw awesome tool :)
greetings

**Comment by lemasato** [comment]
Thank you, I'm glad you like it!

Yeah the count increased, as I was expecting...
1.13.BETA_1 has been released and only has minor flags for now... we'll see in a few days.
I uploaded a different executable that doesn't contain GDIP.
If that one doesn't get flagged, then I guess I will have found the issue.

> I opened a general post for the malicious flagging.
For any talk about the issue, please post over there.
You can find it over here: #124
