### ISSUE TITLE
[PSA] Anvitirus flagging the POE Trades Companion.exe

### ISSUE THREAD

**Issue by lemasato** [lemasato/POE-Trades-Companion#124]
#121 #122 #123 

Lately, antivirus started flagging the tool as malicious.
Worry not, **these are false positives.**
I apologise. This issue really bothers me as much as anyone. Getting your tool flagged could easily mean the end of the project. While some may trust me, I can understand if someone decides to look for an alternative due to being sceptical/scared.

The flagging started appearing after [v1.12.5](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.12.5) release.
The update brought a major change to Trades Companion: Private fonts. Previously, it was required to install fonts on the user's system. This is due to the way the original ImageButton class works (necessary for the skinning system). 
I cannot revert the content of the update, as that would be really inconvenient.

Now that 1.13 first beta is out, I will be able to inspect further. What bothers me the most, is that it takes a long time before the executable is flagged on virustotal. As exemple, the 1.12.7 executable was just fine the day it was released. But nearly a week later, it was only starting to get flagged as malicious ([virustotal scan](https://www.virustotal.com/#/file/87d8b2170d551e0c2960a74848942f79f67a4ceac6b918a0e63d383280a5fd46/detection)).

I know from personal experience that some antivirus simply don't like compiled ahk scripts. On virustotal, even an empty script that has been compiled will get from 5-7 flags. This is due to the way AHK compiles script. But this time, it's beyond reasonable. Having a single executable you can move anywhere is really convenient in my opinion, and I don't really want to lose that aspect, but I will resort to using only the source if necessary.
We could contact AV companies and ask them to whitelist the tool after verifying it, but (I think?) this would be tedious as it would have to be done for every update.

For now, if you want to keep using Trades Companion, you may:
- Add the executable as an exclusion to your Antivirus.
Or even better, put Trades Companion into its own folder and add that folder as an exclusion, so that you don't have to add the exclusion again on every Trades Companion update.
- Download the source zip that doesn't contain compiled executables.
It can be found on the release page, right under the executable.

***

Tried so far:
- Not using VerPatch to change the ver num / desc / copyright. 
- Removing EnumFonts.vbs & FontReg.exe.
- Cutting unused functions from GDIP.ahk.
- Updating to AHK v1.1.30.00 ([waiting](https://www.virustotal.com/#/file/7d5ebb489d571f85fa93aab49d5ff350f67f6761799807bccec5e0748a3a12fc/detection))

**Comment by miaXcova** [comment]
Thanks for the quick reply on my previous post.  I guess I figured it was new since you just published a new version yesterday.
In lieu of trying to download the source and compiling, something most are not going to want to do, simply add POE Trades Companion.exe to the exclusion list (until this is fixed anyway):
Open Malwarebytes, click on settings and then the Exclusions tab.  Click Add Exclusion and navagate to the application location.
![image](https://user-images.githubusercontent.com/13664277/45220202-66c97380-b27b-11e8-8476-acc1fb1466f0.png)

Also might want to sticky this until it's fixed to keep people like me from opening a new thread in a panic. =)

**Comment by WhatelseBeGood** [comment]
Can you explain THIS : 

https://www.hybrid-analysis.com/sample/3fb492ba8acb581e98ad137960e0e63871d57bdd8c19552d2f4c1c13a42a648d/5b4882ad7ca3e16c2f65a0c3

> Modifies Software Policy Settings
details
"POE-Trades-Companion.exe" (Access type: "CREATE"; Path: "HKCU\SOFTWARE\POLICIES\MICROSOFT\SYSTEMCERTIFICATES\CA")
"POE-Trades-Companion.exe" (Access type: "CREATE"; Path: "HKCU\SOFTWARE\POLICIES\MICROSOFT\SYSTEMCERTIFICATES\CA\CERTIFICATES")
"POE-Trades-Companion.exe" (Access type: "CREATE"; Path: "HKCU\SOFTWARE\POLICIES\MICROSOFT\SYSTEMCERTIFICATES\CA\CRLS")
"POE-Trades-Companion.exe" (Access type: "CREATE"; Path: "HKCU\SOFTWARE\POLICIES\MICROSOFT\SYSTEMCERTIFICATES\CA\CTLS")
"POE-Trades-Companion.exe" (Access type: "CREATE"; Path: "HKLM\SOFTWARE\POLICIES\MICROSOFT\SYSTEMCERTIFICATES\CA")
"POE-Trades-Companion.exe" (Access type: "CREATE"; Path: "HKLM\SOFTWARE\POLICIES\MICROSOFT\SYSTEMCERTIFICATES\CA\CERTIFICATES")
"POE-Trades-Companion.exe" (Access type: "CREATE"; Path: "HKLM\SOFTWARE\POLICIES\MICROSOFT\SYSTEMCERTIFICATES\CA\CRLS")
"POE-Trades-Companion.exe" (Access type: "CREATE"; Path: "HKLM\SOFTWARE\POLICIES\MICROSOFT\SYSTEMCERTIFICATES\CA\CTLS")
"POE-Trades-Companion.exe" (Access type: "CREATE"; Path: "HKCU\SOFTWARE\POLICIES\MICROSOFT\SYSTEMCERTIFICATES\DISALLOWED")
"POE-Trades-Companion.exe" (Access type: "CREATE"; Path: "HKCU\SOFTWARE\POLICIES\MICROSOFT\SYSTEMCERTIFICATES\DISALLOWED\CERTIFICATES")
"POE-Trades-Companion.exe" (Access type: "CREATE"; Path: "HKCU\SOFTWARE\POLICIES\MICROSOFT\SYSTEMCERTIFICATES\DISALLOWED\CRLS")
"POE-Trades-Companion.exe" (Access type: "CREATE"; Path: "HKCU\SOFTWARE\POLICIES\MICROSOFT\SYSTEMCERTIFICATES\DISALLOWED\CTLS")
"POE-Trades-Companion.exe" (Access type: "CREATE"; Path: "HKLM\SOFTWARE\POLICIES\MICROSOFT\SYSTEMCERTIFICATES\DISALLOWED")
"POE-Trades-Companion.exe" (Access type: "CREATE"; Path: "HKLM\SOFTWARE\POLICIES\MICROSOFT\SYSTEMCERTIFICATES\DISALLOWED\CERTIFICATES")

> Modifies proxy settings
details
"POE-Trades-Companion.exe" (Access type: "DELETEVAL"; Path: "HKCU\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\INTERNET SETTINGS\ZONEMAP"; Key: "PROXYBYPASS")
"POE-Trades-Companion.exe" (Access type: "DELETEVAL"; Path: "HKLM\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\INTERNET SETTINGS\ZONEMAP"; Key: "PROXYBYPASS")

**Comment by lemasato** [comment]
@WhatelseBeGood Most likely nothing out of ordinary.
[Here are the results for AHK v1.1.30.03 setup exe using the same website.](https://www.hybrid-analysis.com/sample/9c044862a4cd488b3b69b77ab775adb43643b686b2af367a9667e936322a63a4)

Also how is your exe only 6mb when the latest BETA is 12mb and the latest stable is 10mb?
[Your link report](https://www.hybrid-analysis.com/sample/3fb492ba8acb581e98ad137960e0e63871d57bdd8c19552d2f4c1c13a42a648d) - [1.15.BETA_91](https://www.hybrid-analysis.com/sample/ef3bd0cf86d6af236300784fcbe9079131ed321156253db8cfad1ad12a5a0ccb) - [1.14.3](https://www.hybrid-analysis.com/sample/3e7bf3bfdc35d8202fb1b85f4496cfb53ff09b146c7db1049157ebf0ad38bcdd)
I assume it must be 1.12.5, which was compiled with AHK v1.1.28.02.
Sooo, [results for AHK v1.1.28.02 setup exe](https://www.hybrid-analysis.com/sample/24bc24e9193e9e9b3b20d55dbe58510e91aa3f47bd610091d67ca4b2aed25af4)

**Comment by CheeseOfTruth** [comment]
Is there any new Info on this matter?
Trade Companion still gets moved into quarantine everytime i start my PC due to Trojan:Win32/Occamy.C .

**Comment by lemasato** [comment]
Nothing that I can do, except contact each and every AV company but honestly just use the AHK zip. <https://github.com/lemasato/POE-Trades-Companion/releases>

**Comment by CheeseOfTruth** [comment]
Guess I'll do that instead.
Thanks for the Info and Link. :)

**Comment by Xeverous** [comment]
@lemasato as for someone who is working on a different tool, can you explain exactly what causes the antivirus software to erroneously flag it? You wrote it started to happen after adding private fonts feature - what (internally) have you changed then? I think it is probably flagged based on the contents of the shared library objects or symbols in the executable but knowing the bad commit could help me understand the problem better.

**Comment by lemasato** [comment]
@Xeverous It's totally unrelated in the end.
Lots of AV just don't seem to like compiled AHK scripts anymore. Usually they just flag it as "generic", "spyware", "AutoHK"... which just doesn't prove anything anyway.

TradeMacro also used to include an executable with their releases. They stopped for the same reasons.

**Comment by Xeverous** [comment]
Ok, thanks. Then I will need to do a research on my own because I do not use AHK in my project and need to compile everything.
