### ISSUE TITLE
Tradebutton Bug

### ISSUE THREAD

**Issue by EThaNol2005** [lemasato/POE-Trades-Companion#126]
Hey man, me again :)

I found another Bug, the tradebutton dosn't work for me. Nothing happen :(

EDIT:// All small buttons dosn't work

greetings

**Comment by lemasato** [comment]
Only small buttons?
I'll be inspecting.

**Comment by EThaNol2005** [comment]
Seems like. The bigger one like: "Thank you" and "Invite to Party" are working so far.

**Comment by lemasato** [comment]
Confirmed.
I'll be releasing next BETA including the fix once "Price Verify for currency.poe.trade" is done.
Thank you for reporting, again!

**Comment by EThaNol2005** [comment]
Hi, it's  me again :)

I tried now to set the bigger buttons. As example: alternative tradebutton.
Named the button "Trade" selected "send trade to buyer", once with text once without.
Nothing happend :S Not i got in the setting menu the "button but can't add one more or configure anything from the "buttonmenu"

Hope the feedback is helpful 
greetings

**Comment by lemasato** [comment]
Seems to work just fine (?)
Can you provide your Preferences.ini, so I can try it out?
Documents\lemasato\POE Trades Companion\Preferences.ini

**Comment by lemasato** [comment]
The button is disabled.
You need to click on a free slot [ + ] and re-create it.
![image](https://user-images.githubusercontent.com/14184969/44311384-bd633080-a3e6-11e8-879b-20645aeb4518.png)

**Comment by EThaNol2005** [comment]
It's really weird... I did this really often... "Create button, set action and press any button below, like push at the end" and now he saved the position. So maybe now works but, 20-30 mins ago it dosn't.
