### ISSUE TITLE
Multiinstance request

### ISSUE THREAD

**Issue by EThaNol2005** [lemasato/POE-Trades-Companion#127]
Hey,

is't possible to make start the .exe two times? So i can handle 2 windows with the same tool?
Atm i use the 1.27.7 ahk version and the beta exe

greetings

**Comment by lemasato** [comment]
Yeah.
You can use /NewInstance as parameter for 1.13
Or /NoReplace for pre 1.13 versions.

**Comment by lemasato** [comment]
Additionally, you can use the /GameFolder= (/GamePath= for older versions) , so that your shortcut automatically monitor the correct Client.txt, without asking.

Example:
First shortcut: /NewInstance /GameFolder="C:\Games\Path of Exile\"
Second shortcut: /NewInstance /GameFolder="C:\Games\Steam\SteamApps\Common\Path of Exile\"

**Comment by EThaNol2005** [comment]
Whooops 
![ss 2018-08-21 at 06 43 14](https://user-images.githubusercontent.com/6765072/44416003-19a68b80-a572-11e8-97aa-c32867c4f4c1.png)
That should not happend or?
my ink looks so: 
![ss 2018-08-21 at 06 42 28](https://user-images.githubusercontent.com/6765072/44416047-34790000-a572-11e8-8f7d-978b55b7b695.png)

I tried it with /GameFolder and without

**Comment by lemasato** [comment]
Can confirm it doesn't work.
It'll be part of the next update, coming later tonight!

**Comment by EThaNol2005** [comment]
Hey, nice fix, /NewInstance work now.
But /GameFolder or the older one Gamepath don't work.
This is my Command line for the standalone /NewInstance /GamePath="C:\Spiele\Path of Exile"

**Comment by lemasato** [comment]
Hey, fixed the /GameFolder parameter. Wasn't working due to a typo.

The /PrefsFile paramter was removed, I couldn't see any use for it.
It makes thing more complicated for no real reason.

**Comment by EThaNol2005** [comment]
I see a good reason for this parameter.
At least for 2 Monitors you can save the position for your TCwindow. 
Custom settings the 2nd instance as example only for trading/flipping, i don't need the ctrl trading feature there but in my maingame. Maybe other whispersound if i tabbed out so i know witch Window.
Or is there other possibilities to handle 2 instances?

greetings

**Comment by lemasato** [comment]
Decided to merge both /PrefsFile="" and /NewInstance into /InstanceName=""
For example, /InstanceName="Shop" will have your Preferences.ini file named `Shop_Preferences.ini"

**Comment by EThaNol2005** [comment]
Thanks man!
Love how you react to feedback :)

**Comment by lemasato** [comment]
Added the /InstanceName="example" cmd line parameter on [1.13.BETA_6](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.13.BETA_6)
