### ISSUE TITLE
Unexpected Instant whisper

### ISSUE THREAD

**Issue by Henbun** [lemasato/POE-Trades-Companion#131]
Long story short, I ran into an unexpected behavior with the CTRL-click to instant whisper function.
When I have it unchecked, PoE TC will copy and send the message regardless of whether or not CTRL is clicked or not, which is a little off putting.
When the box is checked, it only copies when CTRL is pressed.

Edit: Spelling mistake

**Comment by lemasato** [comment]
Confirmed, I'll get on it.

**Comment by lemasato** [comment]
Fix will be part of the next update, thanks for reporting!
