### ISSUE TITLE
Gui is positioned wrong, program acting fucky. 

### ISSUE THREAD

**Issue by Z0MBIE2** [lemasato/POE-Trades-Companion#132]
https://i.gyazo.com/51589834f8363fe85d57c0aaaf5db9e8.png

When I sent the party invite, it sent it to guild chat instead of a PM to him, and it was just the item name.

**Comment by lemasato** [comment]
Hey,  
Can you send your logs folder? `\Documents\lemasato\POE Trades Companion\Logs`  
Just zip it and attach it here.  

Did reloading the tool help?
Or do you get this issue constantly?

**Comment by lemasato** [comment]
Okay. Looking again closely, reloading the tool won't help.
I would really need your logs file.  
I believe this happens because of OS scaling.  Do you have your OS scaling set to more than 100%?

**Comment by lemasato** [comment]
Fixed the OS scaling issues. [1.13.2](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.13.2). Thanks for reporting!

> When I sent the party invite, it sent it to guild chat instead of a PM to him, and it was just the item name.

Also included a fix about this. I'll be closing this issue, if you encounter this behaviour again please post on #128
