### ISSUE TITLE
Grid localization does not disappear!

### ISSUE THREAD

**Issue by Morgoth92** [lemasato/POE-Trades-Companion#134]
the grid localization works fine. It's really well done. It has one single problem: we would need some kind of command to make it disappear, because it does not seem to disappear in any way for me...

**Comment by miaXcova** [comment]
Temp workaround:  tap Windows key and go back into the game.  Love this feature, btw!

**Comment by lemasato** [comment]
Fixed as of [1.13.2](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.13.2)  
Sorry for the late patch.
