### ISSUE TITLE
Cyrillic characters in hotkeys are being replaced by ??? when program reloads

### ISSUE THREAD

**Issue by miaXcova** [lemasato/POE-Trades-Companion#136]
When entering the following text into a basic hotkey:
![image](https://user-images.githubusercontent.com/13664277/44958601-82660000-aeb0-11e8-9c2b-b3413fc45202.png)

It does not function and complains that "the target of this operation is not a party member".

When exiting TC and restarting the Cyrillic characters have been replaced with question marks like so:
![image](https://user-images.githubusercontent.com/13664277/44958579-2a2efe00-aeb0-11e8-98fb-6b59fc3b95db.png)

**Comment by lemasato** [comment]
Most likely related to the file format. I'll get it fixed on next update tomorrow, thank you for reporting on both forum/github!

**Comment by lemasato** [comment]
A bit later than "tomorrow", but here it is: [1.13.2](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.13.2)  
This was indeed an issue with the Preferences.ini file format.  Thanks!
