### ISSUE TITLE
Assign mouse wheel in hotkey

### ISSUE THREAD

**Issue by DocHoncho** [lemasato/POE-Trades-Companion#138]
In the new interface there does not appear to be any way to set hotkeys for the mouse wheel.

The use case I am trying to (re)implement is Control+MouseWheel [Up/Down] to {Left}/{Right} for moving switching stash tabs.

**Comment by lemasato** [comment]
Hey.  Added something regarding this on 1.13.5.
You can now choose between AHK's regular Hotkey control or an edit box, so you can type your hotkey manually. This alternative allows to bind mouse buttons.
- Advanced hotkeys key-combination can now be typed manually.
Accessed by the new "HK Type Switch" button next to the hotkey control.
This allows some key-combinations that are not normally possible with AHK's default "Hotkey" control (such as mouse buttons).
Refer to https://autohotkey.com/docs/KeyList.htm

Thank you!
