### ISSUE TITLE
Price verification not working correctly with PoeApp whispers

### ISSUE THREAD

**Issue by DocHoncho** [lemasato/POE-Trades-Companion#139]
I've been testing out the new price verification feature, and it does not seem to be working correctly when buyer is using whisper message from PoeApp.com

I whispered myself the following, copied from PoeApp:

![image](https://user-images.githubusercontent.com/216940/44962738-5f5c4000-aef2-11e8-8ce5-d517f7500681.png)
>@buttstuffmcduff` wtb Hypnotic Creed Crimson Jewel listed for 1 Chaos Orb in Delve (stash "Shop"; left 12, top 1)

The verification comes up red, even though it seems to show the same number.

![image](https://user-images.githubusercontent.com/216940/44962698-f1b01400-aef1-11e8-9068-f05cf31c8705.png)

I tested with messages from poe.trade and the official trade tool (which are identical)
>@ButtStuffMcDuff Hi, I would like to buy your Hypnotic Creed Crimson Jewel listed for 1 chaos in Delve (stash tab "Shop"; position: left 12, top 1)

![image](https://user-images.githubusercontent.com/216940/44962787-faedb080-aef2-11e8-9262-7db2d5a1e31a.png)

It would seem that the verification is checking specifically for the string "1 chaos", while the PoeApp whisper uses "1 Chaos Orb"

**Comment by lemasato** [comment]
Fixed as of [1.13.2](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.13.2)!  
Some currency names were missing from the currency list. Thanks for reporting!

https://github.com/lemasato/POE-Trades-Companion/commit/3202ac981d0a52d6cd5a1a5eac7267c0e4b4c15b
