### ISSUE TITLE
Lots of errors since delve.  Not sure how to fix them

### ISSUE THREAD

**Issue by Jiggets** [lemasato/POE-Trades-Companion#140]
![gui](https://user-images.githubusercontent.com/42919320/44991075-a1b86800-af58-11e8-96cd-30585a612bd9.png)

![trades companion](https://user-images.githubusercontent.com/42919320/44990898-2951a700-af58-11e8-9447-3f7396c8260f.png)

[GUI_Trades] hBTN_Minimize: Specified font family is empty!
[GUI_Trades] hBTN_Maximize: Specified font family is empty!
[GUI_Trades] hBTN_TabDefault1: Specified font family is empty!
[GUI_Trades] hBTN_TabJoinedArea1: Specified font family is empty!
[GUI_Trades] hBTN_TabWhisperReceived1: Specified font family is empty!
[GUI_Trades] hBTN_TabDefault2: Specified font family is empty!
[GUI_Trades] hBTN_TabJoinedArea2: Specified font family is empty!
[GUI_Trades] hBTN_TabWhisperReceived2: Specified font family is empty!
[GUI_Trades] hBTN_TabDefault3: Specified font family is empty!
[GUI_Trades] hBTN_TabJoinedArea3: Specified font family is empty!
[GUI_Trades] hBTN_TabWhisperReceived3: Specified font family is empty!
[GUI_Trades] hBTN_TabDefault4: Specified font family is empty!
[GUI_Trades] hBTN_TabJoinedArea4: Specified font family is empty!
[GUI_Trades] hBTN_TabWhisperReceived4: Specified font family is empty!
[GUI_Trades] hBTN_TabDefault5: Specified font family is empty!
[GUI_Trades] hBTN_TabJoinedArea5: Specified font family is empty!
[GUI_Trades] hBTN_TabWhisperReceived5: Specified font family is empty!
[GUI_Trades] hBTN_TabDefault6: Specified font family is empty!
[GUI_Trades] hBTN_TabJoinedArea6: Specified font family is empty!
[GUI_Trades] hBTN_TabWhisperReceived6: Specified font family is empty!
[GUI_Trades] hBTN_TabDefault7: Specified font family is empty!
[GUI_Trades] hBTN_TabJoinedArea7: Specified font family is empty!
[GUI_Trades] hBTN_TabWhisperReceived7: Specified font family is empty!
[GUI_Trades] hBTN_TabDefault8: Specified font family is empty!
[GUI_Trades] hBTN_TabJoinedArea8: Specified font family is empty!
[GUI_Trades] hBTN_TabWhisperReceived8: Specified font family is empty!
[GUI_Trades] hBTN_TabDefault9: Specified font family is empty!
[GUI_Trades] hBTN_TabJoinedArea9: Specified font family is empty!
[GUI_Trades] hBTN_TabWhisperReceived9: Specified font family is empty!
[GUI_Trades] hBTN_TabDefault10: Specified font family is empty!
[GUI_Trades] hBTN_TabJoinedArea10: Specified font family is empty!
[GUI_Trades] hBTN_TabWhisperReceived10: Specified font family is

**Comment by miaXcova** [comment]
Try reinstalling Fontin Smallcaps font from a reliable source ([google search Fontin Smallcaps](https://www.google.com/search?q=Fontin+SmallCaps)).  You will have to first delete the font then reinstall.  If you are nervous about it, copy the font in `C:\Windows\fonts` to a temp directory first.  When re-installation of the font is complete, reboot the computer.

It also wouldn't hurt to delete Trades Companion and extract a fresh new copy.  Could have been something got corrupt if you have been using the same distribution for several leagues/versions.

**Comment by Jiggets** [comment]
Thank you for that I was able to fix the font errors but my interface looks like this:
![gui](https://user-images.githubusercontent.com/42919320/45007620-3c9a5c00-afc4-11e8-9fdf-bb012c38316e.png)

**Comment by Jiggets** [comment]
Thank you for your help.  This has only happened since the delve update.  Not sure why Im not seeing all of the buttons.  The errors have all been fixed.  When I decrease the font size the larger buttons at the bottom start to be visible.  Im just not sure why this is a new issue or what changed.

**Comment by lemasato** [comment]
@miaXcova Thanks for bringing support.

@Jiggets 
>Not sure why Im not seeing all of the buttons

This is an issue related to scaling. #132 
Since the font issue has been solved, I'll be closing this.  
Thank you!
