### ISSUE TITLE
Issues with dual monitors

### ISSUE THREAD

**Issue by JashinFanatic** [lemasato/POE-Trades-Companion#141]
My screen configuration is a bit out there, but I'm having problems I have to blame on that.

Here's a picture of how I see the trade companion interface
![image](https://user-images.githubusercontent.com/17314048/44996403-136bd280-afa8-11e8-8cdb-5e57c44bb4df.png)

The highlight doesn't work correctly either, since I'm guessing the resolution isn't captured correctly there either.

My main screen (where I play) is 3200x1800 and I'm playing on 1:1 windowed FS. My second monitor (smaller) is 1360x768

**Comment by lemasato** [comment]
Hey,
This is an issue related to Windows Scaling. #132 
I'll be working on fixing issues today. Thanks for reporting!

Though I can see that the font colour is off. And that the minimize button does not have its own skin.  
Did you use to have this issue before? If not, I would recommend resetting your settings, from the Settings menu.

**Comment by lemasato** [comment]
The OS Scaling thing is fixed as of [1.13.2](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.13.2).
About the font colours / button not skinned, it's most likely related to your skin preset.
I would recommend setting it back to "Path of Exile" to get the default settings.

**Comment by JashinFanatic** [comment]
Had to change the settings again since it picked up "User defined" after I changed them to "Path of Exile". After updating, restarting and resetting the GUI settings it seems to work much better.

As discussed on Discord, I'm uploading the log I got.
[2018-09-07 18h32m30s.txt](https://github.com/lemasato/POE-Trades-Companion/files/2361814/2018-09-07.18h32m30s.txt)

**Comment by lemasato** [comment]
Hey,
I think this can now be closed.
The OS scaling issues have been fixed, and in case the skin settings are messed up they will be automatically fixed by the tool on next reload. [1.13.3](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.13.3)
> - Default values for skin settings have been added.
This will prevent from being forced to reset your settings when your "User Defined" skin settings are incorrect.

Thanks for the reports!
