### ISSUE TITLE
Unknown currency name: "alch"

### ISSUE THREAD

**Issue by rushtothesun** [lemasato/POE-Trades-Companion#145]
pathofexile.com/trade  uses "alch"

**Comment by lemasato** [comment]
Thank you for reporting!

**Comment by lemasato** [comment]
Added GGG official trading website currency names as of [1.13.4](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.13.4).  
Thank you for reporting, and sticking around so long!

**Comment by rushtothesun** [comment]
> 
> 
> Added GGG official trading website currency names as of [1.13.4](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.13.4).
> Thank you for reporting, and sticking around so long!

Thanks for creating an amazing program
