### ISSUE TITLE
Add price check hotkey

### ISSUE THREAD

**Issue by MarkHC** [lemasato/POE-Trades-Companion#148]
I think having a hotkey to price check an item on poe.trade would be useful. Maybe open the browser window with the item search on the website or something like that.

Personally I hate having to run tools such as POE-Trade-Macro alongside Trade Companion (I just hate running AHK scripts altogether).

I'd be happy to implement such a feature and submit a pull request if it is wanted.

Cheers

**Comment by lemasato** [comment]
Sorry but that's not something I would like to see.  
POE Trades Companion is meant to be centred around "making trading easier".  
In my opinion, it's best to use different tools for different uses.

**Comment by MarkHC** [comment]
Fair enough.

Thank you.
