### ISSUE TITLE
I can't even download the exe, chrome and windows consider it a virus and remove it right away without any options

### ISSUE THREAD

**Issue by Mathias-seemyapps** [lemasato/POE-Trades-Companion#149]

**Comment by Aerinx** [comment]
Bitdefender deletes it too. Detected as trojan (Trojan.GenericKD.31191528) Autohotkey code works.

**Comment by lemasato** [comment]
I would recommend downloading "Source-only-no-exe.zip" from the release page.
It should work the same, and can now also autoupdate itself.
See #124

**Comment by Mathias-seemyapps** [comment]
yea that what I did, the exe is just really misleading for new user, I will suggest removing it completely.
