### ISSUE TITLE
[FAQ] Trades GUI disappears after clicking a button.

### ISSUE THREAD

**Issue by lemasato** [lemasato/POE-Trades-Companion#15]
- Buttons will make the GUI disappears most of the time.
- Receiving a new trade whisper will make it re-appear.
- Buttons will randomly close the current tab.
- The Clipboard Button works as expected.

**Reports:**
- [DjNanos - Forums](https://www.pathofexile.com/forum/view-thread/1755148/page/5#p14137097)  
- [Petusillos- Forums](https://www.pathofexile.com/forum/view-thread/1755148/page/6#p14163116)  
- [psyclown - Forums](https://www.pathofexile.com/forum/view-thread/1755148/page/7#p14201603)

**State:**
- Could not replicate the issue.  Inspecting with DJNanos.  
- Petusillos fixed the issue by running Windows Update.
- 26feb: psyclown fixed the issue by running Windows Update.
- 14mar: More users reporting that running Windows Update fixes the issue.
- I have done some testings on a clean (no updates) W7 installation, could not reproduce the issue.
- Thanks to the help of DjNanos, we now know that the update that fixes this behaviour is among these: KB3020369, KB3021910, KB3172605, KB3212642, KB3212646.

**Comment by lemasato** [comment]
This issue definitely seems to be related to a Windows Update.  
[A Q/A has been added to the WIKI considering the issue](https://github.com/lemasato/POE-Trades-Helper/wiki/FAQ#im-having-an-issue-where-the-gui-disappears-randomly-after-clicking-a-button)

**Comment by 4rg0n** [comment]
I also have this problem. If you need any information from me, just ask =)

**Comment by lemasato** [comment]
Well. The issue does not occur on a fresh W7/W10 install.  
It could be an update that's causing the issue, which is then fixed by another update.  

Do you use a laptop? Or maybe a pre-installed OS?

**Comment by 4rg0n** [comment]
I use a desktop pc with self installed OS.
Here's my [DxDiag](https://gist.github.com/4rg0n/09eb1dc18a2821174e0c829357ff0d30).

I'll try to run the script with piping stderr to a file as described [here](https://autohotkey.com/docs/commands/_ErrorStdOut.htm). 
Maybe there are some hidden errors thrown.

**Comment by 4rg0n** [comment]
Strange behavior so far...

I made a shortcut to "POE Trades Companion.exe":

    "POE Trades Companion.exe" /ErrorStdOut

After executing the shortcut, "POE Trades Companion.exe" disappeared from file system. 
Trying to copy another "POE Trades Companion.exe" to the same location. Windows tells me I dont have the rights to do so. I can't find a running process either. My guess is my antivirus "Avast". But not confirmed...

Second method I tried running "POE Trades Companion.ahk" via a windows cmd:

   "C:\Program Files\AutoHotkey\AutoHotkey.exe" /ErrorStdOut "POE Trades Companion.ahk" 2>"error.log"

Script starts and is running. No errors so far...

Documentation says ErrorStdOut is used for syntax errors. So runtime errors doesn't appear here? 
@lemasato Can you confirm that?

**Comment by lemasato** [comment]
ErrorStdOut only tells you about errors that prevent from running the script, or an unexpected usage of a command: Instead of showing up a message box, it will log the error into a file.  
So yeah, it won't help here.
