### ISSUE TITLE
Stats Screen Issues

### ISSUE THREAD

**Issue by Sindusk** [lemasato/POE-Trades-Companion#152]
When clicking on "My Stats" it does nothing for a few seconds. Afterwards, my computers disk usage spikes to ~75% and remains there for about a minute. Afterwards, the stats screen page finally loads. When I try scrolling down, it crashes.

I have thousands of trades this league so I assume that it's just the fact that there's so many trades to parse.

**Comment by lemasato** [comment]
Sadly won't be able to inspect this for a while.  
I'll see what I can do once I get back.  

In the meantime, you can always reset your stats by deleting or renaming the file here:  
`\Documents\lemasato\POE Trades Companion\Trades_History.ini`

**Comment by lemasato** [comment]
Closing this in favour of #196
