### ISSUE TITLE
No pushbullet notification for whispers

### ISSUE THREAD

**Issue by Rufus66** [lemasato/POE-Trades-Companion#153]
The pushbullet notification for trading whisper works both with the afk setting on or off.
The @ setting for any whisper doesn't send any pushbullet notification regardless if the afk setting is on or off, and if I am afk or not in game.

**Comment by lemasato** [comment]
Fixed as of [1.13.3](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.13.3)
Thanks for reporting!

**Comment by Rufus66** [comment]
Thanks! Nice to see a dev with quick fixes
