### ISSUE TITLE
Program not PMing the buyers properly. 

### ISSUE THREAD

**Issue by Z0MBIE2** [lemasato/POE-Trades-Companion#154]
So I have the problem of the program sometimes not PM'ing people properly, which is a few things. Sometimes it works, sometimes it just sends a PM by using the copied item name [seen here](https://i.imgur.com/EOQjzYj.png), or sometimes it'll just not send anything to them, but it will still invite them and it'll put a @ mark in my chat for a whisper. In the latter case, it didn't even send a PM when I thanked them for the trade, [just nothing.](https://i.imgur.com/wT3HuyH.png) I haven't edited the trade buttons at all except their location. 

Wondering if I should also make a new issue post addressing the fact the program is always minimized by default when I get a PM, even when focused on the game, so it never gets auto-maximized. The other issue about this is a suggestion about it when it isn't focused.

**Comment by lemasato** [comment]
Related to #128 

> the program is always minimized by default when I get a PM, even when focused on the game, so it never gets auto-maximized

Do you have the "Auto maximize on first new tab creation" setting enabled?

Apparently, there was an issue where the GUI wouldn't min/max itself while having "Hide the interface when not in game" enabled and being tabbed out of the game, which will be fixed next release.
