### ISSUE TITLE
Malwarebytes triggered after latest update

### ISSUE THREAD

**Issue by miaXcova** [lemasato/POE-Trades-Companion#155]
Please say it ain't so:
![image](https://user-images.githubusercontent.com/13664277/45219559-4d272c80-b279-11e8-8e87-09e4c931d3f6.png)

Has to be something with the latest update where you fixed the file type or something when Cyrillic characters weren't saving in hotkey text.

**Comment by lemasato** [comment]
It has been like this ever since 1.12.7, see #124 
I'd recommend using the source version, it works the same.

https://github.com/lemasato/POE-Trades-Companion/releases
Source-only-no-exe.zip
