### ISSUE TITLE
ups

### ISSUE THREAD

**Issue by EThaNol2005** [lemasato/POE-Trades-Companion#158]
![ss 2018-09-12 at 05 55 45](https://user-images.githubusercontent.com/6765072/45437503-33d91280-b6b5-11e8-85c1-8cb5f3e6841f.png)

**Comment by lemasato** [comment]
Yeah logs file is too big.
I had it fixed before pushing the update but I guess it was still too big or I didn't push the right exe.
Thankfully, it's only a minor issue that doesn't change anything, so it's fine for now.

**Comment by lemasato** [comment]
This bug was only affecting the AHK version.
New version released, this issue is now gone!
Thank you.
