### ISSUE TITLE
Hotkeys not working

### ISSUE THREAD

**Issue by albinolonewolf** [lemasato/POE-Trades-Companion#160]
The hotkeys like Alt + 1 etc wont work for me :/

**Comment by lemasato** [comment]
Sorry, can't check or do testings for now. It'll have to wait for the 27 :/

But if it's a basic hotkey, make sure to have the box toggled on.
Could you post your logs file, so I can make sure settings are correct?

Documents/lemasato/poe trades companion/logs

**Comment by lemasato** [comment]
Should be fixed as of the latest update. 1.13.5  
Thank you for reporting!
