### ISSUE TITLE
New Variable %sentWhisper%

### ISSUE THREAD

**Issue by ProstheticAIM** [lemasato/POE-Trades-Companion#161]
Can you possible make a Variable for the last whisper I sent instead last received

**Comment by lemasato** [comment]
Sure, could be nice I guess. Will get on that once I get back!

**Comment by lemasato** [comment]
Added on 1.13.5.
Thanks for the suggestion!
- Added a new variable to send a message to the last person you whispered: %sentWhisper% / %lastWhisperSent% / %lws%
Also added two alternative to %lastWhisper% (used to whisper the last person who whispered you): %lastWhisperReceived% / %lwr%
