### ISSUE TITLE
Scaling issues

### ISSUE THREAD

**Issue by Lithorta** [lemasato/POE-Trades-Companion#163]
Hello, 

As you can see, I have a little problem with my overlay. Every skin and every scaling size have been tested, same result. Have the last update too.
![sans titre](https://user-images.githubusercontent.com/43555111/45979762-59b8cc80-c050-11e8-8dc5-3d8c4609cd3e.png)

**Comment by lemasato** [comment]
Probably due to OS scaling. Will have to check on that and get it fixed.

**Comment by lemasato** [comment]
Does this still happen?
If so: 
- What OS are you using?
- Do you have windows' built in scaling setting set to other than 100%?
- Are you using multiple monitors, and do they have different resolution?
- Please provide your logs file from /MyDocuments/lemasato/POE Trades Companion/logs
Just zip the folder and send it here

**Comment by h4xolotl** [comment]
I have the same problem. Windows 10, scaling is at 125%

It works fine on an 100% external monitor
[Logs.zip](https://github.com/lemasato/POE-Trades-Companion/files/2693970/Logs.zip)

**Comment by lemasato** [comment]
@h4xolotl Do you have multiple monitors?
Which resolution are they running on?
Do you have the scaling setting set for a monitor, but not for others?

Logs are saying the scaling is set to 1 (100%).

**Comment by lemasato** [comment]
Think I could pinpoint the issue.  
Seems to be related to Windows 10's fix against [blurry apps](https://www.tenforums.com/attachments/tutorials/168978d1513802753-turn-off-fix-scaling-apps-blurry-windows-10-a-fix_scaling_for_apps-2.png).
I'll see what I can do on it.
