### ISSUE TITLE
Buyer joined area no longer playing sound

### ISSUE THREAD

**Issue by ReflexivR** [lemasato/POE-Trades-Companion#166]
Hi, sound no longer plays when a buyer enters my hideout. As I recall it used to work a few versions ago. I tried re-installing by moving POE Trades Companion directory in \My Documents\lemasato and re-setup as new. Is this a known issue or is there something I can try? Btw, thanks so much for your awesome tool!

**Comment by lemasato** [comment]
The line to play the sound was missing.  
This is due to an error on my end when rewriting the code with 1.13.  
Thank you for reporting!

**Comment by ReflexivR** [comment]
Added the changed lines to the AHK version I have. It's working great now thank you!
