### ISSUE TITLE
Vivaldi Browser Support

### ISSUE THREAD

**Issue by EThaNol2005** [lemasato/POE-Trades-Companion#169]
Heyho,
can you please add vivaldi Browser to the clipboard detection list?

greetings

**Comment by lemasato** [comment]
What do you mean?  
This feature doesn't need browser compatibility.  
It works based on clipboard change. If the copied pattern matches a whisper pattern (while holding CTRL) the whisper will automatically be sent to the last activated game instance window upon releasing CTRL.

**Comment by lemasato** [comment]
Is it working now though?  

Also, translated whispers are not detected by the "Instant Whisper" functionality yet.  
This will be part of the next update ([commit](https://github.com/lemasato/POE-Trades-Companion/commit/1e6b01e1cf8033f3aabc04e4baef01e97fd9ba22))
