### ISSUE TITLE
Trojan detected while updating - Occamy.C

### ISSUE THREAD

**Issue by planet37** [lemasato/POE-Trades-Companion#170]
.....AppData\Local\Microsoft\Windows\INetCache\IE\MN71A71G\POE-Trades-Companion[1].exe

Windows defender is picking this up. 
Assuming it's not the Occamy Trojan .. i can't think of any reason why your code would contain anything resembling this. I would expect something like this from avast or webroot .. defender not so much.

**Comment by planet37** [comment]
please remove this. i didnt see the post below.

**Comment by lemasato** [comment]
Would recommend to use the AHK version instead.  
https://github.com/lemasato/POE-Trades-Companion#usage  

I think it would be best to completely get rid of the executable version in the future.
