### ISSUE TITLE
TC does not support function keys F16 - F19

### ISSUE THREAD

**Issue by niklaas-0rbit** [lemasato/POE-Trades-Companion#171]
Wanted to use the button 'F19' to map as shortcut for /hideout, but TC does not recognize the key.

**Comment by lemasato** [comment]
Have you tried switching to a manual hotkey?  
Click on "HK Type Switch" from the Hotkeys Advanced tab
![image](https://user-images.githubusercontent.com/14184969/48018690-c7691580-e131-11e8-9584-0af93f2e1792.png)

**Comment by niklaas-0rbit** [comment]
yeah, just tried it out, that also does not work for me:
![poe-trades-companion_2018-11-05_19-57-36](https://user-images.githubusercontent.com/32305876/48019986-16fd1080-e135-11e8-86a5-9643e118d435.png)

I tried the same entry with F3 instead of F19, that worked as intended.

**Comment by lemasato** [comment]
How about this simple script?  

```
#SingleInstance Force

F19::SendInput /hideout
```

Save it as .ahk and run.

**Comment by niklaas-0rbit** [comment]
Nope, get a kind of weird behaviour when doing that, it actually opens the World Screen & Inventory when pressing F19, and open/closes the Inventory when I push F19 repeatedly. I get this output on the script from AHK:

---- C:\Users\niklaas\Documents\test.ahk
003: Return (13.23)
003: SendInput,/hideout (0.01)
003: Return (83.50)
003: SendInput,/hideout
003: Return (0.80)
003: SendInput,/hideout (0.02)
003: Return (0.38)
003: SendInput,/hideout
003: Return (0.41)
003: SendInput,/hideout (0.02)
003: Return (0.33)
003: SendInput,/hideout
003: Return (0.16)
003: SendInput,/hideout
003: Return (14.78)

**Comment by lemasato** [comment]
You are forgetting to open the chat and sending the message, using Enter.  
It should be like this: `SendInput, {Enter}/hideout{Enter}`  

If the test.ahk F19 macro works, then it should also work on TC.

**Comment by niklaas-0rbit** [comment]
Oh, haven't realized that missing part either... I Used that now:
`#SingleInstance Force

F19::SendInput {Enter}/hideout{Enter}`

Anyway, can't get it running in TC, no matter if I choose the SendEvent method with {Enter}/hideout{Enter} or the pre-made /hideout command.

**Comment by lemasato** [comment]
It's working great for me, with a Logitech mouse with F19 bound to one of the buttons
Can you provide your most recent logs file?
`Documents/lemasato/POE Trades Companion/Logs`
Just zip and attach the folder

**Comment by niklaas-0rbit** [comment]
Sure, hope it helps.
[TC-Logs.zip](https://github.com/lemasato/POE-Trades-Companion/files/2550939/TC-Logs.zip)

**Comment by lemasato** [comment]
Got it.  
Delete the "Kick myself out of party + hideout" hotkey, and it'll be working.  

Apparently, there is some bug preventing to process all advanced hotkeys if one of them is not set.  
I'll have to inspect that.

**Comment by niklaas-0rbit** [comment]
Sorry for the late response, got sick. Yeah after deleting the  "Kick myself out of party + hideout" hotkey I created a new profile with the /hideout command and F19 hotkey. Works as intended now. Thanks for looking into it!
