### ISSUE TITLE
How to add commands to new buttons?

### ISSUE THREAD

**Issue by rhazor** [lemasato/POE-Trades-Companion#172]
I'm a dumbo, I don't get it, select the button, select the command and how do you add it to the list?

![asdf](https://user-images.githubusercontent.com/22996586/48258327-7bfa8400-e41d-11e8-9e47-c94dd6f369c0.gif)

**Comment by lemasato** [comment]
Normally, clicking on "Push at the end" should do the job,; which doesn't seem to work here.  
Regardless, this interface will be updated to make adding actions more intuitive.  

<details>
    <summary>Customization Buttons tab
    <br>Click to expand the picture.</summary>
        <img src="https://user-images.githubusercontent.com/14184969/48265969-46aa6200-e42e-11e8-92c4-eaf25e0c104a.png">
</details>  
&nbsp;  

1. Did you try reloading the app and then try adding your actions?  
Could be that it bugs out after a while.
1. If the previous did not work, can you test the new version? 
[POE-Trades-Companion-master.zip](https://github.com/lemasato/POE-Trades-Companion/files/2566084/POE-Trades-Companion-master.zip)

**Comment by rhazor** [comment]
So I tried your link, it had my buttons, so it shared same settings? Anyway, it worked. Then I launched my old version and it already had the action added and I was able of adding the rest of actions.

So... Fixed?
