### ISSUE TITLE
Feature Request: Variables from Stats

### ISSUE THREAD

**Issue by livejamie** [lemasato/POE-Trades-Companion#173]
I think it would be fun to have access to variables related to your stats.

I would like my thank you message to be something like:
"Thank you for being my 305th trade this league. Stay safe exile!"

Ideas:
%leagueTradeNumberOverall% - Amount of trades total for current league
%leagueTradeNumberDaily% - Amount of trades for league total for that day
%tradeNumberOverall% - Amount of trades made for all leagues

Might be fun to even have access to the amount of currency you've made that day possibly?
%leagueAmountMadeOverall% - Amount of currency made overall
%leagueAmountMadeDaily% - Amount of currency made that day

Open to other fun ideas.

**Comment by livejamie** [comment]
Does this seem doable? Would be nice to have for next league if possible.

**Comment by lemasato** [comment]
Doable for sure. But not sure if that'd be any useful.  
Feels like it would be the kind of feature that only a handful of people would use.  

It could be great to know how many trades you'd do since you launched the tool, daily, weekly, etc, but the buyer wouldn't care much about it.

**Comment by fladson** [comment]
This is a great idea.
Would love to see some stats like that.

**Comment by lemasato** [comment]
Tbh I think a revamp of the My Stats interface would be better.
I don't think anyone would care to know that you made this much today, or that you did this many trade this league. And on top of that, it's kind of bad to give numbers to your customers.

Improving the My Stats interface with total currency made daily, weekly and per-league would be nice. Also maybe some kind of graph, to compare how much you made per day or per week, if that's even possible.

**Comment by livejamie** [comment]
I like the idea of saying how many trades I've done in my "thank you" whisper, I wouldn't do the price thing myself. It would be good to know for myself, though.
