### ISSUE TITLE
Multiple errors on startup

### ISSUE THREAD

**Issue by Pat1487** [lemasato/POE-Trades-Companion#174]
I extracted the folder in the AHK zip to the same place where I put my trademacro folder. When starting POE Trades Companion.ahk I get several errors listed below in the order that they appear.

An error box:
>FileInstall_CMDs.ahk
>You cannot run this file manually!

A second error box (I edited out my user name but it is the correct name):
>POE Trades Companion - Error log
>
>Section: SETTINGS_MAIN
Key: TradingWhisperSFXPath
Value: C:\Users\MYUSERNAME\Documents\lemasato\POE Trades Companion\SFX\WW_MainMenu_Letter.wav
Default value: C:\Users\MYUSERNAME\Documents\lemasato\POE Trades Companion\SFX\WW_MainMenu_Letter.wav
>
>Section: SETTINGS_CUSTOMIZATION_SKINS
Key: Font
Value: Fontin SmallCaps
Default value: Fontin SmallCaps
>
>Section: SETTINGS_CUSTOMIZATION_SKINS
Key: Preset
Value: Path of Exile
Default value: Path of Exile
>
>Section: SETTINGS_CUSTOMIZATION_SKINS
Key: Skin
Value: Path of Exile
Default value: Path of Exile
>
>Section: SETTINGS_CUSTOMIZATION_SKINS_UserDefined
Key: Font
Value: Fontin SmallCaps
Default value: Fontin SmallCaps
>
>Section: SETTINGS_CUSTOMIZATION_SKINS_UserDefined
Key: Preset
Value: Path of Exile
Default value: Path of Exile
>
>Section: SETTINGS_CUSTOMIZATION_SKINS_UserDefined
Key: Skin
Value: Path of Exile
Default value: Path of Exile

A 3rd error box (I shortened the url but it should be the correct url):
>POE Trade Companion.ahk
>
>Exception thrown (download)!
>
>Error while downloading <github page/releases?page=1> using UrlDownloadToFile (cURL_DownloadFallback).

A 4th error box (I have the most recent version 1.13.6):
>POE Trades Companion - Updating Error
>
>There was an issure when retrieving the latest relese from GitHub API....
> Press [ Space } to close this window

And finally a 5th error box:

![image](https://user-images.githubusercontent.com/33697671/49690612-df9dcd00-fb01-11e8-9ac2-563eeb2bf4f1.png)

The tool then starts but is extremely buggy and basically unusable.

* I've tried running the tool on my C: drive just in case that was a problem but these errors still occur .
* AHK is installed properly, I use PoE Trade Macro all the time without any issues.
* I can't run the exe because Windows Defender detects and deletes it (I know its a false positive but I'd rather use the AHK script anyway)
* The folders that the tool creates in my documents folder are empty.
* Running the tool as an admin doesn't change anything.
* I closed all other AHK scripts just to be sure and it still gives me these errors.

**EDIT:**

I manually copied everything in the resources folder to the Documents\lemasato\POE Trades Companion folder (i put the images in the "imgs" folder into the "Images" folder) which gets the tool working to a usable state with only 3 errors on start up, the first one about running FileInstall_Cmds.ahk manually (which I've never done) and the 2 update error ones.

**Comment by lemasato** [comment]
Make sure to run the tool in its own folder.  
Merging it with TradeMacro could lead to issues as some files would be overwritten.  

Could you provide your logs?  
/Documents/lemasato/POE Trades Companion/Logs  
(Zip the folder)

**Comment by Pat1487** [comment]
It is in its own folder, sorry, I meant I put both folders for both tools in the same folder, that folder is on a different harddrive from poe though so I thought that might be an issue which is why i mentioned putting them in the same place. I didn't do anything weird like merge all the files into 1 folder lol.

Heres the logs
[Logs.zip](https://github.com/lemasato/POE-Trades-Companion/files/2661819/Logs.zip)
I used notepad++ to find in files and replace my user name with MYUSERNAME but the name is correct

The first 8 logs (15h17m27s - 15h39m39s) are me trying to get it working for about 20 minutes before giving up and making this post

The 9th log (16h11m24s) is right after I made this post just to be sure it didn't start working the moment I said something about it

I decided to keep trying after a 5-10 min break so the next 3 logs (16h23m57s - 16h42m09s) are after I manually copied the resource files into the correct place in my documents folder which is when it started working and I started configuring it (I tried to turn off updates since that still doesn't work and would reduce the start up errors by 2, but the setting won't save, so I manually tried changing the ini file but I don't know the name of the settings, I should've tried 'Never')

The last log (12-09 14h55m53s) is from today when I was using it (I didn't get any trade requests though so I still don't know if its working properly or not but it does run and I can change the hotkeys without any issues)

**Comment by Amnexty** [comment]
Bump
Still no idea on how to fix it properly ? Cannot run POETC oO

**Comment by Amnexty** [comment]
Downloading the .exe version worked it out, but now I get a new problem: "No game instance chosen" ( https://puu.sh/CmSiX/57f4c2925a.png )
If I left-click my PoE isntance on the Windows taskbar, then hit continue, it does nothing, any tip ? :(

**Comment by lemasato** [comment]
Looks like something is preventing the tool from extracting assets.  
Not really sure what could be the cause. Make sure that nothing is interfering with the tool.

@Amnexty You need to click on the POE icon as shown here:
![image](https://user-images.githubusercontent.com/14184969/50796007-7069f300-12d0-11e9-9197-2c60fd281d88.png)

**Comment by Amnexty** [comment]
Seems like I was indeed, misunderstood something I read somewhere.
But still, after selecting the instance of PoE you highlighted, the buttons don't work. I receive notifications, sound, POETC shows the list of trades occuring, but can't do shit with buttons :/

Any idea ?

**Comment by lemasato** [comment]
Make sure to be running the tool as admin.  
Steam is automatically running your games as admin. And if the tool is not elevated on the same level, it won't be able to interact with the game window.

**Comment by Amnexty** [comment]
That was is, clicking on the right icon... *dumbface fading*
... and running it as Admin solved the last trouble I encountered.

Thank you very much lemasato!
