### ISSUE TITLE
Noob Friendly?

### ISSUE THREAD

**Issue by MariChally** [lemasato/POE-Trades-Companion#175]
I didn't even know what title to give this since I honestly have no idea what the problem is. I just thought this tool might be helpful to get a bit more professionally trading in PoE. Downloaded the .exe, ran the .exe, had a message in the lower right corner telling me everything is good, then had a window pop up very transparent in the upper left corner. While I was in my browser.
Went into PoE to see if it worked, only have a very transparent bar at the top that does nothing when I click on it no matter where and how and why. What is the "tray icon" I'm supposed to click on? That is the only thing that is there. And it doesn't do anything but look ugly. And it doesn't have anything to do with PoE, doesn't change at all when I start / re-start the game, it's simply always there. 
I then decided to uninstall this shit, guess what there are no instructions on how to do so. no menu to close the program from, and I can't delete the files because they are in use. Now I have a weird transparent bar blocking my tabs in my browser and I'm hoping a restart will fix it. Doesn't even show up in the task manager this thing. I get that I probably made some major mistake installing it but come on. Have you ever heard the term "user-friendly"?

**Comment by lemasato** [comment]
Hi,  

> Downloaded the .exe, ran the .exe, had a message in the lower right corner telling me everything is good, then had a window pop up very transparent in the upper left corner. While I was in my browser.

I would recommend downloading and using the AHK source as indicated on the releases page as the executable is known for getting flagged.  

> then had a window pop up very transparent in the upper left corner. While I was in my browser.

> Went into PoE to see if it worked, only have a very transparent bar at the top that does nothing when I click on it no matter where and how and why

On default settings, the interface is made to appear at all times.  
When no trades are open, the interface will be made transparent and click-through not to annoy the user.  
Such behaviour can be changed by accessing the Settings from the tray menu.  

> What is the "tray icon" I'm supposed to click on? 

The tray icon can be seen in the tray menu.  
The tray menu is that space on the bottom right of your screen that contains icons of the currently running programs (Windows Defender, Steam, Discord, etc...).  

> That is the only thing that is there. And it doesn't do anything but look ugly. And it doesn't have anything to do with PoE, doesn't change at all when I start / re-start the game, it's simply always there.

This is the interface header.  
When minimized, it appears as such. As explained above, it appears at all time on default settings. Though, you can also decide to completely hide it when no trades are open.  

At the moment, three skins are available as seen on the [project's main page](https://github.com/lemasato/POE-Trades-Companion#skins). More are to come for sure, in the future.  

> I then decided to uninstall this shit, guess what there are no instructions on how to do so. no menu to close the program from, and I can't delete the files because they are in use

This tool doesn't need to be installed. Only required assets are extracted on launch-time.  
Local settings are stored in /Documents/lemasato/POE Trades Companion/ as explained in the [Wiki](https://github.com/lemasato/POE-Trades-Companion/wiki/FAQ#where-does-the-tool-store-its-settings).  

> Now I have a weird transparent bar blocking my tabs in my browser and I'm hoping a restart will fix it. 

The interface is made click-through and transparent by default.  
Restarting will not launch the tool again as it doesn't set itself to auto-run on start.  

> Doesn't even show up in the task manager this thing

If using the executable, it will appear as "POE Trades Companion.exe". You can end the process without any risk. If using the ahk, it will appear as "AutoHotKey.exe" as it does with any other uncompiled AHK script.  

> I get that I probably made some major mistake installing it but come on

This tool doesn't install itself but only extract required assets at launch-time.  
You can stop using it at any time, and if the existence of such assets are bothering you, you can delete the local folder as explained above without any risk in case you decide to use it again later.  

> Have you ever heard the term "user-friendly"?

I have created this tool with the ideas of "Customization" and "User-Friendly".  
Regular users can use the tool as-is, without bothering and those who want can customize it to their liking. The 1.13 update especially made the Settings menu even clearer and made setting up buttons / hotkeys much easier.  

If you have any suggestion, I'll be considering them.  
Until then, happy trading!
