### ISSUE TITLE
Trades not detected since update to betrayal

### ISSUE THREAD

**Issue by Jihtsofox** [lemasato/POE-Trades-Companion#176]
Before the update to betrayal I used the steam version, but noticed the file size, so I uninstalled and installed the stand alone POE to my SSD main C drive, I went though and there is no client.txt file anywhere but the new install file. I've gone through all the fixes in previous issues and nothing is working, I also have this issue with mercury trade and it worked before as well. I've tried previous versions, running as admin, deleting the log files of both trade companion and POE...not sure what to do next as this is an amazing program and helps so much. Any suggestions would be greatly appreciated, thanks.

**Comment by Jihtsofox** [comment]
[logs2018-12-09 08h42m08s.zip](https://github.com/lemasato/POE-Trades-Companion/files/2660588/logs2018-12-09.08h42m08s.zip)
Here is the log file if it helps.

**Comment by Jihtsofox** [comment]
Somehow I fixed it...but thanks

**Comment by lemasato** [comment]
Was about to ask if it was still happening.  
It was mostly due to the Trades API being unavailable at the time.  
When such a behaviour occurs, the script retrieve the leagues from a text file on GitHub instead, but I hadn't updated it yet.
