### ISSUE TITLE
Green item box doesnt show which tab

### ISSUE THREAD

**Issue by Weisshuf** [lemasato/POE-Trades-Companion#177]
The green box doesnt show in which stash tab the item is. Especially for Maps it is annoying because i have them in my map stash.

Also, when I copy the item onto my clipboard, it copies the tier like "X map tier:2" and because of that, i cant search that in my search bar because it doesnt highlight.

**Comment by lemasato** [comment]
The Item Grid can show three different locations.  
The big green square is for normal stash tabs.  
The smaller green square is for quad stash tabs.  

And if the item is detected to be a map, it will show a third blue square.
This blue square will show the location of the map in a map stash tab.  

Additionally, you can see the tab name on the top left of your stash.

**Comment by LordPalpatine** [comment]
The problem is, when i set an exact price to the whole tier, i do not get the name of the map-tab.

**Comment by lemasato** [comment]
https://github.com/lemasato/POE-Trades-Companion/issues/194

> 
> 
> Feature will be part of next update.
> Keep in mind showing map case only work with non-shaped non-elder maps. As explained above, those maps are added on the tier at the end of the list, and we have no way of knowing which maps the player decided to upgrade.
> 
> Also, this can only work with english whispers.
> Some translated whispers have parts of their map name translated, and I couldn't find any list with their corresponding english name.
> 
> ![image](https://user-images.githubusercontent.com/14184969/53337035-7c515900-3900-11e9-876a-63cde3e883c0.png)
