### ISSUE TITLE
Buttons/Hotkeys not working

### ISSUE THREAD

**Issue by Dagda47** [lemasato/POE-Trades-Companion#180]
None of the functionality this app offers is working for me anymore since the last time i played (September).
It seems like the requested inputs are not send to the game. If i get an incoming trade the buttons react, tabs get closed and the item-finder-grid also gets activated but none of commands for the chat box (invite, trade, etc.). A simple hotkey command like {Enter}/hideout{Enter} on pressing F2 doesn't work either.
I have tried the .exe and the .ahk script. I tried various combinations of skins, transparency and other options. I am running the newest version (1.13.6). TradeMakro works fine, hotkeys included.
I am running POE windowed, borderless fullscreen on one of my two monitors (Win 10).

Here are my latest logs:
[Logs.zip](https://github.com/lemasato/POE-Trades-Companion/files/2699900/Logs.zip)

Thanks for any help in advance.

**Comment by lemasato** [comment]
Did you try running the tool as admin?
Both the tool and the game need to run at the same elevation level. If the game is running as admin but the tool is not, it will be unable to interact with the game window.

**Comment by Dagda47** [comment]
That did the trick i think. The hotkeys are working. I didn't get a trade request yet.

Thank you very much!
