### ISSUE TITLE
Idea for counting currency stacks

### ISSUE THREAD

**Issue by Rising-Soul** [lemasato/POE-Trades-Companion#182]
Something that would be pretty handy for people who do a lot of currency trading, would be if the script could work out how many stacks a given amount of currency is.

Like, if someone wants to trade for my 125 chromatics, the script would tell me that that is 6 stacks plus 5. 

This would be great for late night half asleep currency trading :)

I imagine a list of currencies and how many per stack would be required to make this work - I'll gladly make the list if you just let me know what format to make it in.

**Comment by lemasato** [comment]
Hi,
You can actually use CTRL+SHIFT+Click. It allows to retrieve just the right amount of the requested currency.
For example, if your buyer asks for 33 chaos, the first, second and third presses will retrieve 3 stacks of 10, and the fourth one will put the last remaining 3 chaos on your cursor.

**Comment by Rising-Soul** [comment]
Wow, that's even better! Thanks :)
