### ISSUE TITLE
Support for Bulk Buying?

### ISSUE THREAD

**Issue by rushtothesun** [lemasato/POE-Trades-Companion#183]
Referencing: https://old.reddit.com/r/pathofexile/comments/a939m6/psa_you_can_use_the_bulk_buy_feature_on_poeninja/

Ex: https://poeapp.com/#/currency/{%22need%22:%20[%22Jungle%20Valley%20Map%22,%22Alleyways%20Map%22,%22Maze%20Map%22,%22Vaal%20Pyramid%20Map%22],%20%22league%22:%20%22betrayal%22,%20%22type%22:%20%22and%22}

**Comment by lemasato** [comment]
Not really sure how I could implement it the best way with the current interface.  
I could simply split each map name and put them in their own tab, but it would be a bit strange for the seller.

**Comment by JusKillmeQik** [comment]
If you could have it bring up a single tab, even if it doesnt highlight the maps just so we see what to grab at once. Same for buying, seeing how much we offered to make sure we bring the right amount. Thanks.

**Comment by lemasato** [comment]
@JusKillmeQik I don't really like the idea of one tab per item tbh. I'd like a proper solution, but that'll require some time.

**Comment by lemasato** [comment]
I'll be closing this issue to keep the issues tab cleaner as those are on my consider/to-do list. A page will be opened with future possible updates.
