### ISSUE TITLE
Trying to create a Advanced Hotkey

### ISSUE THREAD

**Issue by ReyuZero** [lemasato/POE-Trades-Companion#186]
I want a command to "Enter" "Control + V" "Enter"
to paste whispers from poe.trade, I tried many ways {Enter}{^v}{Enter}, {Enter}{Ctrl+V}{Enter}, and many others, but none worked

**Comment by lemasato** [comment]
There actually is a feature for just that.
Hold CTRL when clicking on poe.trade button to copy the whisper, and it will instantly be sent in-game upon releasing the key.

Otherwise, you could use one of these:
`{Enter}^v{Enter}` or `{Enter}{Ctrl Down}v{Ctrl Up}{Enter}`

**Comment by ReyuZero** [comment]
Thank you got it to work with the first command.
And I tried the thing with the CTRL, but it didnt work on google chrome for me, only when doing it with firefox.
