### ISSUE TITLE
Virus detected cant even be downloaded

### ISSUE THREAD

**Issue by Icyeee** [lemasato/POE-Trades-Companion#188]
![trojan](https://user-images.githubusercontent.com/43412278/50908702-37af5280-1465-11e9-91ed-02f12b2ede0e.jpeg)

**Comment by Icyeee** [comment]
I've also tried that but after i run the script it just disappears, is there anything i can do about that??

**Comment by lemasato** [comment]
What do you mean? If you are using the AHK release, it won't get flagged.
What exactly disappears? The files? Or does the script crashes?

**Comment by Icyeee** [comment]
I downloaded the POE-Trades-Companion-AHK-v1-13-6.zip and extracted it, ran the POE Trades Companion.ahk. Trade companion pops up for 10 seconds then it just randomly crashes i think and its gone

**Comment by lemasato** [comment]
Could you zip and send your Logs folder?
\Documents\lemasato\POE Trades Companion\Logs
