### ISSUE TITLE
Lock position option not sticking.

### ISSUE THREAD

**Issue by Niizz** [lemasato/POE-Trades-Companion#189]
Hey, so I'd just would like to point out that every other launch be it through .ahk or the .exe the lock position option un-checks itself in tray icon. Doesn't happen every launch just every other which I find strange.

**Comment by lemasato** [comment]
Thanks for reporting.
Actually, it appears to be reset every launch if you have the "Mode: Window" selected.

**Comment by Niizz** [comment]
Ah yes that's the mode I use. Should have included that. Thank you for all your work. Script is amazing.

**Comment by lemasato** [comment]
This will be fixed on the next update.
If you wish, you can use it now by [downloading the master zip](https://github.com/lemasato/POE-Trades-Companion/archive/master.zip)
