### ISSUE TITLE
Buttons customistation is broken after few clicks between two buttons

### ISSUE THREAD

**Issue by kasprzakdanielt** [lemasato/POE-Trades-Companion#191]
When I go to Customization->Buttons and jump between two buttons few times, then it just doesnt respond to changing button focus. Only restarting whole app helps.
![obraz](https://user-images.githubusercontent.com/9053610/51112065-7c890f80-17fe-11e9-98ff-d7159232f7e1.png)
![obraz](https://user-images.githubusercontent.com/9053610/51112075-84e14a80-17fe-11e9-8647-ba7655281ec3.png)

**Comment by lemasato** [comment]
Can't seem to be able to reproduce the issue.

- Tried click spamming buttons randomly.
- Tried adding new button, typing in action content box, click on another button.
In both cases, switchinb buttons was still working correctly.

**Comment by lemasato** [comment]
I'll be closing this issue to keep the issues tab cleaner as those are either already available in the latest ALPHA or on my consider/to-do list.  
If you wish to try it out, the ALPHA is available on the Discord server. Though, it is really only recommended for testings purpose and not meant to be used to replace the latest BETA.
