### ISSUE TITLE
Price check not working

### ISSUE THREAD

**Issue by Saiasanc** [lemasato/POE-Trades-Companion#192]
While using the price check feature all I ever get is the following:

"Could not find any item matching the same stash location
 Make sure to set your account name in the settings.
 Accounts: saiasanc"

I have tried capitalizing the account name as it appears on the official PoE website. I have also tried the in-game character name I am currently logged into. Nothing seems to work. It's always the same message.  Oh and I have not changed the location of the items AT ALL. So it's not that they are now in different locations or something.

**Comment by lemasato** [comment]
Could you try whispering yourself from [poe.trade](poe.trade/search?seller=Saiasanc&league=Betrayal) and see how it goes?  

The way price checking works is making a search on poe.trade with informations from the whisper:
League, item name (level and quality), and account name (case sensitive) which has to be specified in the settings. Then, for each item found, it will check for the one that has the same tab name and x;y position as the one provided in the whisper. Finally, the buyout price is retrieved and compared with the one from the whisper.  
So if your item does not appear on poe.trade, or the search fails, it won't be able to confirm the price.  

I'm not an expert with IE/cURL. Price checking functions were heavily inspired from TradeMacro.  
So if something goes wrong on the cURL request, I'm not sure I'd be able to help...
