### ISSUE TITLE
If a map is being sold, put the map Tier # next to the tab name?

### ISSUE THREAD

**Issue by rushtothesun** [lemasato/POE-Trades-Companion#194]
Would be extremely helpful if the map tier was included in that white box that says the tab name.

**Comment by livejamie** [comment]
Even better would be for the overlay to highlight the tab

**Comment by lemasato** [comment]
Yup. Was thinking about also showing the "map tier tab" to click.  
Could contain positions in a json, so that it could easily be updated every league.

**Comment by lemasato** [comment]
Highlighting "map tier tab" will be possible for all maps.
But showing the map exact position will only be possible for non-shaped maps.
This is because when adding a shaped map to the tier tab, it will be added to the end of the list, and we have no way of knowing which maps have been shaped.

**Comment by lemasato** [comment]
Feature will be part of next update.  
Keep in mind showing map case only work with non-shaped non-elder maps. As explained above, those maps are added on the tier at the end of the list, and we have no way of knowing which maps the player decided to upgrade. 

Also, this can only work with english whispers.
Some translated whispers have parts of their map name translated, and I couldn't find any list with their corresponding english name.

![image](https://user-images.githubusercontent.com/14184969/53337035-7c515900-3900-11e9-876a-63cde3e883c0.png)
