### ISSUE TITLE
alt + click new hotkey prevents ingame highlighting + picking up an item

### ISSUE THREAD

**Issue by RLFAneo** [lemasato/POE-Trades-Companion#195]
I believe by default in poe alt is used to highlight item. So you press alt to make the item appear, and click on it so that your character goes and pick it up. Now since the change "Currency easy trade hotkey changed to Alt+Click (previously Ctrl+Shift+Click)", the character doesn't move, which makes it easy very uncomfortable to pick up anything, or simply move while highlighting items. This basically forces me to close the macro or I can't play.

Is there any way for us to manually change this hotkey in the macro? (I don't want to change the ingame keys since they are very convenient)

**Comment by lemasato** [comment]
I'm on it, thank you for reporting.  
Sorry for the issue. I changed the hotkey from Ctrl+Shift+Click to Alt+Click at the last moment and forgot something. I'll deploy fix ASAP.

**Comment by lemasato** [comment]
https://github.com/lemasato/POE-Trades-Companion/releases

I've got the original issue fixed but there are some other interactions I didn't expect.  
I decided to temporarily disable the hotkey until I look for a better solution tomorrow.

**Comment by lemasato** [comment]
Hotkey has been changed to Ctrl+Right click.  

Additionally, it will only work if you have a trading tab open, is a currency trade, and the interface is not minimized.  
This is done in order to reduce potential unexpected interactions from happening.
