### ISSUE TITLE
Feature Request : direct stat export

### ISSUE THREAD

**Issue by Gloorf** [lemasato/POE-Trades-Companion#196]
Related to #152, opening the "My stats windows" can take quite a while (the first time I opened it I thought it was bugged and didn't work, since it took several minutes to open !). Would it be possible to have an option to export to CSV directly from the main menu, to avoid this long wait time ?

**Comment by lemasato** [comment]
Could you actually share your Trades_History.ini? I'd like to try some things to potentially improve the loading.  
You can zip the file and attack it here, or PM it to me on the Discord channel.

**Comment by Gloorf** [comment]
[Trades_History.zip](https://github.com/lemasato/POE-Trades-Companion/files/2942154/Trades_History.zip)

Here you go ! The file is less than 3 MB so it shouldn't take that long to read and parse it :)

**Comment by lemasato** [comment]
Hey, I've fixed the loading times.
On 1.14.2, it took 407 seconds to load up the stats menu with the file you provided me.
This has been reduced to ~3 seconds.
