### ISSUE TITLE
Popup location incorrect

### ISSUE THREAD

**Issue by Milkshakes00** [lemasato/POE-Trades-Companion#197]
Have an issue where the popup window is not staying where I closed it, and it's popping up mostly off my main monitor. Not sure if this is a multi-monitor issue? My main monitor is 1440p while both side monitors are 1080p. I've tried moving the box and locking the position, but it still pops in the top left, unfortunately making it very clunky. Attached is a screenshot.

![TradeCompanionLocation](https://user-images.githubusercontent.com/708869/54072003-c1e81d00-4242-11e9-9a9a-86c5fc785c88.png)

**Comment by lemasato** [comment]
> not staying where I closed it
Do you mean on app reload?
Or upon closing a tab?

Most likely an issue related to windows scaling

**Comment by Milkshakes00** [comment]
I've tried reloading the application. This position resets everytime I close the tab window. 

Is there a fix for windows scaling if that's the case?

**Comment by lemasato** [comment]
It's a setting within [Windows](https://images.idgesg.net/images/article/2018/07/scalingwindows10-100764460-large.jpg) itself.
I will have to inspect the issue later.
Meanwhile, I think you can use the "Mode: Window" tray setting, and that should work fine.

**Comment by Milkshakes00** [comment]
If it helps, my windows scaling is at 100%. I'm wondering if it's due to the different monitor resolutions?

**Comment by lemasato** [comment]
Dual monitor shouldn't be an issue.
Could you upload your logs folder?
/Documents/lemasato/POE Trades Companion/Logs - Zip the whole folder and attach it here

**Comment by Milkshakes00** [comment]
Here ya go. (Also, why does github not support .rar...? O_o)

[Logs.zip](https://github.com/lemasato/POE-Trades-Companion/files/2948469/Logs.zip)

**Comment by lemasato** [comment]
Can you confirm if that also happen whenever you minimize the interface?  
When the issue happens, does it always move to that specific position (top right of screen)?

**Comment by lemasato** [comment]
Also, is there any specific reason for you to use the .exe version?  
I will most likely get rid of it in the future, due to the virus flagging issues.  
I would recommend to use the .ahk one instead. Though, it lacks the "single portable executable" convenience...
