### ISSUE TITLE
Window minimizes too much and is ugly now

### ISSUE THREAD

**Issue by phlawski** [lemasato/POE-Trades-Companion#198]
Hi,

I'm using "path of exile" theme and in newest version minimized state looks very awful now - it's white. Look at screenshot: https://imgur.com/a/DCDkCwa

What's more it minimizes now too much. There is no option to minimize it as was in previous version that it just slides up window and title bar stays with the same size as before. I'd like to have it back.

**Comment by lemasato** [comment]
![image](https://user-images.githubusercontent.com/14184969/54299910-277a3780-45bc-11e9-91ee-6824a9814d63.png)
(This is how it is supposed to look like)

- Can you upload a zip of your Logs folder? `/Documents/lemasato/POE Trades Companion/Logs`
- In `\Documents\lemasato\POE Trades Companion\Skins\Path of Exile`, do you see HeaderMin.png?

**Comment by phlawski** [comment]
1. Logs in the attachement.
2. Yes, i can see mentioned file but it's slightly bigger then I'd expect.
[Logs.zip](https://github.com/lemasato/POE-Trades-Companion/files/2963026/Logs.zip)

**Comment by lemasato** [comment]
Assets.ini and Settings.ini fail to extract.  
You can place them manually and it'll be fine.  
Copy them from `C:\Program Files (x86)\POE-Trade-Companion\resources\skins\Path of Exile\` to `\Documents\lemasato\POE Trades Companion\Skins\Path of Exile`

**Comment by phlawski** [comment]
Ok. Thanks for assistance. Seems that everything looks nice right one.
