### ISSUE TITLE
Little green square

### ISSUE THREAD

**Issue by shadowerwtas** [lemasato/POE-Trades-Companion#200]
What's the point of the little green square alongside with the big green square that points where the item is at the tab?

Everytime i trade something that little square points at irrelevant locations and it's a bit disturbing. Is there a use for it i can't understand?

**Comment by lemasato** [comment]
https://github.com/lemasato/POE-Trades-Companion#item-location-grid

It's the item location for quad tabs.
If you don't have any, you can disable it in Settings.
"Hide quad tab location"

**Comment by shadowerwtas** [comment]
If only i read the front page before i ask the question -_-
Thanks a lot mate!

**Comment by lemasato** [comment]
Happy trading :p
