### ISSUE TITLE
Grid location off for maps since new league started?

### ISSUE THREAD

**Issue by mangni** [lemasato/POE-Trades-Companion#201]
Hi, I noticed since the new league started, the grid location is wrong when people whisper to buy my maps (for map tab, and regular size tabs).  I am playing in Standard.

**Comment by lemasato** [comment]
Have you updated to the latest version?
The atlas shuffles with every league, and so I had to include the new positions.

**Comment by mangni** [comment]
Yes I have the latest release.  It's strange that even in non-map tabs it doesn't locate the maps properly.

**Comment by lemasato** [comment]
Could you show screenshots of the issue?

**Comment by mangni** [comment]
Sure I'll try and get a screenshot of it.  Thanks again for your quick replies and updates  :-)

**Comment by mangni** [comment]
Got the screenshot ... https://imgur.com/ovM6oFl
As you can see the location is off and there are three squares for some reason.  Seems to only happen with maps, other items are ok.

**Comment by lemasato** [comment]
Those blue squares are actually showing the location in a map tab.
https://github.com/lemasato/POE-Trades-Companion#item-location-grid

I recently added an option to hide regular and quad locations if the map is an item. By default, this setting is enabled. You can toggle it from the Settings.

**Comment by mangni** [comment]
Thank you so if I uncheck the box "Hide normal and quad locations for maps", it will display the location correctly?  If so can we have it this way by default?  Would it affect the location grid in map tab?

**Comment by lemasato** [comment]
Yup.
It will show both the blue squares (map tab), and the green squares (regular and quads tabs). I decided to make this setting enabled by default because the map tab is quite powerful and lots of people use it. Settings are kept when updating, so you only have to uncheck this case now and it'll be good forever.
