### ISSUE TITLE
messages from poeapp.com are not recognized

### ISSUE THREAD

**Issue by phlawski** [lemasato/POE-Trades-Companion#204]
I'm getting more and more requests from  poeapp.com and Trades Companion seems to not recognize them at all. Could you add support for it?

**Comment by lemasato** [comment]
There is support for poeapp.com.
Could you show the whispers? Screenshot is more than enough

**Comment by phlawski** [comment]
Sure, here it is
![Path of Exile 3_18_2019 8_01_50 PM (2)](https://user-images.githubusercontent.com/28409/54556325-ea95b280-49b8-11e9-8433-7adba5fed779.png)

**Comment by lemasato** [comment]
Strange, I'm almost sure it used to be the same pattern as currency.poe.trade until recently.
I'll add it on next update, thanks for reporting!

**Comment by phlawski** [comment]
This guy said something about "bulk" buy. Maybe it's because he requested 2 fossils for 2c. I'm listing Frigids for 1c each.

**Comment by lemasato** [comment]
Yup. PoeApp (https://poeapp.com/currency) has a section specific for currency trading, just like poe.trade has currency.poe.trade.

currency.poe.trade: `Hi, I'd like to buy your x for my x in x.`
poeapp.com/currency: `I'd like to buy your x for my x in x.`
But I'm almost sure poeapp used to include this `Hi, `

**Comment by phlawski** [comment]
Maybe it's good idea to make it configurable on your side? Then you'd not need to care about it in the future that much.
