### ISSUE TITLE
Make "Trades" windows non focusable

### ISSUE THREAD

**Issue by Pegoth** [lemasato/POE-Trades-Companion#205]
It is possible to extend the exstyle of window with WS_EX_NOACTIVATE (0x08000000) flag, which will prevent obtaining focus when clicking on the GUI. This would fix PoE (and other scripts tied to PoE) losing focus while trading with POE-Trades-Companion.

I force set the exstyle with an autoit script (had to do it twice, once for minimized and once for restored Trades window) and it worked perfectly. PoE no longer lost focus and every button worked perfectly.

The code I used to set the exstyle of the currently focused window:
```autoit
#RequireAdmin
#include <WinAPI.au3>

HotKeySet("{F5}", "kek")

Func kek()
	Local $title = WinGetTitle("")
	Local $handle = WinGetHandle($title)
	
	_WinAPI_SetWindowLong($handle, $GWL_EXSTYLE, BitOR(_WinAPI_GetWindowLong($handle, $GWL_EXSTYLE), 0x08000000))
	
	MsgBox(0, "Done", $title)
EndFunc

While 1
	Sleep(100)
WEnd
```

**Comment by lemasato** [comment]
What exactly is the issue?  
If you're clicking the interface, why should it not be focused?  
Also, you can make the interface click-through and transparent when no tabs are open, from the Settings.

**Comment by Pegoth** [comment]
> What exactly is the issue?
> If you're clicking the interface, why should it not be focused?
Because I use both MercuryTrade and also have in game sound muted when PoE is not focused.
If I click on the GUI MercuryTrade (and every other program that is tied to PoE being focused) will disappear.

It is very anoying and the exstyle I provided fixes it without breaking anything. MercuryTrade works the same way.

**Comment by lemasato** [comment]
That's interesting actually.
It breaks the built-in hotkeys (Ctrl+1/2/etc and Ctrl+WheelUp/Down to scroll through tabs), but I can make it work based on the window under the mouse cursor.

Didn't know about that, thank you!

**Comment by lemasato** [comment]
This will be added on next release, thank you!
