### ISSUE TITLE
Trades companion window will not remain on second screen

### ISSUE THREAD

**Issue by 99TonyStark99** [lemasato/POE-Trades-Companion#206]
Complains the window is out of bounds and resets it to the top right of the first screen

**Comment by lemasato** [comment]
What exactly are the conditions?

**Comment by lemasato** [comment]
Oh nevermind didn't notice the second screen thing. Luckily I have access to two monitors today, so I'll try it out and see.

**Comment by lemasato** [comment]
@99TonyStark99 How is your dual screen set up?
No issue here, main on middle, second on left, both 1080p

**Comment by 99TonyStark99** [comment]
Same arrangement here first is 1080, but the second screen (on left) is 1366x768, and is configured so the bottoms of the screens line up.  
Messing with it more I notice it only happens on startup, or when I access the settings.  if I reposition it after a whisper, it's fine again (until I hit settings)

**Comment by xanthics** [comment]
3x 2440x1440 monitors.  Middle is poe(main), left is PTC(2), right is other stuff(3), resulting in left monitor having negative x location values.  PTC resets window position to upper right main monitor at startup, mentioning invalid location.

```
[SETTINGS_MAIN]
[...]
Pos_X=-591
Pos_Y=53
[...]
```

**Comment by lemasato** [comment]
Only at startup?
Not when you move the interface, or min/max it?

**Comment by 99TonyStark99** [comment]
This seems to have fixed my issue, It no longer complains about the position.

I tried to recreate the issue with using the settings, this is no longer a problem either.

Thanks, and may the RNGods smite you with exalts!

**Comment by lemasato** [comment]
Oh, so this zip fixed your issue?
I'll try to get an update pushed as soon as I can
