### ISSUE TITLE
Feature Request: Ignore Sold Items

### ISSUE THREAD

**Issue by Davst** [lemasato/POE-Trades-Companion#207]
Hi, so I have a feature request for when I have sold an item. I'd love if after you press the "Thanks"/Complete Trade button the trade app would ignore that specific whisper.. 

Since the whisper format contains item, level position and so.. it'd be pretty easy to match and ignore for 30 mins or so

**Comment by zorgshanker** [comment]
Open settings > Buttons > edit ty. Thank you one

From the scroll down select ignore tab item for 10 minutes.

You can also add close other tabs for the same items if you wish

**Comment by Davst** [comment]
ty
