### ISSUE TITLE
New auto-price check feature not working?

### ISSUE THREAD

**Issue by mangni** [lemasato/POE-Trades-Companion#209]
I have added my account name in settings, but still when a whisper comes in, I waive my mouse over the dot and it is stuck at "Comparing price on poe.trade…".

**Comment by sclient** [comment]
Same here. Seems to have started with this league. I recall my error message being different, but Ill have to wait for a chance to copy it.

**Comment by sclient** [comment]
Well for some reason I cant make the edit button work, so the message was 'could not find any item matching stash posistion'

**Comment by lemasato** [comment]
@sclient Some items can take ages to appear on poe.trade, but appear almost instantly on the official website. The price verify feature uses poe.trade, so if the item isn't there yet, it won't be able to verify the price and thus "could not find any item matching stash position".

@mangni Ugh, post is from March? Sorry I never got around to answer you.
It would be really hard to debug this. I'm thinking of adding a /Debug parameter that would log extra lines. This would be really helpful in situations like this.
But until then, sorry to say, but I can't help :/

**Comment by lemasato** [comment]
I'll be closing this issue to keep the issues tab cleaner as those are either already available in the latest ALPHA or on my consider/to-do list.  
If you wish to try it out, the ALPHA is available on the Discord server. Though, it is really only recommended for testings purpose and not meant to be used to replace the latest BETA.
