### ISSUE TITLE
[Bug] Russian names do not work correctly!

### ISSUE THREAD

**Issue by mrG0bliN** [lemasato/POE-Trades-Companion#210]
### Info
![image](https://user-images.githubusercontent.com/11839238/55294748-64448c00-540e-11e9-8381-c9e3cada81ba.png)

------
![image](https://user-images.githubusercontent.com/11839238/55294662-580bff00-540d-11e9-85b9-efd4e6f70153.png)
1. Comming request
1. Wrong parse name 
1. Character does not exist
1. I'm trying to write a whisper

### Fix pls guys T__T

**Comment by lemasato** [comment]
- Does the name appear correctly on the interface?
- Can you provide logs? They contain informations about your AHK installation
/Documents/lemasato/POE Trades Companion/Logs - Zip the whole folder and attach it here

**Comment by mrG0bliN** [comment]
> * Does the name appear correctly on the interface?
> * Can you provide logs? They contain informations about your AHK installation
>   /Documents/lemasato/POE Trades Companion/Logs - Zip the whole folder and attach it here

Logs ? :D 
![image](https://user-images.githubusercontent.com/11839238/55339857-2bf38b00-54ac-11e9-8e44-48b180f57284.png)

i use AHKv2 -> this version: https://www.autohotkey.com/boards/viewtopic.php?p=242306#p242306

**Comment by lemasato** [comment]
Sorry for the late answer.  
Next time this issue happen, please let me know if the name appears correctly on the trades interface. It'll help me determine the source of the issue.  

Personally tried russian names, no issues.
(If you'd like, you can send this in the local chat to simulate a trading whisper:
```a @From русскоеимя: Hi, I would like to buy your ITEM listed for PRICE in Synthesis```

**Comment by mrG0bliN** [comment]
> Sorry for the late answer.
> Next time this issue happen, please let me know ...

Okay, don't close issue pls.

**Comment by Lizlet** [comment]
Personally I have no problem trading with russian names, but they don't show up at all on the interface. just blank characters.

**Comment by mrG0bliN** [comment]
@lemasato maybe try use new encode like a:

	"fallback_encoding": "Cyrillic (Windows 1251)"
?

**Comment by mrG0bliN** [comment]
> Sorry for the late answer.
> Next time this issue happen, please let me know if the name appears correctly on the trades interface. It'll help me determine the source of the issue.
> Personally tried russian names, no issues.
> (If you'd like, you can send this in the local chat to simulate a trading whisper:
> `a @From русскоеимя: Hi, I would like to buy your ITEM listed for PRICE in Synthesis`

![10-04-2019 11-00-49](https://user-images.githubusercontent.com/11839238/55861941-1c490600-5b80-11e9-853c-1ca8efa39f85.jpg)
![10-04-2019 11-00-44](https://user-images.githubusercontent.com/11839238/55861943-1ce19c80-5b80-11e9-9c7a-b78970593a60.jpg)

**Comment by lemasato** [comment]
@mrG0bliN Does the name appear correctly in your Client.txt?
`\YourGamePath\logs\Client.txt`

- If so, delete your POE Trades Companion folder and redownload the latest version from the releases page.
- If not, then close your game, close the tool, delete Client.txt and retry.

**Comment by mrG0bliN** [comment]
@lemasato client.txt 
![image](https://user-images.githubusercontent.com/11839238/56767716-1fb1d380-67b5-11e9-8749-4f136360d62c.png)

**Comment by mrG0bliN** [comment]
@lemasato reintall and download new version help me : |
