### ISSUE TITLE
QOLs that would greatly benefit this program

### ISSUE THREAD

**Issue by leet0rz** [lemasato/POE-Trades-Companion#211]
1.Make the entire windows smaller, like a horizontal bar, its to big currently and downsizing it makes it unreadable and unusable.

2.Make it work with outgoing messages too, currently it only detects incoming messages, let us have it so if we message people for trades we can get the same window and go to their hideout and press a trade button and so on.

3.Trade history, if i miss click the [x] there should be a way to open the same trade again, but it seems to be gone forever. Give us a history so we can bring up old trades again.

The item locator in stash shows 3 location windows instead of 1, not entirely sure why it does this.

**Comment by lemasato** [comment]
Hi,

1. I'd like to offer an alternative interface, but that'd involve a lot of work. Maybe later.

2. Will probably happen. Need to find the optimal way to set it up.

3. Not sure. I don't think that'd be any useful most of the time.

4. https://github.com/lemasato/POE-Trades-Companion#item-location-grid

**Comment by lemasato** [comment]
I'll be closing this issue to keep the issues tab cleaner as those are either already available in the latest ALPHA or on my consider/to-do list.  
If you wish to try it out, the ALPHA is available on the Discord server. Though, it is really only recommended for testings purpose and not meant to be used to replace the latest BETA.
