### ISSUE TITLE
Exception on checking for updates

### ISSUE THREAD

**Issue by johannesschweig** [lemasato/POE-Trades-Companion#212]
Hi,
thanks for the beautiful application making my poe life so much easier!

I get an exception every time the application checks for updates (on each startup at least). It says: `exception thrown (download)! Error while downloading <https://api.github.com/repos/lemasato/POE-Trades-Companion/releases?page=1> using UrlDownloadToFile`.  After that another modal window appears `There was an issue when retrieving the latest release from GitHub...`. 

It would not be bugging me if there was an option to not check for updates on each startup.

I am running v1.14.2 on Win10 with AutoHotkeyU64-v1.130.03. 

Here are my logs.
[Logs.zip](https://github.com/lemasato/POE-Trades-Companion/files/3069870/Logs.zip)
I am also happy to do some more debugging when told where to search.

**Comment by LillieSatou** [comment]
same here, using AHK V1.130.01

**Comment by jakeboxer** [comment]
Same here! Been this way since I first started using the program (which I absolutely love by the way, so thanks!).

- Version 1.14.2
- AHK 1.130.02
- Windows 10

**Comment by Heebeaux** [comment]
I resolved this buy adding a temp folder in my POE-Trades-Companion-AHK-v1-14-2 folder. cURL was failing to create the folder if it wasn't there

**Comment by jakeboxer** [comment]
@Heebeaux ahh great find! Submitted a PR (#213) to hopefully get this fixed for the next release.

**Comment by lemasato** [comment]
Hi, sorry for the late answer.
I should get back on actively coding soon.

How about this one? Can someone who has the issue try and see if it fixes it?
[POE-Trades-Companion-Issue212-1.zip](https://github.com/lemasato/POE-Trades-Companion/files/3093061/POE-Trades-Companion-Issue212-1.zip)

**Comment by Heebeaux** [comment]
POE-Trades-Companion-Issue212-1.zip works. 
I looked into the issue. The reason it was failing before is the script was looking for the curl.exe  in the "C:\User\<USER>\Documents\lemasato\POE Trades Companion\" folder. Since I just downloaded  the zip file curl.exe wasn't copied there. Copying it from the third-party folder fixes the issue. With the curl.exe in place the UrlDownloadToFile fallback never fails. I didn't see any options in the AHK help file to force folder creation.

**Comment by johannesschweig** [comment]
@lemasato Your zip archive works for me.
@Heebeaux Copying a temp folder into the "POE-Trades-Companion-AHK-v1-14-2" folder resolved the issue as well. However, I don't need the curl.exe file in the Documents folder for it to function.
Thanks for digging into this all of you

**Comment by lemasato** [comment]
Fix will be part of the next update.
Thanks for reporting!
