### ISSUE TITLE
New bar at top left which won't disappear.

### ISSUE THREAD

**Issue by Scorten** [lemasato/POE-Trades-Companion#215]
I have this bar at the top left which seems to be new. It stays there permanently, which annoys me because I find it to be useless (it only has two (out of four) working buttons, Return to Hideout and a League button). I don't understand why I would need a separate tool bar just for these two functions. Also it overlaps with buff/debuff icons in-game and tooltips (e.g. when selecting a gem as quest reward the name of certain gems is not visible because it's behind this new tool bar). Is there a way to disable it or make it transparent? Also it basically took the place my whisper notifications did. I have not received any trade requests yet but I fear that this new toolbar will mess with the wisper notification window (which is also located at the top left).

PS: I know that I can move it but it doesn't matter where I put it, it's always in the way and hides crucial information (top left = buffs/debuffs; top right = map, FPS, ping; bottom left/right = skill bar, health/mana). I don't want to move it around, I want it gone.

**Comment by Z0MBIE2** [comment]
Yeah can confirm, can't find any sort of option to disable or make this bar transparent.

**Comment by fuba82** [comment]
same here

**Comment by lemasato** [comment]
I have added transparency + clickthrough to the new interface.
This means you won't be able to access the toolbar if you haven't sent any trade whisper. As a temporary workaround, until I can find a more suitable solution, I have added the league sheet thing to the tray menu.

**Comment by lemasato** [comment]
Closing this as the patch will be pushed really soon :p 
Thank you for the feedback!
