### ISSUE TITLE
Error at line 354

### ISSUE THREAD

**Issue by Fededark** [lemasato/POE-Trades-Companion#216]
#Include in file "Class_GUI_CheatSheet.ahk" cannot be opened.

**Comment by lemasato** [comment]
POE-Trades-Companion-AHK-v-1-15-BETA_3\lib\Class_GUI_CheatSheet.ahk
Does the file exist?

Which version were you using previously?

**Comment by Fededark** [comment]
Was BETA 4 but seems solved after patching to BETA 5
