### ISSUE TITLE
No tabs opening when receiving whispers

### ISSUE THREAD

**Issue by geoffasaurus** [lemasato/POE-Trades-Companion#217]
I've tried reinstalling and no luck, not sure what to do next?

[logs.zip](https://github.com/lemasato/POE-Trades-Companion/files/3268973/logs.zip)
- For issues, make sure to zip and attach your Logs folder:  
/Documents/lemasato/POE Trades Companion/Logs  

- For questions, make sure to check the README on the [project page](https://github.com/lemasato/POE-Trades-Companion) and the [Wiki](https://github.com/lemasato/POE-Trades-Companion/wiki)  
If you haven't found an answer, it is really fine to post an issue to ask about it  
Though, the quickest way would be to directly ask on the [Discord](https://discord.gg/UMxqtfC)

**Comment by lemasato** [comment]
Fixed on 1.15.BETA_4, thanks for the report!
