### ISSUE TITLE
White border around the new interface.

### ISSUE THREAD

**Issue by Tadiian** [lemasato/POE-Trades-Companion#219]
Is this already known and common or is it a wierd bug?

It is only around the new interface, not the old one and I can't get rid of it. Tried every option.

https://i.imgur.com/G1t1lgb.png

**Comment by lemasato** [comment]
Are you using a scaling different than 100% in Trades Companion?
Also, are you using a different scaling setting than 100% in windows?

**Comment by Tadiian** [comment]
No but the latest Beta 5 update (got the update this morning) seems to have fixed this.
