### ISSUE TITLE
Button changes not saved

### ISSUE THREAD

**Issue by Dgc2002** [lemasato/POE-Trades-Companion#220]
I'm attempting to change the message sent to someone prior to kicking them. See the following video:  
  
![2019-06-09_10-28-43](https://user-images.githubusercontent.com/3957791/59160929-7b07fe80-8aa1-11e9-9125-d7820cebf41a.gif)

I'm not sure if I'm missing a step or what.  

Log:
[2019-06-09 10h01m50s.txt](https://github.com/lemasato/POE-Trades-Companion/files/3269671/2019-06-09.10h01m50s.txt)

**Comment by lemasato** [comment]
Seems settings cannot be saved. Clicking on the button reloads settings from the file, and if those settings aren't saved, it will be back to how it was before.

There's a similar old issue about Custom Buttons, and reloading the app fixes it. Have you tried?
Also, in the folder `\Documents\lemasato\POE Trades Companion`, make sure that Preferences.ini isn't set as read-only for some reasons.
You could additionally try resetting settings to default, or edit the file manually to add your message.

**Comment by lemasato** [comment]
I'll be closing this issue to keep the issues tab cleaner as those are either already available in the latest ALPHA or on my consider/to-do list.  
If you wish to try it out, the ALPHA is available on the Discord server. Though, it is really only recommended for testings purpose and not meant to be used to replace the latest BETA.
