### ISSUE TITLE
Crash on Start/No pop-up created when receiving whisper

### ISSUE THREAD

**Issue by NJBS** [lemasato/POE-Trades-Companion#221]
Seems like it crashes on start or shortly after start.

[Logs.zip](https://github.com/lemasato/POE-Trades-Companion/files/3269696/Logs.zip)

**Comment by lemasato** [comment]
Someone reported a similar issue on Discord and reinstalling AHK apparently fixed the issue, could you try?

**Comment by lemasato** [comment]
Also, "No pop-up created when receiving whisper" has been fixed in BETA_4, so it could be that you're using an outdated version.

**Comment by NJBS** [comment]
Updating my AHK fixed this, thanks!
