### ISSUE TITLE
Korean Client Support

### ISSUE THREAD

**Issue by Shinzor** [lemasato/POE-Trades-Companion#223]
Thank you for keeping the addon up, great job!

However, the Korean Client cannot be read. Please add "PathOfExile_KG.exe" and "PathOfExile_x64_KG.exe" to the supported window list-thingy.
(We need to use a different client to access the Korean server.)

Thank you! :)

**Comment by lemasato** [comment]
Oh, thank you for reporting.
I added support for Korean whispers, but had no idea they had to use a different exe.

If you wish to use the fix now, you can replace your "POE Trades Companion.ahk" with this one:
https://raw.githubusercontent.com/lemasato/POE-Trades-Companion/dev/POE%20Trades%20Companion.ahk

**Comment by lemasato** [comment]
Closing this issue as it'll be added on next update. Sorry it took so long to get it pushed, and thank you again for letting me know about this!
