### ISSUE TITLE
[Feature request] Settings & Hotkeys for League Sheets

### ISSUE THREAD

**Issue by Razunter** [lemasato/POE-Trades-Companion#224]
1. There should be an option to replace the app's league sheets with your own custom ones (without replacing files)
2. League sheets should be bindable in settings.

**Comment by lemasato** [comment]
Yup. Hotkey to bring up sheets would be nice.
Maybe bring up a small interface, and you'd be able to choose which sheet to show in fullscreen. Also this small interface would work with any .png file present in the cheatsheets folder, so that users can use their own like you said.

**Comment by lemasato** [comment]
By the way, if you know of any better sheet, let me know.
Or maybe I could look around for some updated informations and make my own.

**Comment by Razunter** [comment]
@lemasato best ones currently are here: https://wraeclast.com/

**Comment by LoneWolfHowl** [comment]
I just saw these today and was disappointed to not be able to hotkey them. This would be an amazing addition!

**Comment by HB25** [comment]
+1

Coming from Mercury trade, I really miss the quick access to the Betrayal sheet.

**Comment by lemasato** [comment]
I added the hotkey already in 1.15.BETA_10.
The new Sheets interface will come in a future update.

**Comment by lemasato** [comment]
I'll be closing this issue to keep the issues tab cleaner as those are on my consider/to-do list. A page will be opened with future possible updates.
