### ISSUE TITLE
program thinks diff price tag is a different trade

### ISSUE THREAD

**Issue by Invisybr** [lemasato/POE-Trades-Companion#225]
Hi,

In my buttons I added the "ignore item tab for 10 min" to the button that thanks them and kicks from party. However, some people are using different trading sites to message me, and depending on if the site refers to the price as "x alch" or "x alchemy" it will think they are different items... so if I sell to someone that their copy+paste message spells it alch, and then someone else messages me and theirs calls it alchemy it won't ignore the second trade like it should.

Thanks, sorry it was a little wordy but wasn't sure of a concise way to explain it.

**Comment by lemasato** [comment]
Closing this as it'll be part of next update. Thanks for reporting!
Next update will use the "real" currency name on the interface, instead of the one from the whisper.
