### ISSUE TITLE
Add /whois button to the outgoing trade window

### ISSUE THREAD

**Issue by Homiephobia** [lemasato/POE-Trades-Companion#226]
This would be a good addition to quickly see whether the seller is busy.

**Comment by lemasato** [comment]
I'll be closing this issue to keep the issues tab cleaner as those are either already available in the latest ALPHA or on my consider/to-do list.  
If you wish to try it out, the ALPHA is available on the Discord server. Though, it is really only recommended for testings purpose and not meant to be used to replace the latest BETA.
