### ISSUE TITLE
Problem with interface

### ISSUE THREAD

**Issue by Djmitry4** [lemasato/POE-Trades-Companion#227]
interface is looks like it compressed 
https://imgur.com/Q3wALdF
don't know what to do.

**Comment by lemasato** [comment]
- Can you zip and attach your logs folder from \Documents\lemasato\POE Trades Companion\Logs?
- Can you provide a second screenshot with 2 whispers?
You can simply whisper yourself from poe.trade.

**Comment by lemasato** [comment]
Nevermind I get it, it's due to Windows DPI being higher than 100%. I'll be on it.

**Comment by Djmitry4** [comment]
Little update of the problem - it's work wrong only when i want to buy smth. When i get a sales request it's work wrong!

**Comment by Vargass1** [comment]
> * Can you zip and attach your logs folder from \Documents\lemasato\POE Trades Companion\Logs?
> * Can you provide a second screenshot with 2 whispers?
>   You can simply whisper yourself from poe.trade.

i have the same problem :(
https://imgur.com/a/7wf1OV5

**Comment by lemasato** [comment]
@Vargass1 The fix will be part of a small update tomorrow.

**Comment by nahana78** [comment]
interface issue, happen only buying interface. selling interface is fine
if i click minimize half of them is gone and sometimes all of them. i have to guess where is maximize  button and click.(url
![3123](https://user-images.githubusercontent.com/51951726/59671855-80d4b100-9212-11e9-91a0-943dbfe15b30.jpg)
)

**Comment by lemasato** [comment]
Closing as fix will be part of next update.
Thank you for the reports!
