### ISSUE TITLE
interface

### ISSUE THREAD

**Issue by antajl** [lemasato/POE-Trades-Companion#228]
https://puu.sh/DGHu4/73fe005d33.png
Always have doubled interfaces. Maybe it's bugged from previous versions. What do i do to fix it
I tried to delete program and "lemasato" folder from documents. Didn't help

**Comment by lemasato** [comment]
Hey,
This is the new interface when buying items.
In this case, you just whispered yourself and so both incoming ant outgoing interfaces got triggered.

You can disable the new buying interface by right clicking on the tray icon and choosing "Disable buy interface?"

**Comment by antajl** [comment]
oh, thanks. I tested it with my own item so it's show both windows
