### ISSUE TITLE
Bulk Map selling suggestions

### ISSUE THREAD

**Issue by Johay90** [lemasato/POE-Trades-Companion#229]
Sometimes when you get messages for bulk maps for example “5 Dunes (T8)”.when you try to copy this it would copy “5 Dunes tier:8” which isn’t really helpful for the search box in a map tab. It would be much better if you could translate this to just be “dunes”.

The above works like this when you get messages from poe.trade, but not when you get messages from pathofexile.com/trade

On the same note, it would be cool if bulk selling would work the same way as single map selling (ie it would just highlight certain spots in the map tab). Would be a nice QoL to speed up map selling.

**Comment by lemasato** [comment]
Hey, sorry it took so long.
> Sometimes when you get messages for bulk maps for example “5 Dunes (T8)”.when you try to copy this it would copy “5 Dunes tier:8” which isn’t really helpful for the search box in a map tab. It would be much better if you could translate this to just be “dunes”.

This will be included in next update.

> On the same note, it would be cool if bulk selling would work the same way as single map selling (ie it would just highlight certain spots in the map tab). Would be a nice QoL to speed up map selling.

This, will take a bit longer.

**Comment by lemasato** [comment]
I'll be closing this issue to keep the issues tab cleaner as those are on my consider/to-do list. A page will be opened with future possible updates.
