### ISSUE TITLE
Interface header semi-invisible

### ISSUE THREAD

**Issue by nahana78** [lemasato/POE-Trades-Companion#230]
interface issue, happen only buying interface. selling interface is fine
if i click minimize half of them is gone and sometimes all of them. i have to guess where is maximize  button and click.(url
![3123](https://user-images.githubusercontent.com/51951726/59671855-80d4b100-9212-11e9-91a0-943dbfe15b30.jpg)
)
![123](https://user-images.githubusercontent.com/51951726/59672060-ea54bf80-9212-11e9-88e4-ee73d5bdd583.jpg)
[Logs.zip](https://github.com/lemasato/POE-Trades-Companion/files/3301048/Logs.zip)

**Comment by lemasato** [comment]
That's actually really strange.
The invisible part of the window, are you able to click through it? Like clicking on that invisible stop makes your character move that way?

> if i click minimize half of them is gone and sometimes all of them

When you minimize then maximize the interface, some of the trades are gone?

**Comment by nahana78** [comment]
Yea either way click through or can still click depend on setting. Trades r still there, they just become invisible it comes back if i click again and again

**Comment by lemasato** [comment]
Do you think you could share a video of the issue?

**Comment by nahana78** [comment]
i just took a video please have a look.

https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAUu0zfwHzA8Qjct8w4zuAQsJ2m3tAV3tF_Q4u44LJv396dwnp50Afrh7%2F%24%7Bf%7D%3Fo%3DAsFcl9eAyGHEFYr2ZULCNfJHckqLaApgiNa42Itrd5yV%26v%3D1%26x%3D3%26a%3DCAogF3ty6Zz1WYgwVC8TXtr486mabaeUgSgeJQJd3a-vVMsSJxCU5Z7NvS0YlPWZocctIgEAKggByAD_Otl9vFIECdpt7VoEAH64ew%26e%3D1565316774%26k%3D%24%7Buk%7D%26fl%3D%26r%3DD358D128-0972-4DF5-87A8-2E26BE02502A-1%26ckc%3Dcom.apple.largeattachment%26ckz%3D4223A311-094C-4FF9-91AC-0F23D185A83D%26p%3D15%26s%3DyaNL4fzIa9und0hqpjmvKKdJLSE&uk=52i2Irn9nuQ8qShxoTX17A&f=IMG_0078.MOV&sz=28695507

**Comment by lemasato** [comment]
I ran into something kind-of similar while working on the current ALPHA. Though, I'm really unsure what caused it or how it could happen. I'm afraid this will stay a mystery for a long time. I'll keep this open in case I run into it again when I'll get back to working on the ALPHA.
