### ISSUE TITLE
item grid location button.

### ISSUE THREAD

**Issue by nahana78** [lemasato/POE-Trades-Companion#231]
Hi there,

Would you please add a function key to check to find a location of an item without click invite button?
Since getting too much pm even after sold it, sometimes i realize that item is sold after i invite someone.
That would be great i can check item is still available or not before i invite.
Thanks

**Comment by lemasato** [comment]
Hey,
I realized this when playing this league and was actually thinking of making it so the item grid would always appear as long as the interface is not minimized. Minimizing the interface would hide the grid, so that if wouldn't be annoying while mapping.

**Comment by nahana78** [comment]
that sounds fantastic :)

**Comment by lemasato** [comment]
Hey, so this has been added as of 1.15.BETA_10. Closing the post!

**Comment by ElCattivo86** [comment]
Didnt want to open a new issue but this change is probably the reason for my problem of the item location not disappearing and i cant find a "Close item location grid" action in the Buttons menu, only an action to show it.

**Comment by lemasato** [comment]
@ElCattivo86 Hey. Just enable this settings, and that'll fix it for now.
![image](https://user-images.githubusercontent.com/14184969/60771531-da315100-a0e9-11e9-8ec8-a3ee4b0b019e.png)
