### ISSUE TITLE
last digit of price not showing up

### ISSUE THREAD

**Issue by nahana78** [lemasato/POE-Trades-Companion#232]
Hi there, after an update today, last digit does not show up.
for example if someone is selling for 12ex, interface show up says 1ex.
![1](https://user-images.githubusercontent.com/51951726/59765271-d3d16580-92f1-11e9-956a-ee1149485468.jpg)

**Comment by lemasato** [comment]
Hey, is this still happening as of 1.15.BETA_10?
If so, please try again and message yourself afterwards.

It should look like this:
![image](https://user-images.githubusercontent.com/14184969/60452118-1ff3a280-9c2e-11e9-9dea-eaa04b1e41b9.png)
