### ISSUE TITLE
error log 

### ISSUE THREAD

**Issue by kanhio** [lemasato/POE-Trades-Companion#233]
Section: SETTINGS_MAIN
Key: TradingWhisperSFXPath
Value: C:\Users\kys\Documents\My Games\Path of Exile\POE-Trades-Companion-AHK-v-1-15-BETA_9\resources\sfx\WW_MainMenu_Letter.wav
Default value: C:\Users\kys\Desktop\POE-Trades-Companion-AHK-v1.15.BETA_1_kr\resources\sfx\WW_MainMenu_Letter.wav

what s meas this error? 
what happen ?

**Comment by lemasato** [comment]
Nothing important.
You moved the folder and so the sound file couldn't be found any-more, therefore you were notified that the value was reset to default.
