### ISSUE TITLE
forced beta update/outgoing whisper interface suggestion

### ISSUE THREAD

**Issue by EThaNol2005** [lemasato/POE-Trades-Companion#234]
Hi, i manuelly downgraded the beta to the lasted stable version but got the beta update again :S 
but i would use the beta if you can added a checkbox for disabling the outgoing whisper interface.
It's too early to use it and has not enough features, like customisation (Custom Text, Buttons)

greetings

**Comment by sicu** [comment]
Just disable it: https://ibb.co/qprzZv1
