### ISSUE TITLE
Bitdefender do every update an disinfection?!

### ISSUE THREAD

**Issue by EThaNol2005** [lemasato/POE-Trades-Companion#238]
Got the ahk version. The tool still work after disinfection. Strange is that i got no log :D
![](https://puu.sh/DNEXm/599863f1c2.png)

**Comment by lemasato** [comment]
Hey,
[[PSA] Anvitirus flagging the POE Trades Companion.exe #124](https://github.com/lemasato/POE-Trades-Companion/issues/124)

And on release page:
> ### Download POE-Trades-Companion-AHK.zip if the executable is being flagged by your antivirus. Extract the zip and run POE Trades Companion.ahk. You do not need to compile the script, you can simply run the ahk file just like you would do with TradeMacro.

> #### If you are still using the exe, please switch to the AHK version instead. Simply download POE-Trades-Companion-AHK.zip from the latest release. The exe is bound to disappear completely in the future due to some stupid recurrent flagging issues.

So yeah, just switch to AHK only :p

**Comment by lemasato** [comment]
Ooo. Nevermind, just noticed you are using the AHK version!
Well, this really shouldn't happen.
Did it only started recently? Does it pinpoint which file is in cause?
The only reason I could see are the compressed League Sheets png files, which I only pushed recently.

**Comment by EThaNol2005** [comment]
> Hey,
> [[PSA] Anvitirus flagging the POE Trades Companion.exe #124](https://github.com/lemasato/POE-Trades-Companion/issues/124)
> 
> And on release page:
> 
> > ### Download POE-Trades-Companion-AHK.zip if the executable is being flagged by your antivirus. Extract the zip and run POE Trades Companion.ahk. You do not need to compile the script, you can simply run the ahk file just like you would do with TradeMacro.
> 
> > #### If you are still using the exe, please switch to the AHK version instead. Simply download POE-Trades-Companion-AHK.zip from the latest release. The exe is bound to disappear completely in the future due to some stupid recurrent flagging issues.
> 
> So yeah, just switch to AHK only :p

i said "Got the ahk version"

**Comment by EThaNol2005** [comment]
> Ooo. Nevermind, just noticed you are using the AHK version!
> Well, this really shouldn't happen.
> Did it only started recently? Does it pinpoint which file is in cause?
> The only reason I could see are the compressed League Sheets png files, which I only pushed recently.

Since 4-5 beta updates.

**Comment by EThaNol2005** [comment]
Still have the problem.

**Comment by lemasato** [comment]
I'd need to know which file exactly is causing the issue.
I tried to scan the AHK zip with the free version of BitDefender, and no result popped up.
The zip doesn't contain any file that I think could be considered as harmful by any protection. The only executable included is curl, which is well known and shouldn't cause issues.

**Comment by EThaNol2005** [comment]
This is the Problem. Bitdefender acting weird... No log entry, only the notification. 

![](https://puu.sh/DUNH2/a893fa5b28.png)

maybe i should reinstall? He don't upgrade to _94 it's stil _92

**Comment by lemasato** [comment]
If you are still on _92, you definitely need to update, but manually.
<https://github.com/lemasato/POE-Trades-Companion/releases>
There's a bug preventing to update in 92 and 93

**Comment by EThaNol2005** [comment]
Don''t know what's the Problem for Bitdefender. I downloaded manually and nothing found. maybe something with the updateroutine? some temp files that get generated?

**Comment by lemasato** [comment]
Probably it doesn't like the fact that the app is downloading something.
Update process goes like this:
Find update > Download zip in /Documents/ > Extract > Delete zip > Overwrite your folder with extracted content > Delete extracted folder > Reload

If you want, I think adding an exception to your Trades Companion folder and to the /Documents/ folder (/Documents/lemasato/POE Trades Companion/) should stop it from scanning.

**Comment by EThaNol2005** [comment]
Nah not only for me, but ty. Maybe clearing old stuff helped now. I'll see next update.

**Comment by EThaNol2005** [comment]
Last update nothing happend.  Maybe cleaning everything up solved it.
