### ISSUE TITLE
[Issue] Foreign names aren't recognized

### ISSUE THREAD

**Issue by noraj** [lemasato/POE-Trades-Companion#239]
Some foreign names like the following one are not parsed and so no notification is shown.

![image](https://user-images.githubusercontent.com/16578570/60616253-574e8480-9dd1-11e9-9c59-8fd17e8415e3.png)

- For issues, make sure to zip and attach your Logs folder:  no log for this event. (default config)

**Comment by lemasato** [comment]
Actually something with the game.
Whispers from Korean aren't being logged, it was discussed here: https://github.com/lemasato/POE-Trades-Companion/issues/236
Soo, sadly nothing I can do

**Comment by noraj** [comment]
@lemasato My bad, The title of issue #236 was not explicit, it may be renamed.
