### ISSUE TITLE
Feature Request: Customize "ty!"-Text of Buying interface

### ISSUE THREAD

**Issue by MasterOfBytes** [lemasato/POE-Trades-Companion#240]
Just a simple Text-Edit in the Settings where you can edit the Text.
( I don't like the short "ty". Editing the Source to Thank You after every Update )

**Comment by lemasato** [comment]
Yup, customisation will come in a future update. Not exactly soon though, there are a few other things I'd like to work on before.

**Comment by DonTheGreatOne** [comment]
I would like to add my support for this upgrade. I would like to be able to customize the buy interface. I am getting around the thank you issue right now with a hotkey. But in addition to that I would either like to be able to add buttons or have buttons for such things as whois and to resend my buy message.

**Comment by Pegoth** [comment]
If you use the ahk version just modify lib\Class_GUI_TradesBuyCompact.ahk line 708 (or search for "ty!" in the file).

**Comment by lemasato** [comment]
But keep in mind that you'll have to do this manual change every update.
Customisation should come with the next "big" update though!

**Comment by DonTheGreatOne** [comment]
Thanks for the info. I look forward to the update

**Comment by JusKillmeQik** [comment]
bumping this as its a feature I'd still like to see

**Comment by lemasato** [comment]
In the works, and already available in the alpha release from discord :p 
I don't really recommend using it though, as it's only for testing purposes.

**Comment by ASprengle** [comment]
Looking forward to this update! There are a number of customized buttons I'd like to be able to add, similarly to the incoming messages window. Things like letting sellers know I found one elsewhere, asking to be reinvited (in the case of buying from multiple people at once somewhat unexpectedly), etc.

**Comment by lemasato** [comment]
I'll be closing this issue to keep the issues tab cleaner as those are either already available in the latest ALPHA or on my consider/to-do list.  
If you wish to try it out, the ALPHA is available on the Discord server. Though, it is really only recommended for testings purpose and not meant to be used to replace the latest BETA.
