### ISSUE TITLE
Feature Request: Auto Reply for Tab-Items that get ignored

### ISSUE THREAD

**Issue by MasterOfBytes** [lemasato/POE-Trades-Companion#241]
It would be great if one can automatically send an "Sorry, allready sold" if an Item is ignored for the next X minutes.
That would be much friendlier to the clients :)

**Comment by lemasato** [comment]
Sadly can't. Could be considered as botting.
You could remove the "Ignore item for 10mins" action, or set-up an hotkey that would answer to the last received whisper with a text that you sold the item.

Though, in the future I think it could be nice to have some indicator that you sold an item with the same name/price/pos recently, for those who aren't using the "Ignore" action.

**Comment by MasterOfBytes** [comment]
That makes Sense. Thanks for your reply.

( And that indicator thing would be great )
