### ISSUE TITLE
Not all messages are catched

### ISSUE THREAD

**Issue by phlawski** [lemasato/POE-Trades-Companion#242]
Hi

I'm on latest beta release and I see that some messages are not catched by the app. I have no idea what search engine they're using but seems that all not catched messages are coming from Korean users. I'm attaching screenshot with such a message.
![Path of Exile 7_7_2019 12_09_21 PM (2)](https://user-images.githubusercontent.com/28409/60766931-8b1afa00-a0b0-11e9-8a6b-0df076c200e4.png)

**Comment by lemasato** [comment]
Hey. Sadly nothing I can do about.
Whispers coming from users using Kakao (Korean accounts) are not logged in Client.txt, and so trading tools have no way to acknowledge them.

 Whispers not being logged in Client.txt #236
