### ISSUE TITLE
Overlay stays after trade

### ISSUE THREAD

**Issue by Ploxl** [lemasato/POE-Trades-Companion#244]
[Logs.zip](https://github.com/lemasato/POE-Trades-Companion/files/3385939/Logs.zip)

Using the latest beta version after every trade, the boxes showing item location stay after completing the trade (clicking thanks or closing with the cross). They stay until i alt tab to another screen then they dissappear.

See this screenshot. Trade is fully completed yet overlay lingers

![ptc_overlay_bug](https://user-images.githubusercontent.com/44341171/61119624-892fad00-a49b-11e9-874b-585ab525cf5a.png)

**Comment by lemasato** [comment]
Hey, see this: https://github.com/lemasato/POE-Trades-Companion/issues/231#issuecomment-509015423 as a temporary fix until the next update is available

**Comment by lemasato** [comment]
Pushed the update! Sorry for the delay.
Originally, it was supposed to be pushed about ten days ago...

https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.15.BETA_92
