### ISSUE TITLE
Can't select a custom button for a hotkey if the start of its name is the same as an existing action

### ISSUE THREAD

**Issue by MarkKoz** [lemasato/POE-Trades-Companion#245]
Reproduction:

1. Open Settings -> Customization -> Buttons
2. Rename _Ask to wait_ to _Wait_
3. Go to Settings -> Hotkeys -> Basic
4. In an empty slot, try to select _Wait_ under _Custom Buttons_.

Instead of _Wait_ remaining selected, the selection will quickly be switched to _Wait {X} milliseconds_. If the button is renamed to something not conflicting, the hotkey selection will actually update to correspond to the new name. So it seems to be selecting the correct button but just displaying the wrong name.

[Logs.zip](https://github.com/lemasato/POE-Trades-Companion/files/3393922/Logs.zip)

**Comment by lemasato** [comment]
It's an issue with AHK where it selects the first match that contains the string, instead of looking for an exact match.
I'll have to look for a proper fix for this.

**Comment by lemasato** [comment]
I'll be closing this issue to keep the issues tab cleaner as those are on my consider/to-do list. A page will be opened with future possible updates.
