### ISSUE TITLE
[QUESTION/SUGGESTION] ChatScanner

### ISSUE THREAD

**Issue by DSDV** [lemasato/POE-Trades-Companion#246]
Hello,

i use Mercury Trade for long time now but it seems not to be updated any longer and often bugs out. ( https://github.com/Exslims/MercuryTrade )

I find you new take (especialy without javaBS) very appeling.
One feature i miss is the chatscanner

it seems to be a basic implementation since i guess you scan the chat anyway for whispers.
is it possible to get this feature in the future?

with kind regards

**Comment by lemasato** [comment]
I have this side-tool [POE-Keyword-Notifier](https://github.com/lemasato/POE-Keyword-Notifier) that does chat notifications. I had plans to update it, but that never happened. I'll most likely add it *(in an improved form ofc)* to Trades Companion in the future.

**Comment by DSDV** [comment]
Nice to heat :)
that would make a perfect package for me.
And finaly get rid of java

**Comment by tonpix** [comment]
I concur! Chat scanner like in Mercury Trade would make me switch to your app (I badly wish for grid locating maps in map tab)

**Comment by Poddi** [comment]
Hey
I also was using MercuryTrade before but its no longer maintained and the only Reason i was still using it was,because it had the chat scanner for specific Keywords included.If i wanna do a Rota or looking for exp leech grp i only had to wait till the app pops up and hit the whisper button.Also useful if searching for various Challenges and so on.Cant live without that.Happy to see i'm not the only one.Would be nice to see it in your App as well :)
Greets

**Comment by lemasato** [comment]
I'll be closing this issue to keep the issues tab cleaner as those are on my consider/to-do list. A page will be opened with future possible updates.

**Comment by DSDV** [comment]
Hi guys :) 
since MercuryTrade is no longer updated i wanted to ask again for a status on the Chatscanner <3
https://github.com/Exslims/MercuryTrade/releases

would love to donate a little if it helps the feature

**Comment by lemasato** [comment]
Honestly I'm not too sure if that'll ever happen.
Development has slowed down quite a lot, and if anything my main goal right now is to finally finish and push the Discord Alpha as a stable release, to finally get rid of all this "Stable"/Beta/Alpha confusing mess.

**Comment by DSDV** [comment]
Oh :( 
that is super sad to hear!
it is the"one" missing feature since its not only good for trading but also for the help chat like shared trials etc. 

would a little donation help to lift the implementation?
