### ISSUE TITLE
Has this worked for anyone in Blight League?

### ISSUE THREAD

**Issue by idSmoker** [lemasato/POE-Trades-Companion#249]
Haven't had this work correctly since the start of Blight.

**Comment by lemasato** [comment]
Seems to work just fine.
Make sure to have reloaded the app since the league start, so that it can retrieve the league names from the API.
Also make sure to be using the latest BETA.

There will be a small update a bit later to include the new map positions in the map stash tab, and include the league name to the league list, in case the api is slow.

**Comment by lemasato** [comment]
Also could be that you're receiving whispers from Korean accounts (See #236)
To make sure this isn't the issue, you can whisper yourself from poe.trade, or make sure that the whisper is being logged in your Client.txt file.

**Comment by melink14** [comment]
I had this probably as well, but it does seem that reloading helped.

**Comment by tonytamps** [comment]
I can't update and some whispers don't trigger it. Worked about 80% of the time for me so far. Whenever I try to update though it downloads, restarts and the old version is still shown.

**Comment by lemasato** [comment]
@tonytamps Bug from an old beta. You need to manually update :/

**Comment by tonytamps** [comment]
Yeah was going to do that sometime today. Cheers.

**Comment by JusKillmeQik** [comment]
It sort of works, when I try and change tabs or when I close a tab, it freezes for a few seconds. I'm not sure what could be causing this. I'm completely up to date on the newest BETA.

**Comment by lemasato** [comment]
@JusKillmeQik Are you using the executable?
If so, I would definitely recommend switching to the AHK instead.
Also, if possible, please include your Logs folder zip.
`\My Documents\lemasato\POE Trades Companion\Logs`

**Comment by LillieSatou** [comment]
Works here, however, Vagan's data needs to be updated within the Betrayal cheatsheet, since he was Revamped with Legion stuff. :)
