### ISSUE TITLE
[🔥] Fixed broken url "pre-release"

### ISSUE THREAD

**Issue by mrG0bliN** [lemasato/POE-Trades-Companion#250]
#### OLD: 
https://github.com/lemasato/POE-Trades-Companion/releases/download/1.15.BETA_96/POE-Trades-Companion-AHK-v-1-15-BETA_97.zip

### FIXED:
 https://github.com/lemasato/POE-Trades-Companion/releases/download/1.15.BETA_97/POE-Trades-Companion-AHK-v-1-15-BETA_97.zip

**Comment by lemasato** [comment]
Oh true. Changed it now.
Thank you for noticing!

**Comment by mrG0bliN** [comment]
> Oh true. Changed it now.
> Thank you for noticing!

"commented 40 seconds ago" -- wow it's too fast :D
