### ISSUE TITLE
Price checker is getting it backwards

### ISSUE THREAD

**Issue by gvieiraaa** [lemasato/POE-Trades-Companion#252]
The correct ratio on poe.trade is 203:21

If the person edits the message to get more currency (basically trying to scam me), the program says that it's a better ratio for me, and it's not. If it's a better ratio for me, it says its a worse ratio.

[image](https://user-images.githubusercontent.com/4547824/64745949-2fba1d80-d4e0-11e9-8750-c101ec30af93.png)

![image](https://user-images.githubusercontent.com/4547824/64746008-6132e900-d4e0-11e9-8aa9-f4388b1fa5af.png)

**Comment by lemasato** [comment]
Fixed as of BETA_990.
Thanks for the report, and sorry this happened.
