### ISSUE TITLE
1.15.BETA_991 no trades inc. 

### ISSUE THREAD

**Issue by EThaNol2005** [lemasato/POE-Trades-Companion#259]
Checked client.txt
Whispers are logged.

**Comment by lemasato** [comment]
None at all? 
Even if you whisper yourself from poe.trade? (make sure to be logged on the same char you are whispering)

**Comment by EThaNol2005** [comment]
None at all. Checked again by whispering myself.
As i said Client.txt whispers are logged

**Comment by lemasato** [comment]
Can you zip your Logs folder from \Documents\lemasato\POE Trades Companion\Logs?

**Comment by EThaNol2005** [comment]
[Logs.zip](https://github.com/lemasato/POE-Trades-Companion/files/3659399/Logs.zip)

**Comment by EThaNol2005** [comment]
He even not register that player joining area.

**Comment by lemasato** [comment]
Are you using any launch parameters?
When starting the tool, do you get any notification about "monitoring logs from folder xxx"?

**Comment by EThaNol2005** [comment]
"D:\progs\Spiele progs\Path of Exile\POE-Trades-Companion\POE Trades Companion.ahk" /NewInstance /GameFolder="C:\Steam\SteamApps\Common\Path of Exile" /InstanceName="Steam" /GameFolder="C:\Steam\steamapps\common\Path of Exile"

**Comment by EThaNol2005** [comment]
"D:\progs\Spiele progs\Path of Exile\POE-Trades-Companion\POE Trades Companion.ahk" /NewInstance /GameFolder="C:\Steam\SteamApps\Common\Path of Exile" /InstanceName="Steam"

**Comment by lemasato** [comment]
Thanks, I'll do some testings with that and see how it goes.

If you start the tool without any parameters, does it work?

**Comment by EThaNol2005** [comment]
> If you start the tool without any parameters, does it work?

yes

**Comment by EThaNol2005** [comment]
i worked with the instance cause i run steam and standealone at the same time

**Comment by lemasato** [comment]
It's been a few updates, but the tool can now monitor multiple folders at once.
If for example your Standalone client is in `C:\Games\POE` and your Steam client is in `C:\Games\Steam\...\POE`, then the tool will automatically detect all whispers from both folders.

Still, running two different TC instances can be convenient to know exactly which whisper was sent to which instance.

**Comment by EThaNol2005** [comment]
> Still, running two different TC instances can be convenient to know exactly which whisper was sent to which instance.

Yes, i run on tc each Monitor, so i can see which on get whispered

**Comment by lemasato** [comment]
Pushing the update now, thank you for reporting!
