### ISSUE TITLE
Game switches into window mode from fullscreen when a trade is detected

### ISSUE THREAD

**Issue by 99TonyStark99** [lemasato/POE-Trades-Companion#263]
Very annoying, causes death like well right away while windoze does it's blinking screen change thing.  please for the love of PoE, fix this!
And I have trade companion on the primary screen, PoE fullscreen mode on the secondary screen

**Comment by lemasato** [comment]
Hi,
You have to play on borderless.
Fullscreen mode cannot work with third-party tools, as they aren't being injected into the game process.

**Comment by 99TonyStark99** [comment]
Trade companion is on my main screen(not the one i'm using to play PoE in fullscreen.)  It interrupts the game to pop up a notification on the secondary screen(which has PoE in full screen)Is there any way to just turn off these popups? then it will function like last year sometime. Also, it seems to minimise the TC window to a small bar when this happens(which is on the main screen) 
this is extremely frustrating!

**Comment by 99TonyStark99** [comment]
Oh, and I have all the buttons on the TC window mapped to function keys s o I don't have to press them by switching to windowed mode(which drops my FPS by 60%)

**Comment by lemasato** [comment]
To be honest, the tool was never really compatible with fullscreen. Only borderless can be supported.

I read something similar on the TradeMacro discord. The script used to work fine in fullscreen for the two previous league, but it doesn't anymore.
If there are things that used to work and don't anymore, then it's likely to be related to a Windows Update.

**Comment by 99TonyStark99** [comment]
I'm fairly certain this is not a windows update related issue, I'm running stock win7 ultimate/sp1, and have never done windows updates on it.

Trademacro has been fine, I have the positions set so the iteminfo etc. appears on the screen I'm not using for PoE. The only time it's a hassle is with advanced search, (which I rarely do.) The mode switch isn't really an issue there since I only advanced check prices in my hideout

**Comment by lemasato** [comment]
Hi,
Sorry for delayed answer (was unavailable until now).

POE Trades Companion was never really designed to work in fullscreen (Overlay apps usually do not work in fullscreen). I'll see what I can do about this, but I can't promise anything.

**Comment by ChrisLovering** [comment]
The only way you'd be able to do this would be to inject some custom interface logic into the graphics dll. There's no other conceivable way since you need to hijack the graphics device that belongs to that game.

I'm pretty sure this would also be against ToS.
