### ISSUE TITLE
Trade GUI invalid value for StartColor

### ISSUE THREAD

**Issue by Neoakb** [lemasato/POE-Trades-Companion#264]
[GUI_Trades] hBTN_TabDefault1: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabJoinedArea1: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabWhisperReceived1: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabDefault2: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabJoinedArea2: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabWhisperReceived2: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabDefault3: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabJoinedArea3: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabWhisperReceived3: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabDefault4: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabJoinedArea4: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabWhisperReceived4: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabDefault5: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabJoinedArea5: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabWhisperReceived5: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabDefault6: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabJoinedArea6: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabWhisperReceived6: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabDefault7: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabJoinedArea7: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabWhisperReceived7: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabDefault8: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabJoinedArea8: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabWhisperReceived8: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabDefault9: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabJoinedArea9: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabWhisperReceived9: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabDefault10: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabJoinedArea10: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabWhisperReceived10: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabDefault11: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabJoinedArea11: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabWhisperReceived11: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabDefault12: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabJoinedArea12: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabWhisperReceived12: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabDefault13: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabJoinedArea13: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabWhisperReceived13: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabDefault14: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabJoinedArea14: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabWhisperReceived14: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabDefault15: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabJoinedArea15: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabWhisperReceived15: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabDefault16: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabJoinedArea16: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabWhisperReceived16: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabDefault17: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabJoinedArea17: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabWhisperReceived17: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabDefault18: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabJoinedArea18: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabWhisperReceived18: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabDefault19: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabJoinedArea19: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabWhisperReceived19: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabDefault20: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabJoinedArea20: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_TabWhisperReceived20: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_Special1: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_Special3: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_Special4: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_Custom3: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_Custom2: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_Custom1: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_Custom6: Invalid value for StartColor in Options[1]!
[GUI_Trades] hBTN_Custom4: Invalid value for StartColor in Options[1]!

**Comment by lemasato** [comment]
Hi,
Sorry for delayed answer (was unavailable until now).

Most likely an issue with your settings.
If you are using a "Custom" preset, I'd recommend switching back to one of the default ones so that you may start fresh. Otherwise, by sharing your logs file I would be able to tell you which setting (in the .ini file) is messing up and how to fix it.

**Comment by Neoakb** [comment]
I reinstalled from scratch and that fixed it.

Thanks
