### ISSUE TITLE
Suggestion Item Grid Overlay

### ISSUE THREAD

**Issue by Odin099** [lemasato/POE-Trades-Companion#265]
Is it possible to change the item grid overlay?
i wannt have a different color and a wider frame.
sorry if it is the wrong area i am not familiar with github

**Comment by lemasato** [comment]
Hi,
Asking question here is just fine!
Sorry but currently the tool doesn't offer possibilities to change square color or width.

If you're familiar enough with AHK, you could take a look at Class_GUI_ItemGrid.ahk
Specifically at the `squareColor` and `gridThicc` variables

**Comment by Odin099** [comment]
ty for the fast answer
i am just a bit familiar with programming but i will take a look into it
