### ISSUE TITLE
how do u capture displayed text

### ISSUE THREAD

**Issue by Conversage** [lemasato/POE-Trades-Companion#269]
Hi,
i really like your Trade Companion!

I am currently writing a java programm for poe myself and i was wondering if u could give me any advise on how to capture the displayed text per image scraping if u dont use Client Log.

My Programm is just an anti scam tool which is supposed to check if the trade is correct.

best regards 
Nils

**Comment by lemasato** [comment]
Hi,
Trading whisper infos are read from the Client.txt file.
This is the only way the game provide us (legally).
