### ISSUE TITLE
how uptodate are the cheatsheets for Betrayal etc?

### ISSUE THREAD

**Issue by Smeagol001** [lemasato/POE-Trades-Companion#270]
i would loke to point out that maybe the info for your cheatsheets may be outdated 
https://preview.redd.it/taiv2uxbkym31.png?width=960&crop=smart&auto=webp&s=f32c0e730c5dc1e0f66d1f2730d117a404d66e75 
indicates that your info may be old so i gues that can be applied to all info you provide

**Comment by lemasato** [comment]
You can change cheatsheets by replacing the files in /POE Trades Companion/resources/cheatsheets/
But it'll have to be done every time that the tool is updated.
Cheat sheets do not support custom sheets as of now, but will be added in the future.

If you have other cheatsheets that you feel like are more up-to-date, please let me know about it :p

**Comment by jevonsp** [comment]
Hey, I really like making cheat sheets and would love to supply some info for nice, easy-reference sheets for betrayal, temple rooms etc

I wanted to learn how to use xml with spreadsheets for another guide, might be useful for updating sheets based on poe.ninja values

**Comment by lemasato** [comment]
@jevonsp League sheets that are updated automatically based on the current market value would be very useful, everyone in the POE community would be happy about it.

I'll be closing this issue to keep the issues tab cleaner as the Betrayal leaguesheet has since been updated.
