### ISSUE TITLE
Is it possible to show buy interface ONLY when the seller's invite is presented?

### ISSUE THREAD

**Issue by laststoneleft** [lemasato/POE-Trades-Companion#272]
- For issues, make sure to zip and attach your Logs folder:  
/Documents/lemasato/POE Trades Companion/Logs  

- For questions, make sure to check the README on the [project page](https://github.com/lemasato/POE-Trades-Companion) and the [Wiki](https://github.com/lemasato/POE-Trades-Companion/wiki)  
If you haven't found an answer, it is really fine to post an issue to ask about it  
Though, the quickest way would be to directly ask on the [Discord](https://discord.gg/UMxqtfC)

**Comment by laststoneleft** [comment]
I'd like to see the buy interface when someone actually invited me, not before.

**Comment by lemasato** [comment]
Can't. We don't have access to party invites notifications, as they are not logged in Client.txt.

**Comment by laststoneleft** [comment]
How can I set the %buyer% variable manually?

**Comment by lemasato** [comment]
%buyer% entirely depends on the slot owning the button, it cannot be set manually
