### ISSUE TITLE
[Feature] trade button on outgoing interface

### ISSUE THREAD

**Issue by JusKillmeQik** [lemasato/POE-Trades-Companion#273]
Once they send me an invite I can click the house button to go to their hideout, but then I have to wait for them to send me a trade notification or do it manually. Being able to hop in and then hit "trade" to start the process would be nice.

**Comment by jevonsp** [comment]
Just came here to add this request! Would be great, loving this tool as a Mercury Trade Supplement (still using it for the flask overlay and DND buttons)

**Comment by lemasato** [comment]
Customization for buying interface is already part of next update.
