### ISSUE TITLE
Interface not remembering position (?)

### ISSUE THREAD

**Issue by Smeagol001** [lemasato/POE-Trades-Companion#274]
everytime i get a whisper the window with the  trade  thankyou etc buttons semms to popup  not at the position i configured it to and whei i use the window the transparent part of the window is in a weierd way  despit having locked it in place

**Comment by lemasato** [comment]
Hi,
Sorry for the late reply.
Could you provide a video to showcase these?

**Comment by Smeagol001** [comment]
hard to capture cause iits occurring randomly  and i dont have a
videdocapture running all thetime -.-

Am Mi., 12. Feb. 2020 um 02:23 Uhr schrieb masato <notifications@github.com

**Comment by lemasato** [comment]
Sorry, I thought it was happening constantly or would be simple to reproduce.  
If you have a NVIDIA GPU that is compatible with GeForce Experience Instant Replay, you could use that to record the last minute when the bug happens.  

Additionally:  
- First, make sure you're using the latest BETA

- Which interface does it happen to?
Selling interface is the one that appears when you receive a whisper
Buying interface is the one that appears when you send a whisper

- How much is it moving? Is it only a few pixels away? Or to a specific position?
- Is it always moving exactly in the same way, or does it seem unpredictable?

> the transparent part of the window is in a weierd way 

- This one especially is quite confusing to understand. If not a video, then could you provide a screenshot?
