### ISSUE TITLE
Option to auto maximize on all new tabs

### ISSUE THREAD

**Issue by ASprengle** [lemasato/POE-Trades-Companion#276]
When mapping, I like to respond to trade requests with a whisper telling them I'm in a map and will get back to them, followed by minimizing the window. It would be great to have the window maximize for all new tabs so I can do the same thing with those people.

At the moment, my two current options are to either leave the window maximized through the whole map or maximize the window manually for ever buyer beyond the first.

P.S. Thanks for the great program!

**Comment by lemasato** [comment]
You could have the "Auto focus new tabs?" option enabled and bind an hotkey to your "I'm in a map" button. Then press it upon receiving a new whisper.
