### ISSUE TITLE
[Feature Request] QoL for Buyer side.

### ISSUE THREAD

**Issue by avunaos** [lemasato/POE-Trades-Companion#278]
Hello! The selling aspect of this companion is awsome, but the buyer could get some love too, here are some ideas:

Being able to sort buy tabs from bottom up.
Being able to edit buying responses
Being able to combine both windows into 1 for easy screen space management.

**Comment by lemasato** [comment]
Hi!

> Being able to sort buy tabs from bottom up.
Being able to edit buying responses

The latest ALPHA update (available on Discord) offers a solution for these.

>  Being able to combine both windows into 1 for easy screen space management.

As of this one, I considered it and still have to see how it would work out.

**Comment by lemasato** [comment]
I'll be closing this issue to keep the issues tab cleaner as those are either already available in the latest ALPHA or on my consider/to-do list.  
If you wish to try it out, the ALPHA is available on the Discord server. Though, it is really only recommended for testings purpose and not meant to be used to replace the latest BETA.
