### ISSUE TITLE
Map Tab Change

### ISSUE THREAD

**Issue by TheOne320** [lemasato/POE-Trades-Companion#280]
Please adjust the map location markers for the new map tab changes. Thank you.

**Comment by lemasato** [comment]
Screenshot?
The latest update should have disabled the "precise" location for non-original tiers.

**Comment by TheOne320** [comment]
![image](https://user-images.githubusercontent.com/7705568/73136096-0098e880-404a-11ea-9570-7809859f88be.png)

**Comment by lemasato** [comment]
I'll get it fixed today or tomorrow, thanks for reporting.

**Comment by lemasato** [comment]
I'll be pushing the update now.
I haven't been playing much at all this league (and the few previous ones too), so while this kind of issue is very obvious for active players, I couldn't be aware of it without anyone reporting. Thank you.
