### ISSUE TITLE
ImageButton "Invalid parameter Hwnd"

### ISSUE THREAD

**Issue by Chichigami** [lemasato/POE-Trades-Companion#281]
[Logs.zip](https://github.com/lemasato/POE-Trades-Companion/files/4132783/Logs.zip)

**Comment by Chichigami** [comment]
Just installed trade companion with AHK and I also restarted my computer and I still have this error

**Comment by lemasato** [comment]
Can you paste the message from the box? It's not logged in the files.

**Comment by Nyab59** [comment]
[GUI_TradesBuyCompact_Slot11] hBTN_WhisperSeller: Invalid parameter HWND!

---
I'm not the original poster. But I keep getting something like this.
Error message is not always the exact same, but always says "Invalid parameter HWND!".

If I restart the PC, the first boot of POE Trade Companion has no problem.
But on the second boot of POE Trade Companion (or reload script), similar message appears again.

---

Windows 10

**Comment by lemasato** [comment]
Strange it would happen specifically to that button only.  
It's not too much of an issue, since only the appearance of the button will be affected.

I'll be pushing a small update tomorrow to disable the warnings from the window, and just log them instead. I think that's already how it works in the alpha anyway.

**Comment by Nyab59** [comment]
Thank you for the response.

Here are some message variations.

[GUI_Trades] hBTN_TabDefault7: Invalid parameter HWND!
[GUI_Trades] hBTN_TabWhisperReceived12: Invalid parameter HWND!
[GUI_Trades] hBTN_LeftArrow: Invalid parameter HWND!
[GUI_Trades] hBTN_TabDefault14: Invalid parameter HWND!
[GUI_Trades] hBTN_TabJoinedArea20: Invalid parameter HWND!
