### ISSUE TITLE
Cheatsheet options

### ISSUE THREAD

**Issue by ZzZombo** [lemasato/POE-Trades-Companion#282]
The feature is very nice! But I'd say its usefulness is diminished by the fact they obscure all your screen, so you have to bounce back and forth between the game and cheatsheets.

* Make them semitransparent with customized level of opacity.
* Make them click-through. Make them close on Esc.

Additionally, I can't seem to be able to summon them via hotkeys. I bound one with "Show League cheatsheet" as an action, but nothing comes up.

**Comment by joe7dust** [comment]
> 
> 
> The feature is very nice! But I'd say its usefulness is diminished by the fact they obscure all your screen, so you have to bounce back and forth between the game and cheatsheets.
> 
>     * Make them semitransparent with customized level of opacity.
> 
>     * Make them click-through. Make them close on Esc.
> 
> 
> Additionally, I can't seem to be able to summon them via hotkeys. I bound one with "Show League cheatsheet" as an action, but nothing comes up.

This feature is still usable? Mine only shows 4 previous leagues not the current one.

**Comment by lemasato** [comment]
@ZzZombo The leaguesheet menu will have a complete overhaul in the future.  
Something about allowing personal sheets pngs + making it prettier and user-friendly.  
If you bound an hotkey to the league sheets action, make sure that it is enabled. Basic hotkeys will stay disabled if you don't tick the corresponding checkbox next to them.

@joe7dust Some leagues do not have any league sheet. They are made by the community, I only include them here.

**Comment by lemasato** [comment]
I'll be closing this as it's on my to-do list.  
Transparency and click-through will be considered during the LeagueSheets Overhaul update. Close on ESC will be added in a small update coming later.
