### ISSUE TITLE
InstantWhisper not working with official website (?)

### ISSUE THREAD

**Issue by joe7dust** [lemasato/POE-Trades-Companion#283]
There always seem to be a huge delay on poe.trade and I lose many deals even after clicking near instantly. Several people have informed me the site just doesn't update as often as the real deal and the API.

Could we please get this feature to work with that site or another alternative site to poe.trade?

**Comment by lemasato** [comment]
It should be compatible with poeapp.com, poe.trade and pathofexile.com/trade (all languages). I'll take a look.

**Comment by lemasato** [comment]
Which browser are you using?  
Seems to work just fine with Firefox and Chrome  
https://www.pathofexile.com/trade/search/Metamorph/mw8zC6

**Comment by joe7dust** [comment]
There are some pages on poe.trade where it works with a single control click, and some where you have to click twice and hit control+c. On the official site there is only the worse option, not even 1clickable anywhere that I've found. Firefox 
> 
> Which browser are you using?
> Seems to work just fine with Firefox and Chrome
> https://www.pathofexile.com/trade/search/Metamorph/mw8zC6
