### ISSUE TITLE
all overlays optionable

### ISSUE THREAD

**Issue by 0ldi** [lemasato/POE-Trades-Companion#285]
Can you make an option to disable all of these overlays?
![image](https://user-images.githubusercontent.com/16578229/75060906-b7c13c00-54f0-11ea-87fe-663215d34e8e.png)

On my system, any overlay affects the performance of the game (if it is on the same monitor as the game) with Gsync turned on.
![image](https://user-images.githubusercontent.com/16578229/75061189-4209a000-54f1-11ea-93ee-d5479b3f9fa6.png)
I do not understand why these options for disabling the grid do not work (probably only for my old maps)

**Comment by lemasato** [comment]
They do work.
But blue squares are meant to show map locations for the map stash tab, and there is no option to disable that for now.

Do you have Windows Aero disabled?
On system that have it disabled, games will experience fps drops when there is a window above them (overlays for example).

**Comment by 0ldi** [comment]
Win10x64, rtx2070, last Drivers
27gk750f 240Hz G-SYNC Compatible (main gaming monitor)
27mp75 60Hz (second monitor)

Ok I will give a detailed answer to warn further questions. The main problem is that most games currently in windowed (borderless) with G-sync turned on have a performance problem, unlike real fullscreen mode (everything is just perfect there). But in PoE (at least for me) it's not really possible to play in fullscreen mode. But I found a tool that fix that problem:
https://www.pcgamingwiki.com/wiki/Special_K#Flip_model_presentation
This function solves the problem and performance becomes similar to fullscreen mode, but any overlay completely cancels this effect. Because I always kept the window of your program on Monitor2, everything was fine, only occasionally it caused problems at the bottom right. I have been using version 1.12.5 for a long time, but with each league it is more and more complicated since item data is not updated. Therefore, I ask you to make an option to disable all or at least unmovable from the overlays main monitor.

**Comment by lemasato** [comment]
Nice, that's interesting. So basically it allows you to run on 240hz on borderless games?

It will be quite a while until the next major update is pushed.
So until I can work on a proper solution, I'd recommend you to edit your Class_GUI_ItemGrid.ahk in `/POE Trades Companion/lib/`
[At line 120](https://github.com/lemasato/POE-Trades-Companion/blob/0f6a846f5002a641b679e5108a5f796b2ff3693b/lib/Class_GUI_ItemGrid.ahk#L120), add `return`
It will effectively cancel the whole item grid gui.

**Comment by 0ldi** [comment]
Thank you very much, that was what I needed.
And the notifications on the bottom right are somehow disabled?

**Comment by lemasato** [comment]
That's from another file
TrayNotifications.ahk, [Line 59](https://github.com/lemasato/POE-Trades-Companion/blob/dev/lib/TrayNotifications.ahk#L59), add `return` just like in the previous file

**Comment by HiPoEGH** [comment]
I would make a suggestion that the Item-Grid ONLY shows up when a player gets invited / joins the party.

**Comment by lemasato** [comment]
It used to be like that, but then I changed it. The reason was that you would invite people until you realize that the item has already been sold. Now, the item location grid will only show while the interface is maximized. This allows you to quickly check if an item is still there in case of doubts.
While actively playing, keeping the interface minimized will let the item grid hidden.

**Comment by HiPoEGH** [comment]
Is there any way to only show it on hover?
It's only a minor issue when inside maps and don't want the grid being displayed all the time.
I can try keeping the interfaced minimized on first new tab, but Idk if that will help.
