### ISSUE TITLE
Missing whispers

### ISSUE THREAD

**Issue by feckk** [lemasato/POE-Trades-Companion#287]
Hello,

First of all I would like to thank you for this amazing tool and the effort you put to create it.

I'm having some trouble with companion not detecting some whispers. Mostly coming from Korean players. I'm not sure if it's an issue with the characters or region. I have tried the versions 997 and 996 which I believe are still in BETA.

Could you lead me to a solution?

Thanks!

**Comment by lemasato** [comment]
Hi,
Nothing can be done about it. Any whispers received from players from Kakao are not being logged by the game. More about it can be found [here](https://www.reddit.com/r/pathofexile/comments/c93tvs)

**Comment by feckk** [comment]
Hello @lemasato, thanks for replying so fast. That's really a bummer, but now everything makes sense. 

Have a great Sunday, happy grinding!
