### ISSUE TITLE
Item highlighting is incorrect on currency tab

### ISSUE THREAD

**Issue by dcgaines** [lemasato/POE-Trades-Companion#288]
Not sure if its the new layout with 3.10 or just the currency tab in general but the item highlighting is off. Not a huge deal since there's only really one item slot but thought I'd mention it

**Comment by lemasato** [comment]
Hi,  
Only regular and quad tabs are supported by the item grid.  
Map stash tab used to be supported too, but that has been broken with the blighted maps (tab layout will change based on maps owned). This will be reworked in the future.
