### ISSUE TITLE
Supporting multiple instances

### ISSUE THREAD

**Issue by rushtothesun** [lemasato/POE-Trades-Companion#29]
Is it possible to support multiple instances? Currently if you try to run two of them at the same time, one of them closes. I have another account sitting in my hideout selling cheap items while my main account has the high price items. I'd like to have two trade helpers running at the same time. Can this work?

Edit: Removed Close_Previous_Program_Instance and got two instances to work. It would be neat to have an option allowing this as well as an option to specify paths/settings.

**Comment by lemasato** [comment]
Those could easily be added as command line parameters.  
Great suggestion!

**Comment by lemasato** [comment]
Feature added as 1.9.  
You can use [Command Line Parameters](https://github.com/lemasato/POE-Trades-Companion/wiki/Command-Line-Parameters) to run an alternate instance of the tool.
