### ISSUE TITLE
question on new beta

### ISSUE THREAD

**Issue by joe7dust** [lemasato/POE-Trades-Companion#290]
What does this mean? "Changes:
Added Delirium"

I'm on 997 and I have Delirium in my Stats dropdown...

**Comment by lemasato** [comment]
Leagues are retrieved from the GGG API on application start.  
So as long as the official website is up, the application will know the latest leagues.  Even so, if the official website would be down, the application is still "clever" enough to determine which part of the whisper message should be the league name.  

This change is only a fail-safe precaution. It'll help in case the official website is down and the application failed to determine the league name.

**Comment by joe7dust** [comment]
Cool, thanks for getting back to me. I wanted to ask or suggest something in the past but didn't because some devs don't seem to appreciate "issues" like this one. You seem like one of the good ones though I will probably make another sometime if I remember what it was. :)
