### ISSUE TITLE
Request: Add /whois button to the window when you whisper someone

### ISSUE THREAD

**Issue by Supportic** [lemasato/POE-Trades-Companion#291]
It would be nice if you could customize these buttons like the main trade window with all actions.
Also it's annoying when I click "Ty!" and the window is closing immediately because I have to leave manually the party instead of just clicking the button "Leave" which disappear. 
Or sending the message again button.

**Comment by SirNorek** [comment]
I second all of this. Not sure why we can't customize the sent whispers box in the same way as the incoming. Many little tweaks we would be able to do, I'd prefer the close box be on the leave button, along with auto sending me to my own HO, and change ty to something with a little more personal flair. Everyones different, there is so much customization everywhere else, but this part is completely missing for seemingly no reason?

**Comment by lemasato** [comment]
Will be part of the next major update. #284
