### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by stark2727** [lemasato/POE-Trades-Companion#294]
I'm trying to make my own button. I click on the plus to add and name it but none of the action section does anything. It's alll blank. Even the default one's dont show anything when clicking on them? I'm using the latest beta 998

**Comment by lemasato** [comment]
This may happen sometimes, though I never encountered it personally.
Based on feedback, reloading the application always fixes it and allows you to make new buttons.

**Comment by stark2727** [comment]
The interface for buttons only works once. If I try to apply an action it
might work, but when i try to do anything else the box is blank, even for
preloaded buttons

Best Regards,
Jeremy
