### ISSUE TITLE
Trading messages in some asian languages are not sniffered

### ISSUE THREAD

**Issue by 0ldi** [lemasato/POE-Trades-Companion#295]
Its old bug and i forgot report it before...
Example: 
![image](https://user-images.githubusercontent.com/16578229/77819495-4c204f00-70ec-11ea-95b0-194b96ec1983.png)
and it does not appear in the tool

**Comment by TgDn32** [comment]
This has to do with Korean privacy laws; GGG doesn't save any messages from the Korean client in the client.txt file.

**Comment by lemasato** [comment]
Yep. Nothing that can be done about this.
https://github.com/lemasato/POE-Trades-Companion/wiki/FAQ#nothing-happens-when-i-receive-a-trading-whisper-or-some-whispers-are-ignored-notably-korean-names
