### ISSUE TITLE
Not working with korean characters?

### ISSUE THREAD

**Issue by domagojmedo** [lemasato/POE-Trades-Companion#296]
Every time I get a whisper from someone with korean characters in their name, trade companion doesn't register it

**Comment by lemasato** [comment]
Hi,
It's a limitation by the game, due to Korean privacy laws.
https://github.com/lemasato/POE-Trades-Companion/wiki/FAQ#nothing-happens-when-i-receive-a-trading-whisper-or-some-whispers-are-ignored-notably-korean-names
