### ISSUE TITLE
[Bug] Issues with "~" as hotkey + Suggest staying on green tab colour when buyer whispers you

### ISSUE THREAD

**Issue by 0ldi** [lemasato/POE-Trades-Companion#297]
Sometimes hotkey stops working.
At the same time, entry to options and exit fix it
In this case, variants:
-hotkey area is empty (then I bind it again)
-or it binded (but does not work).
This is of course a minor bug, but it happens 1-5 times a day, which is annoying
Its "~" hotkey
![image](https://user-images.githubusercontent.com/16578229/78454457-bc0c7780-76a0-11ea-9b43-667d43ed92f4.png)

**Comment by 0ldi** [comment]
And 1 inconvenience until I forgot:
when the buyer wrote something to you (purple), when he is in your HO (green)
But in a situation where purple+green displays only purple, and this is inconvenient, you need to close stash and check who exactly have in HO because there is no difference between buyer:
-who just said "already bought" no need
-who in HO and ready to buy, buy PM anything to me

You need to change the color to green or some other color for such buyers

**Comment by lemasato** [comment]
- Could I have your logs file folder? Zip the whole folder and attach it here.
`\Documents\lemasato\POE Trades Companion\Logs`
- In Windows, which keyboard layout are you using?

**Comment by 0ldi** [comment]
> * Could I have your logs file folder? Zip the whole folder and attach it here.
>   `\Documents\lemasato\POE Trades Companion\Logs`
> * In Windows, which keyboard layout are you using?

I do not quite understand about the "layout". I use default ENG (maybe US) QWERTY-layout and second RU localization.
[2020-04-09 14h32m02s.zip](https://github.com/lemasato/POE-Trades-Companion/files/4460568/2020-04-09.14h32m02s.zip)

**Comment by lemasato** [comment]
I'm sure it's related to AHK using the ` character as an escape character.  
I suppose the fix will have to wait until next major update, which improves the hotkey system quite a bit.

**Comment by lemasato** [comment]
The fix will be part of the next Discord ALPHA update (currently ALPHA_6, fix will be in ALPHA_7)
Thank you for reporting!

**Comment by 0ldi** [comment]
I don’t know which of ALPHA now, because you do not use this in the name "1.15.BETA_9991", but it is still not fixed. And some of the Asian trades still don't appear in Companion.

**Comment by lemasato** [comment]
It'll be part of ALPHA_7, which isn't available as of now.  
I cannot push the fix onto BETA as it would be too much work to adapt it. Everything has seen lots of changes since ALPHA updates.
