### ISSUE TITLE
Pushbullet notifications not sending for English messages

### ISSUE THREAD

**Issue by VicePrez** [lemasato/POE-Trades-Companion#298]
Pushbullet notifications stopped working as of last Friday. I tried resetting the access token to see if that helped - still not working. Any advice on how to resolve this would be appreciated :)

**Comment by lemasato** [comment]
Hi,
Most likely you hit your max limit.
Free pushbullet accounts have had restrictions since a few years ago.
Nothing that I can do about it personally. I've been looking for fully free alternative, but there aren't any that I'm aware of.

**Comment by VicePrez** [comment]
Confirmed to be the issue. Thank you. Have you looked into hooking onto Telegram API? It supports push notifications, end to end encryption, etc.

**Comment by mynameislincks** [comment]
Oh, I was wondering what happened to my Pushbullet notifications, thought it had something to do with last update, but now I know why haha
It's a very useful feature for an already great tool
