### ISSUE TITLE
Overlay not working with new Vulkan renderer

### ISSUE THREAD

**Issue by Versalkul** [lemasato/POE-Trades-Companion#299]
Overlay not displaying in borderless fullscreen when the new Vulkan(Beta) renderer is enabled

**Comment by lemasato** [comment]
Hiya, this is an issue with the game itself.  
While using Vulkan, "Windowed fullscreen" is actually 100% fullscreen and not windowed. This is an issue with their implementation, that I believe they will fix eventually. I'd recommend playing "Windowed" or reverting back to DirectX

**Comment by lemasato** [comment]
Hi, I made a script to work around this issue: [here it is](https://www.reddit.com/r/pathofexile/comments/gseuoy/vulkan_test_technical_megathread/fs6tie9/)
