### ISSUE TITLE
Vulkan Renderer support

### ISSUE THREAD

**Issue by mynameislincks** [lemasato/POE-Trades-Companion#301]
Hi, since the last update that introduced the Vulkan renderer, while using it the overlay doesn't appear on windowed fullscreen mode.
![Base Profile Screenshot 2020 05 30 - 18 09 45 68](https://user-images.githubusercontent.com/32848598/83339116-e6de0b00-a2a0-11ea-826c-d389147b0e76.png)

[lemasato.zip](https://github.com/lemasato/POE-Trades-Companion/files/4706494/lemasato.zip)

**Comment by lemasato** [comment]
Hi, #299
