### ISSUE TITLE
Item Name and Stash Tab shows even when location is disabled

### ISSUE THREAD

**Issue by esfdk** [lemasato/POE-Trades-Companion#303]
Hello!

The grey boxes with item name and stash tab is still shown even if normal, quad and map tab locations are disabled.

A simple fix appears to be to just do the following in Class_GUI_Itemgrid.ahk, but there is probably a much better way to do it. 

`if(hideNormalAndQuadTabsForMaps="True" && hideQuadTab="True" && hideNormalTab="True") 
			return`

**Comment by lemasato** [comment]
This kind of is intended, as the checkboxes are only meant to disable the item location itself. But I'll keep this open in case I ever add more options to the "item location grid" feature
