### ISSUE TITLE
More custom options for Outgoing trade messages to sellers.

### ISSUE THREAD

**Issue by HiPoEGH** [lemasato/POE-Trades-Companion#305]
Hello, Love the script.
I'd love to be able to customize **Outgoing trade messages** and buttons. (Pretty much the exact same as the inbound messages)
If you've ever used mercury trade, you have an idea of what I'm talking about.

I'd love to have the option to send custom messages / buttons, buttons for invite seller, trade with seller, go to sellers hideout, customize the thanks message, /whois, etc.

_Also I have UI issues I'd like addressed with settings options but that can wait for another thread._

**Comment by lemasato** [comment]
Hi,
This is currently only available on the [Discord alpha](https://discord.gg/UMxqtfC). You might want to check it out.
It mostly consists of a Settings UI and Buying/Selling UI rework.

**Comment by lemasato** [comment]
<details>
<summary>Here are some gif previews I just made (click to show):</summary>

![TC Settings](https://user-images.githubusercontent.com/14184969/86537333-b10af280-beee-11ea-888f-a42a2a9ebf5d.gif)
![TC Settings Skin Preview](https://user-images.githubusercontent.com/14184969/86537334-b36d4c80-beee-11ea-8e2d-5042acf7d381.gif)
![TC Settings Buying Custom](https://user-images.githubusercontent.com/14184969/86537336-b49e7980-beee-11ea-98f5-d723a36084c5.gif)

</details>
