### ISSUE TITLE
Resend Buy Request

### ISSUE THREAD

**Issue by ggurman** [lemasato/POE-Trades-Companion#307]
Someone else suggested a message timer. I like that idea, and I think it's related to my suggestion.

I'd like a way to re-send a request once after a reasonable amount of time--maybe 5 minutes (I don't want to spam or nag the seller). 

Maybe this is too complicated, but I figured it was worth mentioning.

Thanks!

**Comment by lemasato** [comment]
This is available in the current Discord ALPHA in the form of a Trading Variable. If you wish to try out the ALPHA, [this is the invite link](https://discord.gg/UMxqtfC).
I'll be closing this to keep the issues about current ongoing issues/wip.

![image](https://user-images.githubusercontent.com/14184969/87829717-dbaa6300-c87f-11ea-85b0-c60a9dd57a50.png)
