### ISSUE TITLE
I can't run Poe Trade Companion after new update

### ISSUE THREAD

**Issue by kaoen9** [lemasato/POE-Trades-Companion#308]
![mTNTp6p](https://user-images.githubusercontent.com/68604486/88074420-af406080-cb77-11ea-855b-50d5d0648877.png)

**Comment by lemasato** [comment]
- For issues, make sure to zip and attach your Logs folder:  
/Documents/lemasato/POE Trades Companion/Logs

**Comment by kaoen9** [comment]
But this folder is empty so i can't attach that.

**Comment by lemasato** [comment]
Makes sense, my bad. Is that your first time running TC ever?
In your \POE-Trades-Companion\resources\translations, what files do you have?

**Comment by kaoen9** [comment]
![PxHD1la](https://user-images.githubusercontent.com/68604486/88078153-663edb00-cb7c-11ea-8869-b54debbf50a7.png)
I used TC but i'm trying to fresh install new version because i can't auto-update older version - error and after this it happened.

**Comment by lemasato** [comment]
Can you send your \lemasato\POE Trades Companion\Preferences.ini file?

**Comment by kaoen9** [comment]
In documents i have only empty catalogues. I dont know why maybe it is a problem but what can i do to force your program to create this files. There is no instalation, only unzip ".zip" file?

**Comment by lemasato** [comment]
Trades Companion creates everything automatically, no need to force it.
You don't have any Preferences.ini file? If you have multiple users on your computer, try checking other users MyDocuments folders.

**Comment by kaoen9** [comment]
I have only one user on my computer and there is any Preferences.ini file in documents/lemasato/Poe Trades Companion/

**Comment by lemasato** [comment]
Strange. I guess it's some system specific oddities. Here's the default Preferences.ini file: [Preferences.zip](https://github.com/lemasato/POE-Trades-Companion/files/4955632/Preferences.zip) - Extract the zip and place the file in the correct location, and that should work.

**Comment by kaoen9** [comment]
Yes, that's working but now i can't change any settings but i guess i should change manually preferences.ini. Maybe its antivirus problem but i didn't see any notification or something...

**Comment by lemasato** [comment]
Sounds like a file access issue or something. Could be related to antivirus. But I'd also recommend making sure your Windows is fully up to date, it can help too. Or maybe reinstalling AHK and making sure it's Unicode 64, or using the executable to see if it helps... Sorry I don't think I can help much in this case :/

**Comment by kaoen9** [comment]
'exe" file is working and i can finally change my settings. Thank you so much for helping and great trade tool :) Have a good day.
