### ISSUE TITLE
Error when clicking the ty! button after buying

### ISSUE THREAD

**Issue by ggurman** [lemasato/POE-Trades-Companion#309]
[2020-07-23 02h14m11s.zip](https://github.com/lemasato/POE-Trades-Companion/files/4967515/2020-07-23.02h14m11s.zip)

I got an error message (included as a screenshot) when I clicked the "ty!" button after buying an item.

**Comment by lemasato** [comment]
You are out of date :p
Fixed in ALPHA_8, download it from the #alpha-releases channel
Or [Direct link](https://github.com/lemasato/POE-Trades-Companion/raw/Discord-ALPHA-ZIP/POE-Trades-Companion-AHK-1-15-BETA_9993-Discord-ALPHA-9.zip)
