### ISSUE TITLE
How do I know what Alpha version I have and whether there's a new one?

### ISSUE THREAD

**Issue by ggurman** [lemasato/POE-Trades-Companion#310]
I understand why there's no auto-update in Alpha, but what's the best way to manually check for updates? 

I can't seem to find the Alpha version in the app. The only way I can tell which version I have is to check the number on the last zip file I downloaded.

Thanks!

**Comment by lemasato** [comment]
Hi,
As stated on the #alpha-releases channel: "You can see your current Alpha version by hovering the tray icon."
If you want to be notified about updates, you need to click on the crab icon which will give you the corresponding role which I'll be pinging whenever there's a new alpha uploaded.

**Comment by ggurman** [comment]
Thanks and sorry if I asked a dumb question. I don't keep discord open usually so I didn't think to look there.

**Comment by lemasato** [comment]
All good, no stupid question. Don't hesitate to post on GitHub again or even on Discord if you ever have any question.
