### ISSUE TITLE
buttons sluggish behavior?

### ISSUE THREAD

**Issue by jabbermacy** [lemasato/POE-Trades-Companion#312]
Last couple days POE-TC has been VERY laggy when using the buttons, takes 5 seconds for an invite to go out, etc. Any ideas??

[2020-07-20 12h28m35s.zip](https://github.com/lemasato/POE-Trades-Companion/files/5003436/2020-07-20.12h28m35s.zip)
- For issues, make sure to zip and attach your Logs folder:  
/Documents/lemasato/POE Trades Companion/Logs  

- For questions, make sure to check the README on the [project page](https://github.com/lemasato/POE-Trades-Companion) and the [Wiki](https://github.com/lemasato/POE-Trades-Companion/wiki)  
If you haven't found an answer, it is really fine to post an issue to ask about it  
Though, the quickest way would be to directly ask on the [Discord](https://discord.gg/UMxqtfC)

**Comment by lemasato** [comment]
This was reported on the Discord a few weeks ago. Rebooting their computer did the trick, TC has been working flawlessly ever since. It's worth a try.
