### ISSUE TITLE
Stash tab affinities make locations for items offset.

### ISSUE THREAD

**Issue by mubbsy** [lemasato/POE-Trades-Companion#315]
Because of the new layout to make room for folders, the location of an item is a little offset now.
If in a folder, its almost lined up, but not quite, if no folders, its about half a unit off. (See Pictures)
![dispalced_infolder](https://user-images.githubusercontent.com/48734602/98181766-12a99080-1ed2-11eb-9393-59c0d420b5aa.png)
![dispalced_nofolder](https://user-images.githubusercontent.com/48734602/98181767-13422700-1ed2-11eb-9e52-ca65804d2a9b.png)
Any support for a tick box to choose between the 2 new locations would be amazing.

**Comment by lemasato** [comment]
Sadly it's going to suck like this for a while. Maybe for ever, unless there's a way to know which tabs are in folders using the API. And from what I can see, there isn't.

**Comment by mubbsy** [comment]
I was just thinking something sorta like the tick boxes for disabling quad tab locations, except it just shifts the position of the location a little based on if you select base or folders support. Wouldn't cover people who want tabs not in folders and in folders, but the other 2 groups could at least have accurate positions until something better can be sorted (if that's even possible).

**Comment by lemasato** [comment]
Having too many settings makes everything messy. I'm not a fan of that.
I was already thinking to get rid of the normal/quad/map locations checkbox by automatically retrieving all tab info from the API. So unless there's a way to know which tab is contained in a folder, no "folder offset" support will happen.

**Comment by Brasolis** [comment]
Too many settings makes it messy so you will just leave it broken? Odd choice but OK.

**Comment by mubbsy** [comment]
Yeah I personally don't care about folders, and won't use them, but it would be nice if either option lined up, folders almost line up but its still a little off, and takes away your option to use side bar to navigate, so I won't be using folders, but I would assume default settings without having add folders ideally should be lined up to the new position as all the stashes shifted upwards a bit.

**Comment by lemasato** [comment]
It's not broken, the feature works just fine and there are more important things for now.
This tool is all about simplicity with a bit of customization. Ideally, the tool should be working from the get-go without the user being forced to change their settings to match their account.
For example, the item square could be changed into a dot. We can see that on both screenshot the upper section of the square match the item location, so the dot could be placed in the upper side of the square.

Anyway affinity has just been released and they'll be making changes soon for sure so it'd be better to wait and see.

**Comment by acidh0uze97** [comment]
so for now we just wait or using another tool (like mercury trade) where it works fine? so sad

**Comment by lemasato** [comment]
I'll wait a few days and see how it goes on GGG side.
I won't be there until at least Monday so if anything happens it won't be before then.
But I guess the solution I stated above would be the best. If anyone knows ways to retrieve tab folders from the API, let me know.

**Comment by lemasato** [comment]
Also I'm not against fixing this. I just don't want any temporary workaround, and I would like it to be working without requiring user configuration if possible.
The advantage of POE Trades Companion's item location grid is that it works instantly with any resolution without requiring user configuration. It'd be a bummer to get rid of that only because of stash tab folders.

**Comment by mubbsy** [comment]
Well the issue is that the 2nd picture is with no folders (the default view) and its over half a square off. This would be the default experience of most users out of the box. 

Only by adding folders in the first picture was I able to make it almost line up, but then you lose your list of tabs on the right of the stash which makes navigating way slower. 
If the advantage of the location grid is that it works instantly without configuration, then its missing the mark, as with 0 configuration, it actually aims closer to 1 square down in a standard tab with the new changes to stash layout from GGG.

**Comment by Moubai** [comment]
Hello, 
i've adjusted the value for my personnal stash
playing in 1920*1080
open lib\Class_GUI_ItemGrid.ahk
correct value at line 64 static tab_yRoot := 162/1080 by 132/1080

![image](https://user-images.githubusercontent.com/1314184/98360209-b5285780-2029-11eb-89fe-cc22ff25afd2.png)

**Comment by mubbsy** [comment]
That's exactly what I wanted, thank you so much. <3
Values were a little different for me for whatever reason, but 126/1080 for y and 15/1080 for x seems to have it perfectly aligned for me in normal and quad tabs. Probably going to depend on if you use folders on not for the y value, as the little folder indicator at the top of the tab seems to be about 6/1080 units.

**Comment by codydbgt** [comment]
you could add a hotkey for diffrent layers for difrent grids i would use numpads :) it seams to me you are gunna need a alternative sloution this sounds easy fast and user friendly just add presets for each situation or u could auto detect based on tab name using a prefix u could add to your tab so the program knows what kinds of tabs its dealing with

**Comment by steelbring3r** [comment]
> That's exactly what I wanted, thank you so much. <3
> Values were a little different for me for whatever reason, but 126/1080 for y and 15/1080 for x seems to have it perfectly aligned for me in normal and quad tabs. Probably going to depend on if you use folders on not for the y value, as the little folder indicator at the top of the tab seems to be about 6/1080 units. (although I understand why the x is 16 normally for most resolutions as it can scale)

How do I fix this item placement error? I'm having the same problem as you.
You said you were able to solve your problem, could you teach me step by step what I should do to fix this problem too?

**Comment by steelbring3r** [comment]
> > That's exactly what I wanted, thank you so much. <3
> > Values were a little different for me for whatever reason, but 126/1080 for y and 15/1080 for x seems to have it perfectly aligned for me in normal and quad tabs. Probably going to depend on if you use folders on not for the y value, as the little folder indicator at the top of the tab seems to be about 6/1080 units. (although I understand why the x is 16 normally for most resolutions as it can scale)
> 
> How do I fix this item placement error? I'm having the same problem as you.
> You said you were able to solve your problem, could you teach me step by step what I should do to fix this problem too?

I managed to get xD.
Because someone else seeks to read this post and has the same problem as me (location of the item is wrong), I will explain what I did.
Open your POE COMPANION folder> LIB> Class_GUI_ItemGrid.ahk> Open with path notes> static tab_yRoot.
static tab_yRoot will be 162/1080 (my case). You can edit 162 until it is the way you prefer.
when you make a change, save, reload into the poe companion and see if it's the way you want it.
You can also edit static tab_xRoot if you find it necessary.

Hope this helps.

**Comment by steelbring3r** [comment]
Now i have another problem.... ever time when any people send me mensage for BUY fossils, my poe companion dont mark the position fossil for me.
Its is normal?

**Comment by Moubai** [comment]
> 
> 
> Now i have another problem.... ever time when any people send me mensage for BUY fossils, my poe companion dont mark the position fossil for me.
> Its is normal?

Got the same pb for Fossil, i don't know why, but not really difficult to look for the fossile to sell :-)

**Comment by damianrath** [comment]
Please just incorporate a manual switch (read: checkbox) for now. While I'm a former professional coder, just consider how many of the userbase that aren't and are literally afraid of making changes.

**Comment by lemasato** [comment]
@steelbring3r  @Moubai Fossil tab compatibility hasn't been added yet as I don't own one myself.
If you'd like it to be added, I'd require a screenshot in fullscreen 1920x1080.

**Comment by TheOptimisticFactory** [comment]
@lemasato, here are screenshots of the newer premium stash tabs, all taken fullscreen 1920x1080 :)

### Delve tab
![image](https://user-images.githubusercontent.com/2607260/98586243-bb882f00-22c8-11eb-9b4d-179cb27c7292.png)

### Blight tab
![image](https://user-images.githubusercontent.com/2607260/98586308-d22e8600-22c8-11eb-88fb-e9825bdd62c7.png)

### Metamorph tab
![image](https://user-images.githubusercontent.com/2607260/98586321-d8246700-22c8-11eb-891e-fb733d221d57.png)

### Delirium tab
![image](https://user-images.githubusercontent.com/2607260/98586385-e8d4dd00-22c8-11eb-912d-d664d3a67c66.png)

**Comment by LillieSatou** [comment]
I can confirm this to be bugged - especially with non-Quad/Premium/Normal Stash tabs (even though these ARE BUGGED, but by pixels.) Blight, Card, Delirium, Essence, Fossil, Fragment, Map, Metamorph & Unique stash tabs are ALL Way off (1/3rd screen away if not further.)

**Comment by mubbsy** [comment]
Quad tabs work the same as normal/premium tabs in that they are a few pixels off, and you can edit the code as mentioned above to fix this. But come to think of it, I don't get markers on Fragment/Essence tab, and I'm assuming all the ones above Lillie mentioned that I haven't bothered owning. Not sure if they changed how things are listed there as I don't seem to recall them always listing to top1, and the left number just basically being a list for the position. 

If you require screenshots of any other tabs please reach out so we can collectively get them all working :)

**Comment by Tvangeste** [comment]
Just adding my own voice, the current state of the POE tabs and Trades Companion is quite annoying and there is no way to fix it from the UI.

I am using quad tabs for trades and all my locations are wrong at the moment. It would be really nice if the locations were correct, at least for the most typical case: normal and quad tabs at the top level, no folders.

**Comment by bloodcraw** [comment]
Hiho lemasato,
thanks for the great addon develpment so far, but i also disagree with this options are bad philosophy. Sure if it can somehow be detected, if the tab is inside the folder or not, then go for it. If this can't be done then an option should be there.
So i made a fork based on 1.15.BETA_9994 and add 2 options for myself.

option1: are folders used at all?
option2: if folders are used, is the tab inside a folder or next to a folder?

This contains a fix for the slight offset problem for high positions (e.g. 23:23) in quadtabs as well.
It can be found here if you consider to add this option or somewone else want to use it.
https://github.com/bloodcraw/POE-Trades-Companion/tree/stash_folder_option

**Comment by MPCMarcelo** [comment]
> 
> 
> Hiho lemasato,
> thanks for the great addon develpment so far, but i also disagree with this options are bad philosophy. Sure if it can somehow be detected, if the tab is inside the folder or not, then go for it. If this can't be done then an option should be there.
> So i made a fork based on 1.15.BETA_9994 and add 2 options for myself.
> 
> option1: are folders used at all?
> option2: if folders are used, is the tab inside a folder or next to a folder?
> 
> This contains a fix for the slight offset problem for high positions (e.g. 23:23) in quadtabs as well.
> It can be found here if you consider to add this option or somewone else want to use it.
> https://github.com/bloodcraw/POE-Trades-Companion/tree/stash_folder_option

**Your files had viruses, more specifically Trojans! check your build!**

**Comment by bloodcraw** [comment]
> 
> 
> > Hiho lemasato,
> > thanks for the great addon develpment so far, but i also disagree with this options are bad philosophy. Sure if it can somehow be detected, if the tab is inside the folder or not, then go for it. If this can't be done then an option should be there.
> > So i made a fork based on 1.15.BETA_9994 and add 2 options for myself.
> > option1: are folders used at all?
> > option2: if folders are used, is the tab inside a folder or next to a folder?
> > This contains a fix for the slight offset problem for high positions (e.g. 23:23) in quadtabs as well.
> > It can be found here if you consider to add this option or somewone else want to use it.
> > https://github.com/bloodcraw/POE-Trades-Companion/tree/stash_folder_option
> 
> **Your files had viruses, more specifically Trojans! check your build!**

if that is the case then it is also included in the original repo of lemasato.
all i've changed are these 3 commits, as you can see here: https://github.com/bloodcraw/POE-Trades-Companion/commits/stash_folder_option
lib/Class_GUI_ItemGrid.ahk https://github.com/bloodcraw/POE-Trades-Companion/commit/c80cbe5e8771034a420d54bbd2c30cbfc02fef3d
lib/Class_Gui_Settings.ahk https://github.com/bloodcraw/POE-Trades-Companion/commit/6d1a4999789c5a3ad18ebeb8fbc6aab52db8473b
lib/Local_File.ahk https://github.com/bloodcraw/POE-Trades-Companion/commit/a9eb3e428e6d05773f99bda22ac574f6e2e77f8f

**Comment by lemasato** [comment]
@MPCMarcelo https://github.com/lemasato/POE-Trades-Companion/issues/124 + the message on bottom of [releases](https://github.com/lemasato/POE-Trades-Companion/releases)
