### ISSUE TITLE
Feature updates for buying items

### ISSUE THREAD

**Issue by davoodinator** [lemasato/POE-Trades-Companion#316]
when buying items we should be able to

1. click a button to see where the seller is (via whois)
2. have some ui similar to selling where we can have a bunch of prefabbed messages/macros

**Comment by lemasato** [comment]
Yep, this has been in the works for a while now.
If you want to try it out, it's available on the [Discord](https://discord.gg/UMxqtfC) server under the #alpha-releases channel.
