### ISSUE TITLE
Grid location is wrong

### ISSUE THREAD

**Issue by ChaosDMG** [lemasato/POE-Trades-Companion#317]
![image](https://user-images.githubusercontent.com/10861785/104807689-66e1c280-57e9-11eb-9cd3-9e4a6d3cbdab.png)

**Comment by DarkStas** [comment]
Same.

**Comment by ChaosDMG** [comment]
@lemasato its not he same issue as #315.  Thats a little bit of from folders
![image](https://user-images.githubusercontent.com/10861785/104836203-e9838400-58b4-11eb-86c9-3fec139d2106.png)
Thats not just a little of from folders is something else.

**Comment by lemasato** [comment]
That's the location for normal tabs.
Smaller green square is for quad tabs. Bigger green is for normal stash tabs. Blue is for map stash tab.

**Comment by ChaosDMG** [comment]
its fixed with last update, thx.
