### ISSUE TITLE
Customization of "Buy Interface" (suggestion)

### ISSUE THREAD

**Issue by DarkStas** [lemasato/POE-Trades-Companion#318]
Sorry, don't know where to write this suggestion,
Please add Settings menu for customization of "Buy Interface", Same as "Sell interface".
And please give a chance to change little icons for both of customization's.

**Comment by lemasato** [comment]
Posting here is perfect.
This feature is already available in the Discord Alpha, you might want to check it out here: https://discord.gg/UMxqtfC

**Comment by DarkStas** [comment]
Thanks! Suggest to let it be here for any new user.
