### ISSUE TITLE
[Thank you] HWND based version of your Class_GUI

### ISSUE THREAD

**Issue by BanditTech** [lemasato/POE-Trades-Companion#322]
I really loved your code style in how you created a class to handle GUI elements. I wanted to use it for myself, but found the global variables extremely confusing.

I was thinking about it, and now that AHK supports HWND for any handle, it no longer requires you to set global variables at all.

I rewrote the class to make a simple version utilizing most of the same function behavior but only requiring the HWND and exclusively storing values within the object. I also added functionality for built in tooltips when creating the element. 

I am just putting it out there for anyone else to find :)

[CLASS_Gui.zip](https://github.com/lemasato/POE-Trades-Companion/files/5897248/CLASS_Gui.zip)

**Comment by BanditTech** [comment]
here is a demo script
```
Gui.New("MainMenu","+AlwaysOnTop","Icarus Main Menu")
ButtonHWND := Gui.Add("Button","TestButton","Text","w200 h50","This Button is Not Active")
Gui.SetControl(Gui.GetHWND("TestButton"),ButtonHWND)
ButtonHWND := Gui.Add("Button","TestButton2","Text","w200 h50","This Button is Also Not Active")
Gui.SetControl(Gui.GetHWND("TestButton2"),ButtonHWND)
Gui.Show("MainMenu","w300 h200 x800 y250")
Gui.BindFunctionOnMessage("Gui",0x200,"MouseMove")
```

**Comment by lemasato** [comment]
Hi,
In case you didn't know, the GUI class is going under heavy changes.  
You can see those here: https://github.com/lemasato/POE-Trades-Companion/blob/alpha-new-class-gui/lib/Class_GUI.ahk

Feel free to get some inspiration from it :p

**Comment by BanditTech** [comment]
ooo nice
will check it out shortly!

**Comment by BanditTech** [comment]
ooo already giving me ideas! :D

`this.sGUI.BindFunctionToControl("hBTN_MyButton", ` **this.__class ".ShowMsgBox"** `, "It's working!")`

**Comment by lemasato** [comment]
The included sample code should be fully working.
Settings/Stats/Trades GUIs are still being updated to use the new class, others should be fine.  
If you have any question, don't hesitate to DM me on Discord!

**Comment by BanditTech** [comment]
I see you are still using global variables for everything though, and since HWND skips the need for a window name, you never need to worry about it. idk its food for though, check the style I used for storing the values just based on HWND. It really simplifies the entire thing to not need to match with the specific formating of the globals.

**Comment by lemasato** [comment]
Maybe I'm too stupid, or it's getting late, but I'm not sure what you mean. I thought I got rid of global variables?  
Can you provide an example where I'm using them when I shouldn't? Sorry for the troubles caused.

**Comment by BanditTech** [comment]
There are no troubles, I really love your work! :D I just wanted to share my experience, and how I fixed some of the things.

One was keeping HWND Variables. 

Instead of giving each element a different HWND variable, they are given a temporary variable that is stored into the Gui array.

No element is required to have a named variable using this style and all variables in the gui can be get/set GLOBALLY without the need to name the specific window.

**Comment by BanditTech** [comment]
so you can label the element whatever you want, such as "This is my really really long descriptive label" and it will not matter

**Comment by lemasato** [comment]
Oh I see. Not too sure, it's sort of the same in the end (?).  
handle := this.sGUI.Controls.hMyButton
handle := this.sGUI.GetHwnd("ThatOneButton")

**Comment by BanditTech** [comment]
I guess I like to not use camelcase when I dont have to :P
no worries :) love your work, and thanks for the chat!
