### ISSUE TITLE
closing tabs prompts to close similar offers

### ISSUE THREAD

**Issue by avgjoe** [lemasato/POE-Trades-Companion#36]
I do think prompting to close similar tabs can be a useful feature, but there are a lot of times I will have offers for 20 chaos for 58 fusings in multiple windows and closing the tab and having to click no gets tedious. I would suggest an option for disabling this feature.

**Comment by lemasato** [comment]
I didn't think of it.  
That'll be part of the next release!

**Comment by lemasato** [comment]
Maybe right clicking the close button would offer an option to close all similar tabs?  
That'd be much more convenient.

**Comment by lemasato** [comment]
Feature added of 1.9  
Right click on the "X" button and pick "Close similar trades".
