### ISSUE TITLE
[Feedback] Option to reply "Item is sold" to all buyers instead of just closing the tabs

### ISSUE THREAD

**Issue by EvanRain** [lemasato/POE-Trades-Companion#37]
I prefer to answer to all people when I sold the item, and now i have to close the pop-up dialogue, click "sold" button, close the pop-up dialogue again.. Would really like to see some improvements here, more automation, or at least an option to disable "close all?" pop-up.

Another feature, if you're keeping some sort of to-to list: indicator on the tab that the person is in your party/hideout, some yellow/green dot would work great.

Thank you for your great work, cannot imagine how people trade without Trades Helper.

**Comment by lemasato** [comment]
>I prefer to answer to all people when I sold the item, and now i have to close the pop-up dialogue, click "sold" button, close the pop-up dialogue again.. Would really like to see some improvements here, more automation, or at least an option to disable "close all?" pop-up.

I thought of adding this.  
Closing all similar tabs would allow the user to send a message.  
**BUT...**  If you have lots of similar trades, you will end up being muted temporarily (spam protection).  
Obviously, we could set a timer at which rate the messages would be sent, but that'd still be an issue... The user would be unable to do any action for a period of time.
&nbsp;  
>Another feature, if you're keeping some sort of to-to list: indicator on the tab that the person is in your party/hideout, some yellow/green dot would work great.

Yep, that'd be really handy.
&nbsp;  
Glad you like the tool, and thanks for the suggestions!

**Comment by EvanRain** [comment]
Oh yeah, I actually got muted once, but that was after like 10+ messages in
a row. Anyway, I don't really mind clicking the button manually, it's just
the "close all" pop-up that annoys me, the opt-out checkbox would be great.

Another issue I'm having is that sometimes the tool fails to put item in
clipboard on tab switch. I'm not sure, but I think it happens whenever I
click "sold" on the x+1 tab and it's automatically switches to x tab.

God, and I wish there was a possibility to check if any input field is
currently active before you click a button. How many times instead of
sending a message I used all my potions and random skills..X)

**Comment by lemasato** [comment]
>Oh yeah, I actually got muted once, but that was after like 10+ messages in
a row. Anyway, I don't really mind clicking the button manually, it's just
the "close all" pop-up that annoys me, the opt-out checkbox would be great.

I understand the po-up being an annoyance, and that'll be changed (See #36)

>Another issue I'm having is that sometimes the tool fails to put item in
clipboard on tab switch. I'm not sure, but I think it happens whenever I
click "sold" on the x+1 tab and it's automatically switches to x tab.

I'll look into it!

>God, and I wish there was a possibility to check if any input field is
currently active before you click a button. How many times instead of
sending a message I used all my potions and random skills..X)

Sadly not possible as it would require reading into the game's memory.

**Comment by lemasato** [comment]
The pop-up has been removed with the 1.9 update.
Instead, you can right click the "X" button and choose "Close similar trades".  
As of the clipboarding issue, after lots of testings, the issue should be gone.

Thanks again for the reports!

**Comment by EvanRain** [comment]
Nice work!
