### ISSUE TITLE
PID is no longer associated to a POE instance

### ISSUE THREAD

**Issue by damoochie** [lemasato/POE-Trades-Companion#41]
I'm getting this message since last update. I tried restarting everything but still i get this message every time I execute a macro. If i select "continue with this one", i see the macro executed in my chat box (example: I have a macro set to the 'HOME' key for going to my hideout which appears as {Enter}/hideout{Enter} when i try to use it).

Something I've done?

**Comment by damoochie** [comment]
I downloaded the previous version and it's working as per usual... so me thinks there's an issue with the latest update ;>

**Comment by lemasato** [comment]
Fixed as 1.9.3, thanks for the report!
