### ISSUE TITLE
[Question] Question about variable TradesMarkCompleted

### ISSUE THREAD

**Issue by avgjoe** [lemasato/POE-Trades-Companion#43]
Is this a future feature that will log our trades? I've been contemplating trying to rig up something on my own, but if this the plan I can't wait. Appreciate all the work that's been done on this

**Comment by lemasato** [comment]
Yes.

**Comment by lemasato** [comment]
Just pushed a commit about this.  
Can't believe it's already been one month...
I'm really sorry for the time it takes me to push updates to the tool...
Hopefully, the next major update should be released before Tuesday.

**Comment by lemasato** [comment]
v1.10 has been released!
If you use a button that has the "Save trade infos..." checkbox enabled, its infos will be extracted into a file.
For now, there is no GUI that allows easy read of these statistics, but I plan on working on it.

**Comment by lemasato** [comment]
This update should see the day tomorrow.  
[Meanwhile, the 1.11.BETA_1 release can be downloaded here!](https://github.com/lemasato/POE-Trades-Companion/raw/dev/POE%20Trades%20Companion.exe)

**Comment by lemasato** [comment]
Decided to leave the BETA running few days in case they would be any unknown issue, but it seems we're good to go! 1.11 has been released, you can access the Stats menu by right clicking the tray icon and choosing "My Stats".
