### ISSUE TITLE
Skills/Flasks/Actions still executed accidentally

### ISSUE THREAD

**Issue by damoochie** [lemasato/POE-Trades-Companion#44]
In your last update it was mentioned there was a fix for accidentally executing random actions if the chat key is invalid. I'm not sure what invalid really means but I'm still having this issue if the chat box is selected (with cursor flashing) and I select an option from the reply boxes.

Not a real biggie issue... but it can get annoying when you have a ton of auras like one of my builds and have to recast them coz one of the macro letters hits the change weapon key xD

So this would be a helpful feature to get working, thanks!

**Comment by lemasato** [comment]
Nothing I can do about this. This is "intended behaviour". There is no way to know if the chat window is activated.
The fix about the chat key is for when we are unable to read it from the game's file.
