### ISSUE TITLE
Transparency applied to the game

### ISSUE THREAD

**Issue by lemasato** [lemasato/POE-Trades-Companion#47]
The transparency is applied to the game window as well upon receiving a whisper.
Issue only occurs on the latest version 1.9.5, and the previous 1.9.4 works fine.

**State:**
Could reproduce the issue.
Definitely due the to A_Gui variable.

**Reports:**
[Petusillos- Forums](https://www.pathofexile.com/forum/view-thread/1755148/page/17#p14466562)

**Solution:**
The A_Gui variable seems to be unreliable.  
The reason of using this variable was to fix an issue where the transparency would be incorrect while in "EXE_NOT_FOUND" mode.

**Comment by JYshadow** [comment]
It's not the exact same issue, but when I recieve a whisper, the trade window doesn't apply the transparency of being active. Upon recieving a trade whisper it stays in its _inactive transparency_. It only goes to its _active transparency_ again when I move the slider (inactive or active) in settings.

**Comment by lemasato** [comment]
You are referring to #42 
I had made a few changes in the latest update, hoping it'd fix that issue...  
Guess it didn't work. It's a really obscure one.

**Comment by lemasato** [comment]
Fixed with 1.9.6 release.
