### ISSUE TITLE
Tabs aren't being removed after Trades are completed

### ISSUE THREAD

**Issue by fEcAlMaTteR** [lemasato/POE-Trades-Companion#48]
The tab button is kept for awhile after completing trade.  The content of it is removed so it's not broken but it's confusing if you have a queue.

**Comment by lemasato** [comment]
Issue only occurs with the Path of Exile skin.
I'd recommend you to switch to the default System skin while I take a look at this.

**Comment by fEcAlMaTteR** [comment]
alright, wasn't happening before this mornings updates.

**Comment by lemasato** [comment]
Got it. Will be fixed with the next minor release, thanks for the report!
