### ISSUE TITLE
/tradewith %buyername% not working

### ISSUE THREAD

**Issue by PotatoPineappleApple** [lemasato/POE-Trades-Companion#50]
Probaly a mistake of my part, but i can't use the command.

**Comment by lemasato** [comment]
Could you provide a screenshot of how you set it up?

**Comment by PotatoPineappleApple** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/28679388/26033984/db06b6f6-388b-11e7-8053-210cfbacdbad.png)

**Comment by lemasato** [comment]
You must set the Horizontal/Vertical positions and the button's size.
Left/Center/Right is pretty clear.
Top/Middle/Bottom will set the button on the 1st/2nd/3rd row.
Small/Medium/Large will change how many slots should the button take.

Examples:
Button on top left: Left/Top/Small
Button in bottom, taking all the GUI's width: Left/Bottom/Large
Button on middle, taking center and right slot: Center/Middle/Medium

I want to improve the system to position the buttons, but currently I'm not sure how.

**Comment by PotatoPineappleApple** [comment]
Can't i use the hotkey with the button being disabled?

**Comment by lemasato** [comment]
You can. Please read the edit part of my previous post.
All you need is to set up an hotkey with "/tradewith %buyerName%"

**Comment by PotatoPineappleApple** [comment]
Maybe the button i'm using is just not working. Thanks!

**Comment by lemasato** [comment]
That's how it is built.
If a button is set to disabled, it won't appear on the interface and the hotkey will not be activated.
Glad we could resolve your issue!

**Comment by PotatoPineappleApple** [comment]
I'm dumb.
