### ISSUE TITLE
Avira Reports Malware in Latest POE Trades Companion.exe

### ISSUE THREAD

**Issue by idSmoker** [lemasato/POE-Trades-Companion#52]
While downloading the latest installer to update, either from launching the previous version of the app, or by downloading from [https://raw.githubusercontent.com/lemasato/POE-Trades-Companion/master/POE%20Trades%20Companion.exe](url), my anti-virus, Avira (free), is flagging the executable as malware.

The exact message is:

> The pattern of 'HEUR/APC (Cloud) [HEUR/APC]'
detected in file 'C:\Downloads\POE Trades Companion.exe.
Action performed: Move file to quarantine

Anyone else seeing this issue?

**Comment by lemasato** [comment]
False report. It's open source, and AHK is pretty easy to understand.
A quick google search for `HEUR/APC (Cloud)` lead me to lots of false positive reports.

The only modifications the tool does to your system: 
- Store the settings in a file.
- Make a backup copy of POE's settings file.
- Extract the assets from the executable.

And the only websites accessed by the tool is:
- GitHub. Reaches for the version.txt file and download the new executable (if updating).

If for some reason you choose not to trust the executable: [Usage](https://github.com/lemasato/POE-Trades-Companion/wiki/Usage)

**Comment by idSmoker** [comment]
Thanks, that's the information I was looking for.
