### ISSUE TITLE
Make small buttons optional

### ISSUE THREAD

**Issue by DocHoncho** [lemasato/POE-Trades-Companion#55]
It would be nice if it were possible to hide the small buttons.  I don't personally have any use for them, and mystery icons are always bad UX.  If they had tooltips they'd be a little better, but I'd like to hide them if possible.

Plz don't make this just like MercuryTrade!  If people want a terse, cryptic UI they should just get MercuryTrade instead!

**Comment by lemasato** [comment]
Mystery icons?
But based on their icon, it's pretty clear what they do.
Also yes, I will add an option to toggle them off!

**Comment by damoochie** [comment]
Just wanted to add the little icons are great. I had these macros set anyway before these small buttons were available so this has freed up space for few more custom action buttons.

Though, If you're adding options to the small icons, it would be nice to be able to arrange their position.

And a small thing I've noticed with font sizing is that 9 is too small, 11 is too big and there is no difference between 9 and 10 (10 being the size that would most likely be the best for me). No biggy but thought i'd mention it.

Thx again

**Comment by lemasato** [comment]
Being able to set positions (or disable) will be available in next update.  

`9 is too small, 11 is too big and there is no difference between 9 and 10  `
I have looked into it, and sadly there is nothing I can do. It has something to do with AHK's way of rendering font. This simple script shows there are definitely some sizing issues with some fonts:
```
Loop 20 {
	Gui, Font, S%A_Index% Q5, MS Sans Serif
	Gui, Add, Text,, THIS IS FONT SIZE %A_INDEX%
}
Gui, Show
```
As a workaround, I would suggest you to use a different font.
Installing fonts to the tool can be done by dragging the font file here: 
`\Documents\AutoHotkey\POE Trades Companion\Fonts`

**Comment by lemasato** [comment]
Feature added as of [1.10.2](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.10.2).
@damoochie I also included the Segoe UI font, which works fine with all sizes.

**Comment by damoochie** [comment]
Perfect! Thanks so much <3

**Comment by DocHoncho** [comment]
Thanks!  Sorry if I came off as grouchy, I really appreciate the work you put into this tool!  I was just afraid you were going down the minimalistic UI road!

**Comment by lemasato** [comment]
Oh, but you were not agressive at all.
I tend to make my tool as customizable and user-friendly as possible.
So yeah, this feature definitely had to implemented!
