### ISSUE TITLE
"Could not detect the chat key"

### ISSUE THREAD

**Issue by JYshadow** [lemasato/POE-Trades-Companion#57]
Every button doesn't work. Happened after the last update (either 1.10.3 or 1.10.4). It worked fine yesterday. Here's the log:
https://pastebin.com/zZQBMsXT

**Comment by lemasato** [comment]
Can you confirm it still works fine on 1.10.2? [(Download link)](https://github.com/lemasato/POE-Trades-Companion/releases/download/1.10.2/POE-Trades-Companion.exe)

Also, do you have any other logs file in the folder?
If not, look into other users's folder.

**Comment by JYshadow** [comment]
The Beta works fine

**Comment by lemasato** [comment]
Oops. I thought the GitHub page would refresh itself automatically.
The fix has been released!
