### ISSUE TITLE
Tab 1 issue

### ISSUE THREAD

**Issue by JeffArkun** [lemasato/POE-Trades-Companion#59]
Hi. I just updated to the latest version.  (v1.11)

there is an issue with tab 1. I have no buyer or anything but there is a tab 1 open and when I click any button (clipboard, ask to wait, thank you, etc...) it says  no buyer found operation cancled but the tab stays open. Even when I click the X to close the tab it gives the same error.
Also when I minimize it still says on the top "Queued Trades 1"
Tried restarting and such but no luck.

Update: Right clicking taskbar icon and picking reload fixed the problem.

**Comment by lemasato** [comment]
Could be related to this new feature. I'll be doing some testings later

>
- Upon reloading (through the tray menu option or updating to a new version), all your pending trades are saved locally.
On next launch, they will be loaded so you never lose a potential sale!

**Comment by lemasato** [comment]
This issue has been fixed with 1.11.1 (See 2b007299d11d6c0dc03579a9768c51fe505ef1fd).
Thank you for reporting!
