### ISSUE TITLE
Invalid Option error dialog

### ISSUE THREAD

**Issue by dcgaines** [lemasato/POE-Trades-Companion#63]
Whenever I try to run the new 1.12.BETA_3 it comes up with an error dialog.  I tried deleting it and downloading a fresh copy from github and the same issue kept happening
![capture](https://user-images.githubusercontent.com/10469397/28889471-1b449888-7792-11e7-81e6-cd1fe59be215.JPG)

**Comment by lemasato** [comment]
I'll inspect and fix right now.

**Comment by lemasato** [comment]
There we go, fixed on BETA_4!  
Thank you for reporting!

**Comment by dcgaines** [comment]
There is a different one now
![capture](https://user-images.githubusercontent.com/10469397/28892306-766ed2ba-779b-11e7-97df-6c7cd7aa2bff.JPG)

**Comment by lemasato** [comment]
That's an issue with the skins.  
Could you open the Documents\AutoHotkey\POE Trades Companion\Skins, head to the Skin's folder you are using and see if the "TabWhisperActive", TabWhisperHover", "TabWhisperInactive" png files are existing?

**Comment by BladesOfExile** [comment]
> Could you open the Documents\AutoHotkey\POE Trades Companion\Skins, head to the Skin's folder you are using and see if the "TabWhisperActive", TabWhisperHover", "TabWhisperInactive" png files are existing?

Nope there is nothing there.

Also, there is no File_Install.ahk in that directory.

**Comment by lemasato** [comment]
> Nope there is nothing there.
Also, there is no File_Install.ahk in that directory.

Just to make sure:
File_Install.ahk should be located in .\resources\ahk\ from **the script's folder** when using the source.
**Not** in Documents\AutoHotkey\POE Trades Companion.  
Can you double confirm the file was not there?

**Comment by lemasato** [comment]
BETA_5 deployed. Sorry for the issue guys.
Once again, thank you for reporting these issues!
It actually makes me very happy to realize people are using the BETA releases.

**Comment by dcgaines** [comment]
That appears to have fixed it for me, cannot test the functionality of the new color changing features until later though, but I am excited!

**Comment by BladesOfExile** [comment]
Seems to be fixed, great work and great app!

**Comment by lemasato** [comment]
Happy trading!
