### ISSUE TITLE
Gem clipboard search not working (1.12.BETA_5)

### ISSUE THREAD

**Issue by rushtothesun** [lemasato/POE-Trades-Companion#64]
For example this was copied to the clipboard for Controlled Destruction Level 1:  
Controlled Destruction Support Lvl:1 / Qual:0%

**Comment by lemasato** [comment]
Yeah I have just noticed this too.  
I'll take a look and fix

**Comment by lemasato** [comment]
Done!  
The fix will not be available until the next release.
But meanwhile, if you wish to use the fix, you can [download and run the source](https://github.com/lemasato/POE-Trades-Companion/archive/dev.zip)

**Comment by lemasato** [comment]
[Fixed as of 1.12.BETA_6!](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.12.BETA_7)
Thank you for reporting.
