### ISSUE TITLE
Stash tab highlighting 

### ISSUE THREAD

**Issue by rushtothesun** [lemasato/POE-Trades-Companion#65]
Do you think you could add stash tab highlighting? Having multiples of the same unique and selling them is pretty difficult and slow because you have to count the blocks to see which one the buyer is asking for.

MercuryTrade currently has this, but Trades Companion is literally better in every other way.

**Comment by lemasato** [comment]
It has been requested and will (probably) be a future features.  
Though I cannot estimate when I'll be working on it.

**Comment by EThaNol2005** [comment]
Is this still a thing? like Mercurytrade?

**Comment by lemasato** [comment]
Yep.
I was intending to include it in 1.13.
If the feature doesn't make it in time, then I'll just add it post release in another update.

**Comment by lemasato** [comment]
Available as of [1.13.BETA_6](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.13.BETA_6)!
