### ISSUE TITLE
Cant use settings

### ISSUE THREAD

**Issue by realIzok** [lemasato/POE-Trades-Companion#66]
When I use the companion, there is no tray icon to right click on

**Comment by lemasato** [comment]
- Do you get the Trades GUI to appear?  
- Have you tried reloading the application?

**Comment by lemasato** [comment]
I have added a potential fix for this on [1.12.BETA_7](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.12.BETA_7).  
Could you try it out and report back?

**Comment by realIzok** [comment]
I got it figured out. I found the config file and edited it externally.

**Comment by lemasato** [comment]
That still remain an issue on itself.
The workaround on BETA_7 did not make it re-appear?

**Comment by lemasato** [comment]
Hi, should this be considered fixed?

**Comment by realIzok** [comment]
Yes
