### ISSUE TITLE
[Suggestion] Is there a way to minimize the overlay when you ask someone to wait?

### ISSUE THREAD

**Issue by dcgaines** [lemasato/POE-Trades-Companion#69]
Often when I ask someone to wait I am in the middle of a fight and the overlay somewhat obstructs my screen, is there a way to ask someone to wait and minimize it with a single click?

**Comment by lemasato** [comment]
Not possible at the moment, but will be part of the "Button Actions" overhaul.
Once I'm done with 1.12, that'll be the new thing I'll be working on.

Meanwhile, some alternatives (that require more than a single click):
- Bind the button to an hotkey, so you can answer your buyer while you are fighting, without having to un-minimize the GUI. The downside to this is that it will only answer to your currently active tab.
To work around this, you can either:
- - Set hotkeys to scroll between tabs (Hotkeys > Special).
- - Or use a regular hotkey that replies to your latest whisper: `@%lastWhisper% blablabla`.
- Bind the "Toggle Minimize State" (Hotkeys > Special), so you can instantly minimize the GUI after answering by pressing the hotkey.
- Set an /autoreply hotkey that you could hit when entering a map
Autoreply is reset upon entering a new area, so you would have to do it for every new area..

**Comment by lemasato** [comment]
[1.12.BETA_10 released](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.12.BETA_10)
I decided to add a "Send Message + Minimize" action, as a temporary solution!
