### ISSUE TITLE
Rework "MINIMIZE" button

### ISSUE THREAD

**Issue by sockenklaus** [lemasato/POE-Trades-Companion#72]
Hi,

this is a very minor issue, but I'd like to see this improved:

On the right side of the Companion's  top bar there's a "MINIMIZE"-button that toggles the visibility of the overlay.

I'd love to see two improvements of this button:

1. Make this a more distinct or visible button or toggle so the user knows at a glance, that they can click on it to do something. The way it's now it's undistinguishable from the rest of the bar.
2. Change the button's description according to the window's state: At least let it say "MAXIMIZE" when the window is minimized and "MINIMIZE" when it's maximized.

Otherwise great work and very, very useful tool!

**Comment by lemasato** [comment]
Yeah, this has been on my mind for a while now.  
Having a specific asset for a minimize button would look much better than having the whole text taking 1/3 of the title bar.

Thank you for the kind words!

**Comment by sockenklaus** [comment]
I fiddled around with Photoshop for a few minutes.

Maybe [this](https://github.com/sockenklaus/PoE-Trades-Companion-Buttons) is of any use for you?

**Comment by lemasato** [comment]
I like it. I may just end up using it, to be honest!

Seems you even made one for the System skin, but it will be gone on [**1.12**](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.12.BETA_8).
It will be replaced by a cleaner "White" themed skin as well as a "Dark Blue" themed skin.

**Comment by lemasato** [comment]
Yup, intentional.
This is to make spotting active/inactive state easier.
Though I don't like the black colour myself, so I'll most likely look for something else.
Probably a bold font on active and normal on active

**Comment by lemasato** [comment]
Hey there!
This has been added as of [1.12.BETA_11](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.12.BETA_11).
Thank you for the assets!
