### ISSUE TITLE
Using PoeTradesCompanion is like I'm doing an Alt Tab.

### ISSUE THREAD

**Issue by Grandjojo** [lemasato/POE-Trades-Companion#73]
Hello my PoE is windowed fullscreen, the first day with Poe Trades Companion all works as intended I suppose but the next day when I use this addon it's like I'm doing an alt tab (poe sound is off and I can't move without clicking on the PoE tab).
I didn't change anything, I don't know why it's doing this.

**Comment by lemasato** [comment]
Hellooo,
I'm not too sure to understand...
When exactly does the "alt-tab" occurs?

**Comment by Grandjojo** [comment]
When I click on the addon, like when I click on minize, invite ect... So it's "Minize" check what he wants, "click on the game"  open my stash "party invite" "click one the game" "trade" "kick" "click on the game" "minimize" "click on the game"

**Comment by lemasato** [comment]
I'm really confused.
Maybe could you get a video footage/gif from the issue, so I can get a better grasp on what's going on?

**Comment by Grandjojo** [comment]
In game : http://hpics.li/edd3058
When I Un-Minimize : http://hpics.li/91c6005
Windows Taskbar in here and PoE is in background, however it's not doing that when I use the buttons like "invite" or "thank you" anymore.

**Comment by lemasato** [comment]
Using W10, I don't get this issue personally.
I don't remember it occurring back then on W7 either, but I'll see if I can trigger it.

**Comment by lemasato** [comment]
Using W10, I don't get this issue personally.
I don't remember it occurring back then on W7 either, but I'll see if I can trigger it.

Also, from the screenshot I can see you are using 1.11.3, I'd recommend using the latest beta available here: https://github.com/lemasato/POE-Trades-Companion/releases

**Comment by Megaddd** [comment]
I believe what OP is referencing, is that since the TC overlay is a window, whenever you click buttons, it makes the fullscreen windowed game go to background, which brings the taskbar up

from this: http://i.imgur.com/jUiOQCh.jpg
to this: http://i.imgur.com/f0w3sgI.jpg

**Comment by lemasato** [comment]
Never had this happen personally.
Giving the focus back to POE would cause the taskbar to flicker, not the best fix out there in my opinion.

**Comment by lemasato** [comment]
Hi, should this be considered fixed?

**Comment by Megaddd** [comment]
Yeah I don't think this is an issue at all.
