### ISSUE TITLE
Custom Buttons not saving through reload

### ISSUE THREAD

**Issue by Synol** [lemasato/POE-Trades-Companion#74]
Whenever I edit the Party Invite Custom Button and remove the line "2 @%buyerName% My %itemName% listed for %itemPrice% is ready to be picked up!" it works until I close Trades Companion.

But when I reload the program, ie the next day when I go to play again, the line "2 @%buyerName% My %itemName% listed for %itemPrice% is ready to be picked up!" is back again. The program only seems to save the macros that you edited, if you delete a line it won't remember that.

Since this macro sends 2 commands it's an illegal macro. So it would be great if it would remember that I deleted the message portion of the macro. Having to edit it every single time I load it up is really annoying.

**Comment by lemasato** [comment]
Strange... Thought I had it fixed. Thanks for reporting!

**Comment by lemasato** [comment]
Hi there. Fixed with [1.12.BETA_10](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.12.BETA_10) release!
