### ISSUE TITLE
message issues

### ISSUE THREAD

**Issue by CevdetArkun** [lemasato/POE-Trades-Companion#75]
So thanks for fixing the "kicked from server" issue
but here is the new problem I am having

messages are all massed up.

party invite button not inviting, sending wierd msg to people sush as instead of items for Xchaos is ready to picked up(default msg) its saying ex: "arc" level"8" and not doing anythhing after that. and sometimes sends these messages twice.
I just added 1 line to thank you button rest is the same (1. kick  2.thank you 3.additional thank you)
sometimes doing just 1 of them sometimes 2 sometimes all 3 and sometimes sending 1 of the thank you msg twice and that is it not kicking and stuff.

But all these things are not happening all the time with every trade.
Like right now I just did a trade and every button did what it is suppose to do.

Not sure if others are having such issues though. I will try to do a clean install right now. will even delete the config files and stuff and try both beta and latest releases.

**Comment by lemasato** [comment]
Sounds like an issue with the clipboard.
Doing a "clean install" won't help.
The latest stable release still uses the old way (that could trigger the "too many actions" kick), so comparing it with the latest beta won't help either.

I simply need to play around with the delays, and see the best compromise between speed/reliability.
Thanks for reporting!

**Comment by ldbenoit** [comment]
Hey, just wanted to let you know that I am having this issue lately as well. It started after my graphics card blew up yesterday. I've just been trading while waiting for my rma and this happens frequently. I see you have addressed this in your latest commit, Ill test it out and get back to you.

**Comment by lemasato** [comment]
Hey there,
Hope it works. Did some testings (over 10k simulated button click) and not a single issue.

**Comment by ldbenoit** [comment]
So far so good, no issues while running dev.  On an unrelated note, I've been switching out the tc_symbols font whenever for my custom one not sure if you've seen it.
https://github.com/ldbenoit/POE-Trades-Helper/blob/Dev/Resources/Fonts/TC_Symbols.ttf
![image](https://user-images.githubusercontent.com/20944/29898955-72ee7506-8d9d-11e7-9553-43aeef800647.png) 
Just need to change the scale of the font `Gui, Font,% "S" 15*scaleMult,% "TC_Symbols"`

**Comment by lemasato** [comment]
The fix has been added as of [1.12.BETA_11](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.12.BETA_11).
