### ISSUE TITLE
when selling currency for currency, ratios should be displayed (and checked against ones set in settings)

### ISSUE THREAD

**Issue by Megaddd** [lemasato/POE-Trades-Companion#77]
For instance:

Item: 39 Alchemy
Price: 10 Chaos (1:3.9 ✓)

or 

Item: 389 Alchemy
Price: 100 Chaos (❢ 1:3.89 ✗, set: 1:3.9)

**Comment by lemasato** [comment]
This would be nice, but sadly it's not something I will be adding. Or at least, not in the near future.

Adding it the way you suggest would be extremely annoying for the user, as he would have to constantly edit his ratio settings as the league progresses.
A nice way to make it work would be to retrieve your currency.poe.trade ratios then compare with the whisper received... But honestly, it's not something I want to work on. If poe.trade were to ever make any html change to their page, the feature would have to be updated accordingly. Too much fuss in my opinion.
