### ISSUE TITLE
Custom Chat Button Not Hitting Enter After Message.

### ISSUE THREAD

**Issue by postal291** [lemasato/POE-Trades-Companion#78]
Created a new button for inviting someone without a message.

Action: Write Message
1: /invite %buyerName%
2: [blank]

But when I click it, the chat opens, it populates the /invite <buyerName> properly, but it just sits there.
Am I missing something?

**Comment by lemasato** [comment]
In your case, you must use "Send Message".
"Write Message" is in case you wish to write additional informations to your whisper before sending it.

**Comment by postal291** [comment]
Ahhh, thank you lemasato

**Comment by lemasato** [comment]
All good!
By the way, if you leave your mouse on the "Actions" dropdownlist, you will get a small tooltip explaining each actions. The same is true for most other settings in the Settings GUI.
