### ISSUE TITLE
Timestamps on PoE PID 

### ISSUE THREAD

**Issue by rushtothesun** [lemasato/POE-Trades-Companion#81]
https://puu.sh/xkZKE/551bdf445e.png

Could you add timestamps to the executable selection? I'm having difficulty getting two instances of Trades Companion to work. I want to have my main account free to map while my alt account makes low-currency trades (1 alch, 3alt, etc) so that I don't have to waste a portal trading. 

The issue is that launching another instance with /NoReplace isn't attaching to the other PoE instance and I can't tell if I'm picking the right one because there's no timestamps.

Edit: Got the two instances of Trades Companion to match the two instances of PoE but then they both revert to one instance of PoE, meaning when someone messages my main account, both instances of Trade Companion popup.

**Comment by lemasato** [comment]
In your case, you do not require to run two instances of the tool.
Running multiple instances of the tool is only required when using different paths for your game (example first instance using GGG launcher located on `D:\Games\Path of Exile` and second instance using Steam launcher located on `D:\Steam\...\Path of Exile`).

**Comment by lemasato** [comment]
Hi there, [1.12.BETA_12 released](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.12.BETA_12). This GUI has been re-done.
![chooseinstancegui](https://user-images.githubusercontent.com/14184969/30306355-f28cd42c-9777-11e7-95e6-42b000165499.png)
Each icon correspond to an instance. Upon clicking one of the icons, its corresponding instance will be set on top and its taskbar button will flash, allowing you to easily find the one you desire.

**Comment by rushtothesun** [comment]
This is perfect, thanks!
