### ISSUE TITLE
Quick minor enhancement - Accept button hotkey.

### ISSUE THREAD

**Issue by Megaddd** [lemasato/POE-Trades-Companion#83]
Just as simple as it sounds, a hotkey for clicking the area of the screen where the accept button is.

**Comment by lemasato** [comment]
Not sure, I don't want to make hotkeys for everything and anything.

But if you want, you can just make an external script that'd do just that! It's pretty easy to do.
- Download and install AutoHotKey.
- Run Window Spy: `Program Files\AutoHotkey\AU3_Spy.exe`
- Get someone to send you an invite, put your mouse over the "accept" button and press Win+A.
- - (The Win+A hotkey freezes the Window Spy window, allowing you to retrieve the coordinates)
- On the Window Spy, under Mouse Position, get the Client coordinates.
- Now make a new .ahk script (right click on the desktop > new > autohotkey script)

Assuming the coordinates are 800, 200:
```
Numpad1:: ; This is your hotkey
MouseGetPos, mouseX, mouseY ; Gets the current mouse position
MouseClick, Left, 800, 200 ; Click at 800, 200
Sleep 10 ; Small delay before moving the mouse back
MouseMove, %mouseX%, %mouseY% ; Move the mouse back to its old position
return
```

Or you could click on the button, based on a picture. [MouseClick.zip](https://github.com/lemasato/POE-Trades-Companion/files/1273112/MouseClick.zip)

**Comment by Megaddd** [comment]
Oh, of course, I just realised there's no reason I couldn't just run more scripts ^^
