### ISSUE TITLE
Companion sends wrong text if russian layout is active

### ISSUE THREAD

**Issue by snqlby** [lemasato/POE-Trades-Companion#84]
It sends "v" text to the latest recipient instead of required text to a new buyer.

**Comment by lemasato** [comment]
Oops. You're right.

**Comment by lemasato** [comment]
This fix will be part of BETA_12, which will be released later today.
Meanwhile, you can download the [dev branch source](https://github.com/lemasato/POE-Trades-Companion/archive/dev.zip) and run POE Trades Companion.ahk.
Once the new version is released, you will receive the update prompt as usual. (When updating, it only download the latest executable. If you want to keep using the .ahk file, you will have to manually download the release source.)

**Comment by lemasato** [comment]
[1.12.BETA_12 released](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.12.BETA_12), this issue is now fixed.
Thanks again for reporting!
