### ISSUE TITLE
Price per item line

### ISSUE THREAD

**Issue by snqlby** [lemasato/POE-Trades-Companion#86]
I would like to propose a new feature. It would be great to have a row with price per item as result of <total_price/quantity> parsed from the message
I get 5-10 requests per minute and it would be nice to see the price per one item. I want to be sure that the buyer (a potential scammer) did not change the price manually.

**Comment by snqlby** [comment]
There are a lot of scammers in the game who correct the message with their hands.

**Comment by lemasato** [comment]
Hi, this feature may be added in the future.
I don't personally trade currency, so I have no idea how often(rare?) people edit the whisper message, but that would surely be handy.

Here's my answer to a similar request on the forums, a little bit a go:
> This has been requested a few times now, and I do realize it's something that would greatly improve trading (making sure the person did not edit the currency.poe.trade whisper).
But (at the moment) I'm not sure if that's something I will be adding.

**Comment by Survap** [comment]
Hey lemasato, thanks for sharing your thoughts, and I want to add to the OP my own point of view about this suggestion. As a currency flipper, I come across a lot of people and they all want to make trades as fast as possible; when you trade with many people at the same time, some of them will just leave if you don't make all trades in time which leaves little to no time to make any calculations to see if the exchange ratio for currency A to B is correct. This might result into: A. You lose pending trades; B. You blindly accept the amount payed and assume you might have been scammed by the player buying.
Thus, a huge way to mitigate this would be, like the OP said, adding a way to know how much currency a player should be paying to buy 1 unit of whatever i'm selling.

Thanks for reading and good luck.

**Comment by Survap** [comment]
Oh and I like to emphasize that there are **_a lot_** of scammers changing the ratios of what they're buying to something relatively similar, and when big volumes of currency are traded fast this kind of things happen.

**Comment by avgjoe** [comment]
All I do with companion is flip currency and I've ran into the whisper changing a couple times. However, I have a friend who only trades items and he has run into it far more than I have. Most especially on rare items. When he first caught it, it was on a rare jewel he was selling and only had one jewel listed so he knew what to expect for it. Although, afterwards he wondered if he had fell for it before on other listings. As Survap said, when you're flipping currency, you're normally doing trades rapidly and it's harder to catch unless you know your ratios well, which as volatile as the market is, it's often not well at all. This wasn't something I had thought about being in the app, but I would definitely welcome the addition.

**Comment by deduijk** [comment]
When u grab the item to put it into the trade box you see the price it was listed for by u? Takes a split second to look. I sometimes forgot though. might have fallen victim to this too, but all u have to do is look  b4 u drag it into inventory?

**Comment by lemasato** [comment]
Should this issue be considered as resolved?
We've been having "Price verify" since 1.13 (31 aug 2018). This should really help if the rate / price seems off. It takes a second for the price/rate to be confirmed.
