### ISSUE TITLE
Sending any kind of input to the chat does not work

### ISSUE THREAD

**Issue by baiumbg** [lemasato/POE-Trades-Companion#89]
A quick note: this is probably a local issue, as I haven't seen anyone else complain about it.

Whenever I try to do anything that interacts with the chat (invite to party, send response, whisper, etc.) it either doesn't do anything or it opens the chat and writes the message without sending it. I tried MercuryTrade and I have the same issue there as well. I have no idea when this started happening, but I remember using both scripts without any issues.

Edit: Could the version of AHK I have installed somehow be the cause for this?
Edit 2: I think this started happening around the time I changed my keyboard. I use Corsair K70 RGB (thus I have the Corsair Utility Engine installed). Could this be causing some kind of delay?

**Comment by lemasato** [comment]
This is most likely a conflict issue.  
Close every optional program and see if the issue goes away.

**Comment by baiumbg** [comment]
Hmm, looks like this was caused by a program called Resanance (soundboard software basically). I've had other input related issues caused by it as well. Hadn't noticed it was running every time POETC/MercuryTrade was running.

Thanks!
