### ISSUE TITLE
Major bug - when you write non-color text to color field in settings the app crashes and becomes impossible to start

### ISSUE THREAD

**Issue by Zarremgregarrok** [lemasato/POE-Trades-Companion#90]
When you write non color string to text color field in settings, the app not only crashes, but again crashes on startup and does not allow opening of settings again to fix the faulty string.
ie.: becoming entirely useless

**Comment by Zarremgregarrok** [comment]
Found the preferences in \Documents\AutoHotkey\POE Trades Companion and fixed them.
The self-crashing vulnerability still exists, but I am now able to use the application.

**Comment by lemasato** [comment]
My bad, I did not think about this.  
Thanks for reporting!

**Comment by lemasato** [comment]
This has been addressed on [1.12](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.12). Thanks again for finding out about this!
