### ISSUE TITLE
copy/paste maps not working since poe.trade change

### ISSUE THREAD

**Issue by CrayonCodeGit** [lemasato/POE-Trades-Companion#91]
The new format is like this: Superior Arid Lake Map (T2)
So if you paste it in the stash search it wont find it.

**Comment by lemasato** [comment]
Thank you for reporting!

**Comment by lemasato** [comment]
This has been added on [1.12](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.12), thanks for notifying me about the change!
Since PoeApp was using the same format for maps, it is now also working correctly.

**Comment by 0ldi** [comment]
why no highlighting map?
I tried a lot of maps, 

> tier: 

not working
![](http://20ld.unaux.com/152122255565_kiss_3144kb.png)

**Comment by lemasato** [comment]
That's something to do with how the map tab works (bug, most likely).  
It's not an issue with the `tier:x` search, it's an issue when combining it with a string search.  

`tier:9` alone works just fine and highlight the tier icon, the map icon, and the map item.  
`Moon Temple Map` alone works the same, highlighting all three.  
But when using `Moon Temple Map tier:9` only the map item is highlighted.  
Same thing for literal string searches `"Moon Temple Map"`, only the map item is highlighted.

**Comment by 0ldi** [comment]
> But when using Moon Temple Map tier:9 only the map item is highlighted.
>
but it does not work ... I have a whole month to manually delete prefix tier:X and it's very annoying.
No idea why it exists, can you at least add an option to remove tier:X for maps?

https://youtu.be/AVtbKZCs67g

**Comment by lemasato** [comment]
I think I'll just remove it.
Sorry you had to deal with it for this long. As you said, it's very inconvenient, and barely serves any use.

About your idea:
If your buyer wants a rare map but you end up giving him a normal one, he could get confused.
Some people like to buy specific map mods combination that others do not want, as it's convenient (and sometimes cheaper too) for them. So, I can't do that.

**Comment by 0ldi** [comment]
> About your idea:
If your buyer wants a rare map but you end up giving him a normal one, he could get confused.
Some people like to buy specific map mods combination that others do not want, as it's convenient (and sometimes cheaper too) for them. So, I can't do that.

I meant a little bit different:
1)The name of the map displayed inside the POE-Trades-Companion should remain as the buyer wrote it
2)Name of the map when you click on the Clipboard is transformed into a normal one. (because rare is not highlighted too, need to delete "rare parts" from map name ... and its annoying too)

but thanks for the update

**Comment by lemasato** [comment]
My bad, I missed the point but I get it now.
It highlights the map item, but not the category it's sitting in.

Though, I don't think that's something I'd be doing, as this behaviour sounds like another missing feature (bug) of the Map Stash Tab. It shouldn't be hard to do, but making a list of every map and their corresponding tier would be pretty time consuming and tedious. So, if that happens, it'll be post 1.13 release.
