### ISSUE TITLE
Could not detect chat key

### ISSUE THREAD

**Issue by Kazz580** [lemasato/POE-Trades-Companion#93]
As the title says, having a problem where the trade companion could not detect chat key when I invite someone to a party or do other actions. 
[2018-01-04_17-26-25.txt](https://github.com/lemasato/POE-Trades-Companion/files/1605029/2018-01-04_17-26-25.txt)
https://pastebin.com/Ku4EQgNc

**Comment by lemasato** [comment]
Sorry for taking so long to answer...  
There does not seem to be any issue with your chat key, strange that you get the message box. I did some changes to the messagebox, could you try again and send me a screenshot?
