### ISSUE TITLE
Sorry, I don't know any other way to contact you.

### ISSUE THREAD

**Issue by Loftaris** [lemasato/POE-Trades-Companion#94]
Is it possible to add a feature in the settings for If window is not active, rather than if active or always.  Would be nice to have it play a sound when I'm away rather than when I'm there only.

Thank you.

**Comment by lemasato** [comment]
Hi there,  
It's fine, you can contact me however you want.
For future reference, you can find me on: [Reddit](https://www.reddit.com/user/lemasato/) - [GGG Forums](https://www.pathofexile.com/account/view-profile/z0rhawk).
There is also a discord server, but I haven't made the url public yet.

Sorry but I don't think this would be useful.  If the GUI only appears while you are out of the game, you will be unable to use it.  You would have to tab out of the game to press any button.

**Comment by Loftaris** [comment]
The reason I would like this feature is because I have a file I used to run
on another app that no longer works.. I use it when I'm out of poe to send
me a text message when I get a message.  I'm looking for something to
recreate this feature. That's why I reached out to you.

**Comment by Loftaris** [comment]
Another option would be to simply have a field dedicated to "if window is
out of focus play this file" that would be fandiddilytastic!
