### ISSUE TITLE
As of today I cannot make any version work. Win 8.1

### ISSUE THREAD

**Issue by sclient** [lemasato/POE-Trades-Companion#95]
Used the newest beta, and all of a sudden it wont show the window by any means. Tried rebooting, the save and preview wouldnt draw it, reloading the tool doesnt help, and I tried the last stable version as well.

**Comment by lemasato** [comment]
(The latest beta version is exactly the same as 1.12.2)

`Documents\AutoHotkey\POE Trades Companion\`
Make a backup of your Preferences.ini file then delete the original.
Restart the tool and see if it helps.

**Comment by sclient** [comment]
Ok that seems to have worked. Is there any save way to get back my prefs? Id made a good bit of custom replies and such.

**Comment by lemasato** [comment]
The default colour scheme should be just like on this screenshot
![Theme](https://raw.githubusercontent.com/lemasato/POE-Trades-Companion/dev/Resources/Skins/Path%20of%20Exile/Preview.png)

Could you send me your corrupted Preferences.ini so I can inspect and see what went wrong?

**Comment by sclient** [comment]
[Preferences.zip](https://github.com/lemasato/POE-Trades-Companion/files/1633420/Preferences.zip)
Sure.. For some reason on mine after I delete the prefs, all the letters show as black (and are set that way by the hex codes).

**Comment by lemasato** [comment]
It could be that the GUI position was out of your screen.
```
X_POS=1418
Y_POS=-1080
```
Means it was positioned 1080 pixels above your main monitor.  
Do you (or did you use to) have a secondary monitor set up to be above your main one?

About your "black text" issue, are you sure that you changed the preset and not just the skin?

**Comment by sclient** [comment]
Yeah, I have a second monitor.. It looks like I didnt change the preset as well as the skin.

I did notice another thing, quite frequently when I hit the trade button, it just comes up like a whisper attempt.

**Comment by lemasato** [comment]
The tool ended up being out of your monitor area. I should prevent this from happening...
If this issue ever happens again: Right click on the tray icon > Click on `Mode: Overlay` > Click back on `Mode: Window` > The GUI will now be located on the top right of your main monitor.

Like a whisper attempt?
![Metal Gear?](https://i.imgur.com/L8559SX.jpg?1) Something like this?

**Comment by sclient** [comment]
Yes, except the text field is just blank.. Ill have to look closer next time it does that to be 100%.

**Comment by Sikksens** [comment]
I'm having a similar issue, none of my commands are working, I've left all the default settings in place
and when clicking a button like invite I see the chat window appear for a split second then disappear again with no invite sent, same goes for all other chat input commands.

I have a 3 monitor setup but using the app on my main PoE monitor.

**Comment by lemasato** [comment]
@Sikksens Sounds like a clipboard issue to me.
Make sure you aren't running anything that could interfere with the clipboard.

**Comment by Sikksens** [comment]
Ah ofc, I forgot to mention that I am using it alongside the Trade-Macro, and in trying it now without the Trade-Macro running it works perfectly.

**Comment by lemasato** [comment]
Weird, I'm running both together on a daily basis and no issue (using default settings on TradeMacro, with only Pre-Fill Min/Max values disabled).
See if updating to the latest [AHK version](https://autohotkey.com/download/) makes any change.

**Comment by Sikksens** [comment]
Thank you, they are now both working, for some reason I had _Put tooltip results on clipboard_ checked which was interfering with the clipboard.

**Comment by lemasato** [comment]
Sweet, I'll see if there is anything I can do about it.
