### ISSUE TITLE
Shortcut in startup folder doesn't start TC

### ISSUE THREAD

**Issue by damoochie** [lemasato/POE-Trades-Companion#97]
I've setup a few scripts to automatically load upon startup by placing shortcuts in the windows startup folder. They all startup fine except for Trades Companion which doesn't start at all. It does however startup normally like the others if I place the .exe itself in the startup folder. Only problem for me is, when it goes through an update (like today), it brings up a blue box error and I have to sort out the update manually each time.

It's no biggie really, but it'd be nice to set it once and not have to think about it :)

**Comment by lemasato** [comment]
Tested on W7 x64, script starts just fine on startup.  
Do the script not load at all (no "reloading in..." green box)?  
Could you see if the /NoAdmin parameter helps? `"C:\Path\POE Trades Companion.exe" /NoAdmin`

**Comment by damoochie** [comment]
Just to clarify; the ' /NoAdmin ' parameter gets added to the shortcut, yeah? Assuming it's a yes, this didn't work unfortunately. I get the sense it's not being opened at all because nothing happens with TC (no green box, or tray icon) while the others load up normally. I also checked the "Run this as Administrator" option and made sure all the permissions were checked.

Could loading too many scripts on startup cause conflicts? I have 5, including TC. Three are very basic scripts i wrote for keyboard mapping stuff but "TradeMacro" is obviously more complex and seems to take a long time to load so I'm thinking this could be a factor.

And like I said, it's no big deal really. Im probably wasting more time trying to set this up than just copying the exe to the startup directory after each TC update :p

**Comment by lemasato** [comment]
Tried running a dozen of random scripts on startup, no issue. Though, I dont think having many scripts running on startup would make a difference.  
You could try using CCleaner, in Tools > Startup, and see if the tool appears there.  

As a workaround, you could also use a .bat script (example):
```
@echo off
cd "C:\Game Tools"
"POE Trades Companion.lnk"
```

**Comment by damoochie** [comment]
Thanks! I used the .bat script and it loads on startup now.

I also tried CCleaner before the .bat script option and saw it appears as enabled for 'POE Trade Companion.exe.Ink' (double extension unusual?). It didn't change anything though.

This thread can be closed 😀

**Comment by lemasato** [comment]
Glad the workaround worked!

The "double extension" is to be expected, since the shortcut file (.lnk) is linked to an executable file (.exe). By default, when creating a shortcut, it will be named `source file name.extension.lnk - Shortcut` (creating a shortcut for `Example File.exe` will result in `Example File.exe - Shortcut.lnk`)  

Though, you may rename the .lnk file however you want, as long as you keep its extension (.lnk). You could rename it "Start POE-TC.lnk" and it would work just fine.
