### ISSUE TITLE
cant start using companion

### ISSUE THREAD

**Issue by garaika** [lemasato/POE-Trades-Companion#98]
got this on any launch....try to full delete, root new downloads companion
![default](https://user-images.githubusercontent.com/9705964/35770991-d1ef151e-0936-11e8-9059-d27d9d59da8d.png)

this r settings
![default](https://user-images.githubusercontent.com/9705964/35771007-077b6d2c-0937-11e8-8484-126596938de3.png)
![default](https://user-images.githubusercontent.com/9705964/35771010-145afb48-0937-11e8-910b-e6182cc47334.png)

**Comment by lemasato** [comment]
Are you still having the issue?  
It seems to be related to one of the smaller buttons.

**Comment by garaika** [comment]
no, solve this problem by delete folder from "My Documents"

p.s. sorry my "perfect engilsh"
