### ISSUE TITLE
Error - Can't start companion

### ISSUE THREAD

**Issue by wjashin** [lemasato/POE-Trades-Companion#99]
As i start the application this message pops up: Error: Expecting JSON value(string, number, true, false, null, object or array)

Here's a screenshot.

![immagine](https://user-images.githubusercontent.com/37018079/36934522-7416a19e-1eeb-11e8-9a97-995ce04d29f7.jpg)

How do i solve this?

**Comment by lemasato** [comment]
How long have you been getting this?  
Are you sure it's not related to the server downtime that happened just now?

**Comment by wjashin** [comment]
It worked yesterday and yeah, maybe it's that. I'll try again later and let you know if that was the problem.

**Comment by lemasato** [comment]
Normally, you should work now.  
If not, you may want to flush your dns:
`Win+R` > `cmd` > `ipconfig /flushdns`
If that still doesn't work, see if you can access the [Leagues API](http://api.pathofexile.com/leagues?type=main)

**Comment by wjashin** [comment]
Ok that was the problem! Thanks for the quick answer!

**Comment by lemasato** [comment]
Glad it's sorted out!
Good luck on the league!
